// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.


suite("test_cast_to_decimal256_from_float_const") {

    // This test case is generated from the correspoinding be UT test case,
    // update this case if the correspoinding be UT test case is updated,
    // e.g.: ../run-be-ut.sh --run --filter=FunctionCastToDecimalTest.test_from_string --gen_regression_case
    sql "set enable_strict_cast=true;"
    qt_sql_0_strict """select cast(cast("0.04" as float) as decimalv3(76, 0));"""
    qt_sql_1_strict """select cast(cast("1.04" as float) as decimalv3(76, 0));"""
    qt_sql_2_strict """select cast(cast("9.04" as float) as decimalv3(76, 0));"""
    qt_sql_3_strict """select cast(cast("0.05" as float) as decimalv3(76, 0));"""
    qt_sql_4_strict """select cast(cast("1.05" as float) as decimalv3(76, 0));"""
    qt_sql_5_strict """select cast(cast("9.05" as float) as decimalv3(76, 0));"""
    qt_sql_6_strict """select cast(cast("-0.04" as float) as decimalv3(76, 0));"""
    qt_sql_7_strict """select cast(cast("-1.04" as float) as decimalv3(76, 0));"""
    qt_sql_8_strict """select cast(cast("-9.04" as float) as decimalv3(76, 0));"""
    qt_sql_9_strict """select cast(cast("-0.05" as float) as decimalv3(76, 0));"""
    qt_sql_10_strict """select cast(cast("-1.05" as float) as decimalv3(76, 0));"""
    qt_sql_11_strict """select cast(cast("-9.05" as float) as decimalv3(76, 0));"""
    sql "set enable_strict_cast=false;"
    qt_sql_0_non_strict """select cast(cast("0.04" as float) as decimalv3(76, 0));"""
    qt_sql_1_non_strict """select cast(cast("1.04" as float) as decimalv3(76, 0));"""
    qt_sql_2_non_strict """select cast(cast("9.04" as float) as decimalv3(76, 0));"""
    qt_sql_3_non_strict """select cast(cast("0.05" as float) as decimalv3(76, 0));"""
    qt_sql_4_non_strict """select cast(cast("1.05" as float) as decimalv3(76, 0));"""
    qt_sql_5_non_strict """select cast(cast("9.05" as float) as decimalv3(76, 0));"""
    qt_sql_6_non_strict """select cast(cast("-0.04" as float) as decimalv3(76, 0));"""
    qt_sql_7_non_strict """select cast(cast("-1.04" as float) as decimalv3(76, 0));"""
    qt_sql_8_non_strict """select cast(cast("-9.04" as float) as decimalv3(76, 0));"""
    qt_sql_9_non_strict """select cast(cast("-0.05" as float) as decimalv3(76, 0));"""
    qt_sql_10_non_strict """select cast(cast("-1.05" as float) as decimalv3(76, 0));"""
    qt_sql_11_non_strict """select cast(cast("-9.05" as float) as decimalv3(76, 0));"""
    sql "set enable_strict_cast=true;"
    qt_sql_12_strict """select cast(cast("4e-39" as float) as decimalv3(76, 38));"""
    qt_sql_13_strict """select cast(cast("1.4e-38" as float) as decimalv3(76, 38));"""
    qt_sql_14_strict """select cast(cast("9.4e-38" as float) as decimalv3(76, 38));"""
    qt_sql_15_strict """select cast(cast("0.1" as float) as decimalv3(76, 38));"""
    qt_sql_16_strict """select cast(cast("0.9" as float) as decimalv3(76, 38));"""
    qt_sql_17_strict """select cast(cast("0.9" as float) as decimalv3(76, 38));"""
    qt_sql_18_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_19_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_20_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_21_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_22_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_23_strict """select cast(cast("1.1" as float) as decimalv3(76, 38));"""
    qt_sql_24_strict """select cast(cast("5e-39" as float) as decimalv3(76, 38));"""
    qt_sql_25_strict """select cast(cast("1.5e-38" as float) as decimalv3(76, 38));"""
    qt_sql_26_strict """select cast(cast("9.5e-38" as float) as decimalv3(76, 38));"""
    qt_sql_27_strict """select cast(cast("0.1" as float) as decimalv3(76, 38));"""
    qt_sql_28_strict """select cast(cast("0.9" as float) as decimalv3(76, 38));"""
    qt_sql_29_strict """select cast(cast("0.9" as float) as decimalv3(76, 38));"""
    qt_sql_30_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_31_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_32_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_33_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_34_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_35_strict """select cast(cast("1.1" as float) as decimalv3(76, 38));"""
    qt_sql_36_strict """select cast(cast("-4e-39" as float) as decimalv3(76, 38));"""
    qt_sql_37_strict """select cast(cast("-1.4e-38" as float) as decimalv3(76, 38));"""
    qt_sql_38_strict """select cast(cast("-9.4e-38" as float) as decimalv3(76, 38));"""
    qt_sql_39_strict """select cast(cast("-0.1" as float) as decimalv3(76, 38));"""
    qt_sql_40_strict """select cast(cast("-0.9" as float) as decimalv3(76, 38));"""
    qt_sql_41_strict """select cast(cast("-0.9" as float) as decimalv3(76, 38));"""
    qt_sql_42_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_43_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_44_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_45_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_46_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_47_strict """select cast(cast("-1.1" as float) as decimalv3(76, 38));"""
    qt_sql_48_strict """select cast(cast("-5e-39" as float) as decimalv3(76, 38));"""
    qt_sql_49_strict """select cast(cast("-1.5e-38" as float) as decimalv3(76, 38));"""
    qt_sql_50_strict """select cast(cast("-9.5e-38" as float) as decimalv3(76, 38));"""
    qt_sql_51_strict """select cast(cast("-0.1" as float) as decimalv3(76, 38));"""
    qt_sql_52_strict """select cast(cast("-0.9" as float) as decimalv3(76, 38));"""
    qt_sql_53_strict """select cast(cast("-0.9" as float) as decimalv3(76, 38));"""
    qt_sql_54_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_55_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_56_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_57_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_58_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_59_strict """select cast(cast("-1.1" as float) as decimalv3(76, 38));"""
    sql "set enable_strict_cast=false;"
    qt_sql_12_non_strict """select cast(cast("4e-39" as float) as decimalv3(76, 38));"""
    qt_sql_13_non_strict """select cast(cast("1.4e-38" as float) as decimalv3(76, 38));"""
    qt_sql_14_non_strict """select cast(cast("9.4e-38" as float) as decimalv3(76, 38));"""
    qt_sql_15_non_strict """select cast(cast("0.1" as float) as decimalv3(76, 38));"""
    qt_sql_16_non_strict """select cast(cast("0.9" as float) as decimalv3(76, 38));"""
    qt_sql_17_non_strict """select cast(cast("0.9" as float) as decimalv3(76, 38));"""
    qt_sql_18_non_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_19_non_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_20_non_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_21_non_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_22_non_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_23_non_strict """select cast(cast("1.1" as float) as decimalv3(76, 38));"""
    qt_sql_24_non_strict """select cast(cast("5e-39" as float) as decimalv3(76, 38));"""
    qt_sql_25_non_strict """select cast(cast("1.5e-38" as float) as decimalv3(76, 38));"""
    qt_sql_26_non_strict """select cast(cast("9.5e-38" as float) as decimalv3(76, 38));"""
    qt_sql_27_non_strict """select cast(cast("0.1" as float) as decimalv3(76, 38));"""
    qt_sql_28_non_strict """select cast(cast("0.9" as float) as decimalv3(76, 38));"""
    qt_sql_29_non_strict """select cast(cast("0.9" as float) as decimalv3(76, 38));"""
    qt_sql_30_non_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_31_non_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_32_non_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_33_non_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_34_non_strict """select cast(cast("1" as float) as decimalv3(76, 38));"""
    qt_sql_35_non_strict """select cast(cast("1.1" as float) as decimalv3(76, 38));"""
    qt_sql_36_non_strict """select cast(cast("-4e-39" as float) as decimalv3(76, 38));"""
    qt_sql_37_non_strict """select cast(cast("-1.4e-38" as float) as decimalv3(76, 38));"""
    qt_sql_38_non_strict """select cast(cast("-9.4e-38" as float) as decimalv3(76, 38));"""
    qt_sql_39_non_strict """select cast(cast("-0.1" as float) as decimalv3(76, 38));"""
    qt_sql_40_non_strict """select cast(cast("-0.9" as float) as decimalv3(76, 38));"""
    qt_sql_41_non_strict """select cast(cast("-0.9" as float) as decimalv3(76, 38));"""
    qt_sql_42_non_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_43_non_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_44_non_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_45_non_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_46_non_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_47_non_strict """select cast(cast("-1.1" as float) as decimalv3(76, 38));"""
    qt_sql_48_non_strict """select cast(cast("-5e-39" as float) as decimalv3(76, 38));"""
    qt_sql_49_non_strict """select cast(cast("-1.5e-38" as float) as decimalv3(76, 38));"""
    qt_sql_50_non_strict """select cast(cast("-9.5e-38" as float) as decimalv3(76, 38));"""
    qt_sql_51_non_strict """select cast(cast("-0.1" as float) as decimalv3(76, 38));"""
    qt_sql_52_non_strict """select cast(cast("-0.9" as float) as decimalv3(76, 38));"""
    qt_sql_53_non_strict """select cast(cast("-0.9" as float) as decimalv3(76, 38));"""
    qt_sql_54_non_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_55_non_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_56_non_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_57_non_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_58_non_strict """select cast(cast("-1" as float) as decimalv3(76, 38));"""
    qt_sql_59_non_strict """select cast(cast("-1.1" as float) as decimalv3(76, 38));"""
    sql "set enable_strict_cast=true;"
    qt_sql_60_strict """select cast(cast("0" as float) as decimalv3(76, 75));"""
    qt_sql_61_strict """select cast(cast("0" as float) as decimalv3(76, 75));"""
    qt_sql_62_strict """select cast(cast("0" as float) as decimalv3(76, 75));"""
    qt_sql_63_strict """select cast(cast("0" as float) as decimalv3(76, 75));"""
    qt_sql_64_strict """select cast(cast("0" as float) as decimalv3(76, 75));"""
    qt_sql_65_strict """select cast(cast("0" as float) as decimalv3(76, 75));"""
    qt_sql_66_strict """select cast(cast("-0" as float) as decimalv3(76, 75));"""
    qt_sql_67_strict """select cast(cast("-0" as float) as decimalv3(76, 75));"""
    qt_sql_68_strict """select cast(cast("-0" as float) as decimalv3(76, 75));"""
    qt_sql_69_strict """select cast(cast("-0" as float) as decimalv3(76, 75));"""
    qt_sql_70_strict """select cast(cast("-0" as float) as decimalv3(76, 75));"""
    qt_sql_71_strict """select cast(cast("-0" as float) as decimalv3(76, 75));"""
    sql "set enable_strict_cast=false;"
    qt_sql_60_non_strict """select cast(cast("0" as float) as decimalv3(76, 75));"""
    qt_sql_61_non_strict """select cast(cast("0" as float) as decimalv3(76, 75));"""
    qt_sql_62_non_strict """select cast(cast("0" as float) as decimalv3(76, 75));"""
    qt_sql_63_non_strict """select cast(cast("0" as float) as decimalv3(76, 75));"""
    qt_sql_64_non_strict """select cast(cast("0" as float) as decimalv3(76, 75));"""
    qt_sql_65_non_strict """select cast(cast("0" as float) as decimalv3(76, 75));"""
    qt_sql_66_non_strict """select cast(cast("-0" as float) as decimalv3(76, 75));"""
    qt_sql_67_non_strict """select cast(cast("-0" as float) as decimalv3(76, 75));"""
    qt_sql_68_non_strict """select cast(cast("-0" as float) as decimalv3(76, 75));"""
    qt_sql_69_non_strict """select cast(cast("-0" as float) as decimalv3(76, 75));"""
    qt_sql_70_non_strict """select cast(cast("-0" as float) as decimalv3(76, 75));"""
    qt_sql_71_non_strict """select cast(cast("-0" as float) as decimalv3(76, 75));"""
}