-- SELECT /*+SET_VAR(enable_fallback_to_original_planner=false) */
--     concat('https://github.com/', cast(v["repo"]["name"] as string), '/commit/', cast(v["payload"]["commit_id"] as string)) URL,
--     cast(v["payload"]["commit_id"] as string) AS commit_id,
--     count() AS comments,
--     count(distinct cast(v["actor"]["login"] as string)) AS authors
-- FROM github_events
-- WHERE (cast(v["type"] as string) = 'CommitCommentEvent') AND commit_id != ""
-- GROUP BY
--     cast(v["repo"]["name"] as string),
--     commit_id 
-- HAVING authors >= 10
-- ORDER BY count() DESC, URL, authors
-- LIMIT 50
