-- TABLES: lineitem

SELECT SUM(CAST(var["L_EXTENDEDPRICE"] AS DOUBLE) * CAST(var["L_DISCOUNT"] AS DOUBLE)) AS REVENUE
FROM
  lineitem
WHERE
  CAST(var["L_SHIPDATE"] AS DATE) >= DATE '1994-01-01'
  AND CAST(var["L_SHIPDATE"] AS DATE) < DATE '1994-01-01' + INTERVAL '1' YEAR
AND CAST(var["L_DISCOUNT"] AS DOUBLE) BETWEEN 0.06 - 0.01 AND .06 + 0.01
AND CAST(var["L_QUANTITY"] AS DOUBLE) < 24

