header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - "dist"
    - "licenses"
    - "**/*.md"
    - "LICENSE"
    - "NOTICE"
    - "DISCLAIMER"
    - ".clang-format"
    - ".clang-format-ignore"
    - ".clang-tidy"
    - ".gitattributes"
    - ".gitignore"
    - ".gitmodules"
    - ".licenserc.yaml"
    - ".rat-excludes"
    - "be/src/common/status.cpp"
    - "be/src/common/status.h"
    - "be/src/env/env.h"
    - "be/src/env/env_posix.cpp"
    - "**/glibc-compatibility/**"
    - "**/gutil/**"
    - "**/test_data/**"
    - "**/jmockit/**"
    - "**/*.json"
    - "**/*.dat"
    - "**/*.svg"
    - "**/*.md5"
    - "**/*.patch"
    - "**/*.log"
    - "**/*.sql"
    - "**/*.lock"
    - "tsan_suppressions"
    - "docs/.markdownlintignore"
    - "fe/fe-core/src/test/resources/data/net_snmp_normal"
    - "fe/fe-core/src/main/antlr4/org/apache/doris/nereids/JavaLexer.g4"
    - "fe/fe-core/src/main/antlr4/org/apache/doris/nereids/JavaParser.g4"
    - "be/src/common/signal_handler.h"
    - "be/src/olap/lru_cache.cpp"
    - "be/src/olap/lru_cache.h"
    - "be/src/olap/skiplist.h"
    - "be/src/runtime/string_search.hpp"
    - "be/src/util/coding.cpp"
    - "be/src/util/coding.h"
    - "be/src/util/condition_variable.cpp"
    - "be/src/util/condition_variable.h"
    - "be/src/util/murmur_hash3.cpp"
    - "be/src/util/murmur_hash3.h"
    - "be/src/util/mustache/mustache.cc"
    - "be/src/util/mustache/mustache.h"
    - "be/src/util/sse2neo.h"
    - "be/src/util/sse2neon.h"
    - "be/src/util/utf8_check.cpp"
    - "build-support/run_clang_format.py"
    - "regression-test/data"
    - "docs/.vuepress/public/css/animate.min.css"
    - "docs/.vuepress/public/js/jquery.min.js"
    - "docs/.vuepress/public/js/wow.min.js"
    - "docs/package-lock.json"

  comment: on-failure
