-- SELECT
--     lower(split_part(repo_name, '/', 1)) AS org,
--     count(distinct actor_login) AS authors,
--     count(distinct pr_author) AS pr_authors,
--     count(distinct issue_author) AS issue_authors,
--     count(distinct comment_author) AS comment_authors,
--     count(distinct review_author) AS review_authors,
--     count(distinct push_author) AS push_authors
-- FROM
-- (
-- SELECT
--     repo_name,
--     actor_login,
--     CASE WHEN event_type = 'PullRequestEvent' THEN actor_login ELSE NULL END pr_author,
--     CASE WHEN event_type = 'IssuesEvent' THEN actor_login ELSE NULL END issue_author,
--     CASE WHEN event_type = 'IssueCommentEvent' THEN actor_login ELSE NULL END comment_author,
--     CASE WHEN event_type = 'PullRequestReviewCommentEvent' THEN actor_login ELSE NULL END review_author,
--     CASE WHEN event_type = 'PushEvent' THEN actor_login ELSE NULL END push_author
-- FROM github_events
-- WHERE event_type IN ('PullRequestEvent', 'IssuesEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent', 'PushEvent')
-- ) t
-- GROUP BY org
-- ORDER BY authors DESC
