// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

suite("nereids_win_fn") {
	sql 'use regression_test_nereids_function_p0'
	sql 'set enable_nereids_planner=true'
	sql 'set enable_fallback_to_original_planner=false'
	qt_sql_dense_rank '''
		select kint, ksint dense_rank() over() as wf from fn_test'''
	qt_sql_dense_rank_notnull '''
		select kint, ksint dense_rank() over() as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_ob '''
		select kint, ksint dense_rank() over(order by kint) as wf from fn_test'''
	qt_sql_dense_rank_ob_notnull '''
		select kint, ksint dense_rank() over(order by kint) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_1 '''
		select kint, ksint dense_rank() over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_2 '''
		select kint, ksint dense_rank() over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_3 '''
		select kint, ksint dense_rank() over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_4 '''
		select kint, ksint dense_rank() over(order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_5 '''
		select kint, ksint dense_rank() over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_6 '''
		select kint, ksint dense_rank() over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_7 '''
		select kint, ksint dense_rank() over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_8 '''
		select kint, ksint dense_rank() over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_9 '''
		select kint, ksint dense_rank() over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_10 '''
		select kint, ksint dense_rank() over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_11 '''
		select kint, ksint dense_rank() over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_12 '''
		select kint, ksint dense_rank() over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_13 '''
		select kint, ksint dense_rank() over(order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_14 '''
		select kint, ksint dense_rank() over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_15 '''
		select kint, ksint dense_rank() over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_16 '''
		select kint, ksint dense_rank() over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_17 '''
		select kint, ksint dense_rank() over(order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_18 '''
		select kint, ksint dense_rank() over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_19 '''
		select kint, ksint dense_rank() over(order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_20 '''
		select kint, ksint dense_rank() over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_21 '''
		select kint, ksint dense_rank() over(order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_22 '''
		select kint, ksint dense_rank() over(order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_23 '''
		select kint, ksint dense_rank() over(order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_24 '''
		select kint, ksint dense_rank() over(order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_25 '''
		select kint, ksint dense_rank() over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_notnull_26 '''
		select kint, ksint dense_rank() over(order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_pb '''
		select kint, ksint dense_rank() over(partition by kstr) as wf from fn_test'''
	qt_sql_dense_rank_pb_notnull '''
		select kint, ksint dense_rank() over(partition by kstr) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_pb_ob '''
		select kint, ksint dense_rank() over(partition by kstr order by kint) as wf from fn_test'''
	qt_sql_dense_rank_pb_ob_notnull '''
		select kint, ksint dense_rank() over(partition by kstr order by kint) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_1 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_2 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_3 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_4 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_5 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_6 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_7 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_8 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_9 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_10 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_11 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_12 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_13 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_14 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_15 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_16 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_17 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_18 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_19 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_20 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_21 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_22 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_23 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_24 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_25 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_dense_rank_f_pb_notnull_26 '''
		select kint, ksint dense_rank() over(partition by kstr order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''

	qt_sql_first_value '''
		select kint, ksint first_value(kint) over() as wf from fn_test'''
	qt_sql_first_value_notnull '''
		select kint, ksint first_value(kint) over() as wf from fn_test_not_nullable'''
	qt_sql_first_value_ob '''
		select kint, ksint first_value(kint) over(order by kint) as wf from fn_test'''
	qt_sql_first_value_ob_notnull '''
		select kint, ksint first_value(kint) over(order by kint) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_1 '''
		select kint, ksint first_value(kint) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_2 '''
		select kint, ksint first_value(kint) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_3 '''
		select kint, ksint first_value(kint) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_4 '''
		select kint, ksint first_value(kint) over(order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_5 '''
		select kint, ksint first_value(kint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_6 '''
		select kint, ksint first_value(kint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_7 '''
		select kint, ksint first_value(kint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_8 '''
		select kint, ksint first_value(kint) over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_9 '''
		select kint, ksint first_value(kint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_10 '''
		select kint, ksint first_value(kint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_11 '''
		select kint, ksint first_value(kint) over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_12 '''
		select kint, ksint first_value(kint) over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_13 '''
		select kint, ksint first_value(kint) over(order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_14 '''
		select kint, ksint first_value(kint) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_15 '''
		select kint, ksint first_value(kint) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_16 '''
		select kint, ksint first_value(kint) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_17 '''
		select kint, ksint first_value(kint) over(order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_18 '''
		select kint, ksint first_value(kint) over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_19 '''
		select kint, ksint first_value(kint) over(order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_20 '''
		select kint, ksint first_value(kint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_21 '''
		select kint, ksint first_value(kint) over(order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_22 '''
		select kint, ksint first_value(kint) over(order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_23 '''
		select kint, ksint first_value(kint) over(order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_24 '''
		select kint, ksint first_value(kint) over(order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_25 '''
		select kint, ksint first_value(kint) over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_notnull_26 '''
		select kint, ksint first_value(kint) over(order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_pb '''
		select kint, ksint first_value(kint) over(partition by kstr) as wf from fn_test'''
	qt_sql_first_value_pb_notnull '''
		select kint, ksint first_value(kint) over(partition by kstr) as wf from fn_test_not_nullable'''
	qt_sql_first_value_pb_ob '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint) as wf from fn_test'''
	qt_sql_first_value_pb_ob_notnull '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_1 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_2 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_3 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_4 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_5 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_6 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_7 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_8 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_9 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_10 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_11 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_12 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_13 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_14 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_15 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_16 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_17 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_18 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_19 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_20 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_21 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_22 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_23 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_24 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_25 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_first_value_f_pb_notnull_26 '''
		select kint, ksint first_value(kint) over(partition by kstr order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''

	qt_sql_lag '''
		select kint, ksint lag(kint, 2, 1) over() as wf from fn_test'''
	qt_sql_lag_notnull '''
		select kint, ksint lag(kint, 2, 1) over() as wf from fn_test_not_nullable'''
	qt_sql_lag_ob '''
		select kint, ksint lag(kint, 2, 1) over(order by kint) as wf from fn_test'''
	qt_sql_lag_ob_notnull '''
		select kint, ksint lag(kint, 2, 1) over(order by kint) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_1 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_2 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_3 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_4 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_5 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_6 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_7 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_8 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_9 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_10 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_11 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_12 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_13 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_14 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_15 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_16 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_17 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_18 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_19 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_20 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_21 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_22 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_23 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_24 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_25 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_notnull_26 '''
		select kint, ksint lag(kint, 2, 1) over(order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_pb '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr) as wf from fn_test'''
	qt_sql_lag_pb_notnull '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr) as wf from fn_test_not_nullable'''
	qt_sql_lag_pb_ob '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint) as wf from fn_test'''
	qt_sql_lag_pb_ob_notnull '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_1 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_2 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_3 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_4 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_5 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_6 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_7 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_8 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_9 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_10 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_11 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_12 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_13 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_14 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_15 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_16 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_17 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_18 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_19 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_20 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_21 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_22 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_23 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_24 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_25 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lag_f_pb_notnull_26 '''
		select kint, ksint lag(kint, 2, 1) over(partition by kstr order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''

	qt_sql_last_value '''
		select kint, ksint last_value(kint) over() as wf from fn_test'''
	qt_sql_last_value_notnull '''
		select kint, ksint last_value(kint) over() as wf from fn_test_not_nullable'''
	qt_sql_last_value_ob '''
		select kint, ksint last_value(kint) over(order by kint) as wf from fn_test'''
	qt_sql_last_value_ob_notnull '''
		select kint, ksint last_value(kint) over(order by kint) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_1 '''
		select kint, ksint last_value(kint) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_2 '''
		select kint, ksint last_value(kint) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_3 '''
		select kint, ksint last_value(kint) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_4 '''
		select kint, ksint last_value(kint) over(order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_5 '''
		select kint, ksint last_value(kint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_6 '''
		select kint, ksint last_value(kint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_7 '''
		select kint, ksint last_value(kint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_8 '''
		select kint, ksint last_value(kint) over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_9 '''
		select kint, ksint last_value(kint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_10 '''
		select kint, ksint last_value(kint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_11 '''
		select kint, ksint last_value(kint) over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_12 '''
		select kint, ksint last_value(kint) over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_13 '''
		select kint, ksint last_value(kint) over(order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_14 '''
		select kint, ksint last_value(kint) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_15 '''
		select kint, ksint last_value(kint) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_16 '''
		select kint, ksint last_value(kint) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_17 '''
		select kint, ksint last_value(kint) over(order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_18 '''
		select kint, ksint last_value(kint) over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_19 '''
		select kint, ksint last_value(kint) over(order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_20 '''
		select kint, ksint last_value(kint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_21 '''
		select kint, ksint last_value(kint) over(order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_22 '''
		select kint, ksint last_value(kint) over(order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_23 '''
		select kint, ksint last_value(kint) over(order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_24 '''
		select kint, ksint last_value(kint) over(order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_25 '''
		select kint, ksint last_value(kint) over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_notnull_26 '''
		select kint, ksint last_value(kint) over(order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_pb '''
		select kint, ksint last_value(kint) over(partition by kstr) as wf from fn_test'''
	qt_sql_last_value_pb_notnull '''
		select kint, ksint last_value(kint) over(partition by kstr) as wf from fn_test_not_nullable'''
	qt_sql_last_value_pb_ob '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint) as wf from fn_test'''
	qt_sql_last_value_pb_ob_notnull '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_1 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_2 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_3 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_4 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_5 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_6 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_7 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_8 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_9 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_10 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_11 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_12 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_13 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_14 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_15 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_16 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_17 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_18 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_19 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_20 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_21 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_22 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_23 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_24 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_25 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_last_value_f_pb_notnull_26 '''
		select kint, ksint last_value(kint) over(partition by kstr order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''

	qt_sql_lead '''
		select kint, ksint lead(kint, 2, 1) over() as wf from fn_test'''
	qt_sql_lead_notnull '''
		select kint, ksint lead(kint, 2, 1) over() as wf from fn_test_not_nullable'''
	qt_sql_lead_ob '''
		select kint, ksint lead(kint, 2, 1) over(order by kint) as wf from fn_test'''
	qt_sql_lead_ob_notnull '''
		select kint, ksint lead(kint, 2, 1) over(order by kint) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_1 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_2 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_3 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_4 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_5 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_6 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_7 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_8 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_9 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_10 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_11 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_12 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_13 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_14 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_15 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_16 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_17 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_18 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_19 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_20 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_21 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_22 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_23 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_24 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_25 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_notnull_26 '''
		select kint, ksint lead(kint, 2, 1) over(order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_pb '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr) as wf from fn_test'''
	qt_sql_lead_pb_notnull '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr) as wf from fn_test_not_nullable'''
	qt_sql_lead_pb_ob '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint) as wf from fn_test'''
	qt_sql_lead_pb_ob_notnull '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_1 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_2 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_3 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_4 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_5 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_6 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_7 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_8 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_9 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_10 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_11 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_12 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_13 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_14 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_15 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_16 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_17 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_18 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_19 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_20 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_21 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_22 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_23 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_24 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_25 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_lead_f_pb_notnull_26 '''
		select kint, ksint lead(kint, 2, 1) over(partition by kstr order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''

	qt_sql_ntile '''
		select kint, ksint ntile(3) over() as wf from fn_test'''
	qt_sql_ntile_notnull '''
		select kint, ksint ntile(3) over() as wf from fn_test_not_nullable'''
	qt_sql_ntile_ob '''
		select kint, ksint ntile(3) over(order by kint) as wf from fn_test'''
	qt_sql_ntile_ob_notnull '''
		select kint, ksint ntile(3) over(order by kint) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_1 '''
		select kint, ksint ntile(3) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_2 '''
		select kint, ksint ntile(3) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_3 '''
		select kint, ksint ntile(3) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_4 '''
		select kint, ksint ntile(3) over(order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_5 '''
		select kint, ksint ntile(3) over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_6 '''
		select kint, ksint ntile(3) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_7 '''
		select kint, ksint ntile(3) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_8 '''
		select kint, ksint ntile(3) over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_9 '''
		select kint, ksint ntile(3) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_10 '''
		select kint, ksint ntile(3) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_11 '''
		select kint, ksint ntile(3) over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_12 '''
		select kint, ksint ntile(3) over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_13 '''
		select kint, ksint ntile(3) over(order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_14 '''
		select kint, ksint ntile(3) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_15 '''
		select kint, ksint ntile(3) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_16 '''
		select kint, ksint ntile(3) over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_17 '''
		select kint, ksint ntile(3) over(order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_18 '''
		select kint, ksint ntile(3) over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_19 '''
		select kint, ksint ntile(3) over(order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_20 '''
		select kint, ksint ntile(3) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_21 '''
		select kint, ksint ntile(3) over(order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_22 '''
		select kint, ksint ntile(3) over(order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_23 '''
		select kint, ksint ntile(3) over(order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_24 '''
		select kint, ksint ntile(3) over(order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_25 '''
		select kint, ksint ntile(3) over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_notnull_26 '''
		select kint, ksint ntile(3) over(order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_pb '''
		select kint, ksint ntile(3) over(partition by kstr) as wf from fn_test'''
	qt_sql_ntile_pb_notnull '''
		select kint, ksint ntile(3) over(partition by kstr) as wf from fn_test_not_nullable'''
	qt_sql_ntile_pb_ob '''
		select kint, ksint ntile(3) over(partition by kstr order by kint) as wf from fn_test'''
	qt_sql_ntile_pb_ob_notnull '''
		select kint, ksint ntile(3) over(partition by kstr order by kint) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_1 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_2 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_3 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_4 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_5 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_6 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_7 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_8 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_9 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_10 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_11 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_12 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_13 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_14 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_15 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_16 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_17 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_18 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_19 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_20 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_21 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_22 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_23 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_24 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_25 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_ntile_f_pb_notnull_26 '''
		select kint, ksint ntile(3) over(partition by kstr order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''

	qt_sql_rank '''
		select kint, ksint rank() over() as wf from fn_test'''
	qt_sql_rank_notnull '''
		select kint, ksint rank() over() as wf from fn_test_not_nullable'''
	qt_sql_rank_ob '''
		select kint, ksint rank() over(order by kint) as wf from fn_test'''
	qt_sql_rank_ob_notnull '''
		select kint, ksint rank() over(order by kint) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_1 '''
		select kint, ksint rank() over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_2 '''
		select kint, ksint rank() over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_3 '''
		select kint, ksint rank() over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_4 '''
		select kint, ksint rank() over(order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_5 '''
		select kint, ksint rank() over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_6 '''
		select kint, ksint rank() over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_7 '''
		select kint, ksint rank() over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_8 '''
		select kint, ksint rank() over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_9 '''
		select kint, ksint rank() over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_10 '''
		select kint, ksint rank() over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_11 '''
		select kint, ksint rank() over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_12 '''
		select kint, ksint rank() over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_13 '''
		select kint, ksint rank() over(order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_14 '''
		select kint, ksint rank() over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_15 '''
		select kint, ksint rank() over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_16 '''
		select kint, ksint rank() over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_17 '''
		select kint, ksint rank() over(order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_18 '''
		select kint, ksint rank() over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_19 '''
		select kint, ksint rank() over(order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_20 '''
		select kint, ksint rank() over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_21 '''
		select kint, ksint rank() over(order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_22 '''
		select kint, ksint rank() over(order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_23 '''
		select kint, ksint rank() over(order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_24 '''
		select kint, ksint rank() over(order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_25 '''
		select kint, ksint rank() over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_notnull_26 '''
		select kint, ksint rank() over(order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_pb '''
		select kint, ksint rank() over(partition by kstr) as wf from fn_test'''
	qt_sql_rank_pb_notnull '''
		select kint, ksint rank() over(partition by kstr) as wf from fn_test_not_nullable'''
	qt_sql_rank_pb_ob '''
		select kint, ksint rank() over(partition by kstr order by kint) as wf from fn_test'''
	qt_sql_rank_pb_ob_notnull '''
		select kint, ksint rank() over(partition by kstr order by kint) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_1 '''
		select kint, ksint rank() over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_2 '''
		select kint, ksint rank() over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_3 '''
		select kint, ksint rank() over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_4 '''
		select kint, ksint rank() over(partition by kstr order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_5 '''
		select kint, ksint rank() over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_6 '''
		select kint, ksint rank() over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_7 '''
		select kint, ksint rank() over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_8 '''
		select kint, ksint rank() over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_9 '''
		select kint, ksint rank() over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_10 '''
		select kint, ksint rank() over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_11 '''
		select kint, ksint rank() over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_12 '''
		select kint, ksint rank() over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_13 '''
		select kint, ksint rank() over(partition by kstr order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_14 '''
		select kint, ksint rank() over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_15 '''
		select kint, ksint rank() over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_16 '''
		select kint, ksint rank() over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_17 '''
		select kint, ksint rank() over(partition by kstr order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_18 '''
		select kint, ksint rank() over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_19 '''
		select kint, ksint rank() over(partition by kstr order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_20 '''
		select kint, ksint rank() over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_21 '''
		select kint, ksint rank() over(partition by kstr order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_22 '''
		select kint, ksint rank() over(partition by kstr order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_23 '''
		select kint, ksint rank() over(partition by kstr order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_24 '''
		select kint, ksint rank() over(partition by kstr order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_25 '''
		select kint, ksint rank() over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_rank_f_pb_notnull_26 '''
		select kint, ksint rank() over(partition by kstr order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''

	qt_sql_row_number '''
		select kint, ksint row_number() over() as wf from fn_test'''
	qt_sql_row_number_notnull '''
		select kint, ksint row_number() over() as wf from fn_test_not_nullable'''
	qt_sql_row_number_ob '''
		select kint, ksint row_number() over(order by kint) as wf from fn_test'''
	qt_sql_row_number_ob_notnull '''
		select kint, ksint row_number() over(order by kint) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_1 '''
		select kint, ksint row_number() over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_2 '''
		select kint, ksint row_number() over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_3 '''
		select kint, ksint row_number() over(order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_4 '''
		select kint, ksint row_number() over(order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_5 '''
		select kint, ksint row_number() over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_6 '''
		select kint, ksint row_number() over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_7 '''
		select kint, ksint row_number() over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_8 '''
		select kint, ksint row_number() over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_9 '''
		select kint, ksint row_number() over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_10 '''
		select kint, ksint row_number() over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_11 '''
		select kint, ksint row_number() over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_12 '''
		select kint, ksint row_number() over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_13 '''
		select kint, ksint row_number() over(order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_14 '''
		select kint, ksint row_number() over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_15 '''
		select kint, ksint row_number() over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_16 '''
		select kint, ksint row_number() over(order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_17 '''
		select kint, ksint row_number() over(order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_18 '''
		select kint, ksint row_number() over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_19 '''
		select kint, ksint row_number() over(order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_20 '''
		select kint, ksint row_number() over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_21 '''
		select kint, ksint row_number() over(order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_22 '''
		select kint, ksint row_number() over(order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_23 '''
		select kint, ksint row_number() over(order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_24 '''
		select kint, ksint row_number() over(order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_25 '''
		select kint, ksint row_number() over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_notnull_26 '''
		select kint, ksint row_number() over(order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_pb '''
		select kint, ksint row_number() over(partition by kstr) as wf from fn_test'''
	qt_sql_row_number_pb_notnull '''
		select kint, ksint row_number() over(partition by kstr) as wf from fn_test_not_nullable'''
	qt_sql_row_number_pb_ob '''
		select kint, ksint row_number() over(partition by kstr order by kint) as wf from fn_test'''
	qt_sql_row_number_pb_ob_notnull '''
		select kint, ksint row_number() over(partition by kstr order by kint) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_1 '''
		select kint, ksint row_number() over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_2 '''
		select kint, ksint row_number() over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_3 '''
		select kint, ksint row_number() over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_4 '''
		select kint, ksint row_number() over(partition by kstr order by kint rows between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_5 '''
		select kint, ksint row_number() over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_6 '''
		select kint, ksint row_number() over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_7 '''
		select kint, ksint row_number() over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_8 '''
		select kint, ksint row_number() over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_9 '''
		select kint, ksint row_number() over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_10 '''
		select kint, ksint row_number() over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_11 '''
		select kint, ksint row_number() over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_12 '''
		select kint, ksint row_number() over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_13 '''
		select kint, ksint row_number() over(partition by kstr order by kint rows between 2 following and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_14 '''
		select kint, ksint row_number() over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_15 '''
		select kint, ksint row_number() over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_16 '''
		select kint, ksint row_number() over(partition by kstr order by kint range 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_17 '''
		select kint, ksint row_number() over(partition by kstr order by kint range between unbounded preceding and 2 preceding) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_18 '''
		select kint, ksint row_number() over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_19 '''
		select kint, ksint row_number() over(partition by kstr order by kint range between unbounded preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_20 '''
		select kint, ksint row_number() over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_21 '''
		select kint, ksint row_number() over(partition by kstr order by kint range between 2 preceding and current row) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_22 '''
		select kint, ksint row_number() over(partition by kstr order by kint range between 2 preceding and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_23 '''
		select kint, ksint row_number() over(partition by kstr order by kint range between 2 preceding and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_24 '''
		select kint, ksint row_number() over(partition by kstr order by kint range between current row and 2 following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_25 '''
		select kint, ksint row_number() over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable'''
	qt_sql_row_number_f_pb_notnull_26 '''
		select kint, ksint row_number() over(partition by kstr order by kint range between 2 following and unbounded following) as wf from fn_test_not_nullable'''

}