# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

FROM ubuntu:trusty

RUN apt-get install mysql-client curl tar -y

COPY apache-doris-be-1.1.2-bin-x86_64.tar.gz /opt/apache-doris-be-1.1.2-bin-x86_64.tar.gz
RUN tar zxvf /opt/apache-doris-be-1.1.2-bin-x86_64.tar.gz -C /opt/
RUN rm -rf  /opt/doris/apache-doris-be-1.1.2-bin-x86_64.tar.gz
RUN  ln -s /opt/apache-doris-be-1.1.2-bin-x86_64 /opt/doris

EXPOSE 9060
EXPOSE 8040
EXPOSE 9050
EXPOSE 8060

COPY  register_be.sh /opt/register_be.sh
COPY  decommision_be.sh /opt/decommision_be.sh
RUN chmod  +x /opt/register_be.sh
RUN chmod  +x /opt/decommision_be.sh

CMD /opt/doris/be/bin/start_be.sh