# Data source configuration
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # Master Data source configuration
            master:
                url: jdbc:mysql://10.220.146.10:9030/test_2
                username: root
                password:
            # Number of initial connections
            initialSize: 5
            # Minimum number of connection pools
            minIdle: 10
            # Maximum number of connection pools
            maxActive: 20
            # Configure the timeout period to wait for the connection to be acquired
            maxWait: 60000
            # Configure how long the interval is to perform a check, check idle connections that need to be closed, the unit is milliseconds
            timeBetweenEvictionRunsMillis: 60000
            # Configure the minimum survival time of a connection in the pool, in milliseconds
            minEvictableIdleTimeMillis: 300000
            # Configure the maximum survival time of a connection in the pool, in milliseconds
            maxEvictableIdleTimeMillis: 900000
            # Configure to detect whether the connection is valid
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # Set a whitelist, leave it blank to allow all access
                allow:
                url-pattern: /druid/*
                #Console management user name and password
                login-username: admin
                login-password: admin
            filter:
                stat:
                    enabled: true
                    # Slow SQL records
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
