name: "dbt_testing_example"
version: "1.0.0"
config-version: 2

profile: "dbt_testing_example"

#require-dbt-version: ">=1.7.0"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_testing_example:
    +materialized: table
#  elementary:
#    +schema: "elementary"
