// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

suite('nereids_arith_p0') {
	qt_sql_test_1 """
		select id, kbool + kbool, kbool - kbool, kbool * kbool, kbool / kbool, kbool DIV kbool, kbool % kbool, kbool & kbool, kbool | kbool, kbool ^ kbool from expr_test order by id"""
	qt_sql_test_2_notn """
		select id, kbool + kbool, kbool - kbool, kbool * kbool, kbool / kbool, kbool DIV kbool, kbool % kbool, kbool & kbool, kbool | kbool, kbool ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_3 """
		select id, kbool + ktint, kbool - ktint, kbool * ktint, kbool / ktint, kbool DIV ktint, kbool % ktint, kbool & ktint, kbool | ktint, kbool ^ ktint from expr_test order by id"""
	qt_sql_test_4_notn """
		select id, kbool + ktint, kbool - ktint, kbool * ktint, kbool / ktint, kbool DIV ktint, kbool % ktint, kbool & ktint, kbool | ktint, kbool ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_5 """
		select id, kbool + ksint, kbool - ksint, kbool * ksint, kbool / ksint, kbool DIV ksint, kbool % ksint, kbool & ksint, kbool | ksint, kbool ^ ksint from expr_test order by id"""
	qt_sql_test_6_notn """
		select id, kbool + ksint, kbool - ksint, kbool * ksint, kbool / ksint, kbool DIV ksint, kbool % ksint, kbool & ksint, kbool | ksint, kbool ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_7 """
		select id, kbool + kint, kbool - kint, kbool * kint, kbool / kint, kbool DIV kint, kbool % kint, kbool & kint, kbool | kint, kbool ^ kint from expr_test order by id"""
	qt_sql_test_8_notn """
		select id, kbool + kint, kbool - kint, kbool * kint, kbool / kint, kbool DIV kint, kbool % kint, kbool & kint, kbool | kint, kbool ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_9 """
		select id, kbool + kbint, kbool - kbint, kbool * kbint, kbool / kbint, kbool DIV kbint, kbool % kbint, kbool & kbint, kbool | kbint, kbool ^ kbint from expr_test order by id"""
	qt_sql_test_10_notn """
		select id, kbool + kbint, kbool - kbint, kbool * kbint, kbool / kbint, kbool DIV kbint, kbool % kbint, kbool & kbint, kbool | kbint, kbool ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_11 """
		select id, kbool + klint, kbool - klint, kbool * klint, kbool / klint, kbool DIV klint, kbool % klint, kbool & klint, kbool | klint, kbool ^ klint from expr_test order by id"""
	qt_sql_test_12_notn """
		select id, kbool + klint, kbool - klint, kbool * klint, kbool / klint, kbool DIV klint, kbool % klint, kbool & klint, kbool | klint, kbool ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_13 """
		select id, kbool + kfloat, kbool - kfloat, kbool * kfloat, kbool / kfloat, kbool DIV kfloat, kbool % kfloat, kbool & kfloat, kbool | kfloat, kbool ^ kfloat from expr_test order by id"""
	qt_sql_test_14_notn """
		select id, kbool + kfloat, kbool - kfloat, kbool * kfloat, kbool / kfloat, kbool DIV kfloat, kbool % kfloat, kbool & kfloat, kbool | kfloat, kbool ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_15 """
		select id, kbool + kdbl, kbool - kdbl, kbool * kdbl, kbool / kdbl, kbool DIV kdbl, kbool % kdbl, kbool & kdbl, kbool | kdbl, kbool ^ kdbl from expr_test order by id"""
	qt_sql_test_16_notn """
		select id, kbool + kdbl, kbool - kdbl, kbool * kdbl, kbool / kdbl, kbool DIV kdbl, kbool % kdbl, kbool & kdbl, kbool | kdbl, kbool ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_17 """
		select id, kbool + kchr, kbool - kchr, kbool * kchr, kbool / kchr, kbool DIV kchr, kbool % kchr, kbool & kchr, kbool | kchr, kbool ^ kchr from expr_test order by id"""
	qt_sql_test_18_notn """
		select id, kbool + kchr, kbool - kchr, kbool * kchr, kbool / kchr, kbool DIV kchr, kbool % kchr, kbool & kchr, kbool | kchr, kbool ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_19 """
		select id, kbool + kvchr, kbool - kvchr, kbool * kvchr, kbool / kvchr, kbool DIV kvchr, kbool % kvchr, kbool & kvchr, kbool | kvchr, kbool ^ kvchr from expr_test order by id"""
	qt_sql_test_20_notn """
		select id, kbool + kvchr, kbool - kvchr, kbool * kvchr, kbool / kvchr, kbool DIV kvchr, kbool % kvchr, kbool & kvchr, kbool | kvchr, kbool ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_21 """
		select id, kbool + kstr, kbool - kstr, kbool * kstr, kbool / kstr, kbool DIV kstr, kbool % kstr, kbool & kstr, kbool | kstr, kbool ^ kstr from expr_test order by id"""
	qt_sql_test_22_notn """
		select id, kbool + kstr, kbool - kstr, kbool * kstr, kbool / kstr, kbool DIV kstr, kbool % kstr, kbool & kstr, kbool | kstr, kbool ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_23 """
		select id, kbool + kdt, kbool - kdt, kbool * kdt, kbool / kdt, kbool DIV kdt, kbool % kdt, kbool & kdt, kbool | kdt, kbool ^ kdt from expr_test order by id"""
	qt_sql_test_24_notn """
		select id, kbool + kdt, kbool - kdt, kbool * kdt, kbool / kdt, kbool DIV kdt, kbool % kdt, kbool & kdt, kbool | kdt, kbool ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_25 """
		select id, kbool + kdtm, kbool - kdtm, kbool * kdtm, kbool / kdtm, kbool DIV kdtm, kbool % kdtm, kbool & kdtm, kbool | kdtm, kbool ^ kdtm from expr_test order by id"""
	qt_sql_test_26_notn """
		select id, kbool + kdtm, kbool - kdtm, kbool * kdtm, kbool / kdtm, kbool DIV kdtm, kbool % kdtm, kbool & kdtm, kbool | kdtm, kbool ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_27 """
		select id, kbool + kdtv2, kbool - kdtv2, kbool * kdtv2, kbool / kdtv2, kbool DIV kdtv2, kbool % kdtv2, kbool & kdtv2, kbool | kdtv2, kbool ^ kdtv2 from expr_test order by id"""
	qt_sql_test_28_notn """
		select id, kbool + kdtv2, kbool - kdtv2, kbool * kdtv2, kbool / kdtv2, kbool DIV kdtv2, kbool % kdtv2, kbool & kdtv2, kbool | kdtv2, kbool ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_29 """
		select id, kbool + kdtmv2, kbool - kdtmv2, kbool * kdtmv2, kbool / kdtmv2, kbool DIV kdtmv2, kbool % kdtmv2, kbool & kdtmv2, kbool | kdtmv2, kbool ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_30_notn """
		select id, kbool + kdtmv2, kbool - kdtmv2, kbool * kdtmv2, kbool / kdtmv2, kbool DIV kdtmv2, kbool % kdtmv2, kbool & kdtmv2, kbool | kdtmv2, kbool ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_31 """
		select id, ktint + kbool, ktint - kbool, ktint * kbool, ktint / kbool, ktint DIV kbool, ktint % kbool, ktint & kbool, ktint | kbool, ktint ^ kbool from expr_test order by id"""
	qt_sql_test_32_notn """
		select id, ktint + kbool, ktint - kbool, ktint * kbool, ktint / kbool, ktint DIV kbool, ktint % kbool, ktint & kbool, ktint | kbool, ktint ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_33 """
		select id, ktint + ktint, ktint - ktint, ktint * ktint, ktint / ktint, ktint DIV ktint, ktint % ktint, ktint & ktint, ktint | ktint, ktint ^ ktint from expr_test order by id"""
	qt_sql_test_34_notn """
		select id, ktint + ktint, ktint - ktint, ktint * ktint, ktint / ktint, ktint DIV ktint, ktint % ktint, ktint & ktint, ktint | ktint, ktint ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_35 """
		select id, ktint + ksint, ktint - ksint, ktint * ksint, ktint / ksint, ktint DIV ksint, ktint % ksint, ktint & ksint, ktint | ksint, ktint ^ ksint from expr_test order by id"""
	qt_sql_test_36_notn """
		select id, ktint + ksint, ktint - ksint, ktint * ksint, ktint / ksint, ktint DIV ksint, ktint % ksint, ktint & ksint, ktint | ksint, ktint ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_37 """
		select id, ktint + kint, ktint - kint, ktint * kint, ktint / kint, ktint DIV kint, ktint % kint, ktint & kint, ktint | kint, ktint ^ kint from expr_test order by id"""
	qt_sql_test_38_notn """
		select id, ktint + kint, ktint - kint, ktint * kint, ktint / kint, ktint DIV kint, ktint % kint, ktint & kint, ktint | kint, ktint ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_39 """
		select id, ktint + kbint, ktint - kbint, ktint * kbint, ktint / kbint, ktint DIV kbint, ktint % kbint, ktint & kbint, ktint | kbint, ktint ^ kbint from expr_test order by id"""
	qt_sql_test_40_notn """
		select id, ktint + kbint, ktint - kbint, ktint * kbint, ktint / kbint, ktint DIV kbint, ktint % kbint, ktint & kbint, ktint | kbint, ktint ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_41 """
		select id, ktint + klint, ktint - klint, ktint * klint, ktint / klint, ktint DIV klint, ktint % klint, ktint & klint, ktint | klint, ktint ^ klint from expr_test order by id"""
	qt_sql_test_42_notn """
		select id, ktint + klint, ktint - klint, ktint * klint, ktint / klint, ktint DIV klint, ktint % klint, ktint & klint, ktint | klint, ktint ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_43 """
		select id, ktint + kfloat, ktint - kfloat, ktint * kfloat, ktint / kfloat, ktint DIV kfloat, ktint % kfloat, ktint & kfloat, ktint | kfloat, ktint ^ kfloat from expr_test order by id"""
	qt_sql_test_44_notn """
		select id, ktint + kfloat, ktint - kfloat, ktint * kfloat, ktint / kfloat, ktint DIV kfloat, ktint % kfloat, ktint & kfloat, ktint | kfloat, ktint ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_45 """
		select id, ktint + kdbl, ktint - kdbl, ktint * kdbl, ktint / kdbl, ktint DIV kdbl, ktint % kdbl, ktint & kdbl, ktint | kdbl, ktint ^ kdbl from expr_test order by id"""
	qt_sql_test_46_notn """
		select id, ktint + kdbl, ktint - kdbl, ktint * kdbl, ktint / kdbl, ktint DIV kdbl, ktint % kdbl, ktint & kdbl, ktint | kdbl, ktint ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_47 """
		select id, ktint + kchr, ktint - kchr, ktint * kchr, ktint / kchr, ktint DIV kchr, ktint % kchr, ktint & kchr, ktint | kchr, ktint ^ kchr from expr_test order by id"""
	qt_sql_test_48_notn """
		select id, ktint + kchr, ktint - kchr, ktint * kchr, ktint / kchr, ktint DIV kchr, ktint % kchr, ktint & kchr, ktint | kchr, ktint ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_49 """
		select id, ktint + kvchr, ktint - kvchr, ktint * kvchr, ktint / kvchr, ktint DIV kvchr, ktint % kvchr, ktint & kvchr, ktint | kvchr, ktint ^ kvchr from expr_test order by id"""
	qt_sql_test_50_notn """
		select id, ktint + kvchr, ktint - kvchr, ktint * kvchr, ktint / kvchr, ktint DIV kvchr, ktint % kvchr, ktint & kvchr, ktint | kvchr, ktint ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_51 """
		select id, ktint + kstr, ktint - kstr, ktint * kstr, ktint / kstr, ktint DIV kstr, ktint % kstr, ktint & kstr, ktint | kstr, ktint ^ kstr from expr_test order by id"""
	qt_sql_test_52_notn """
		select id, ktint + kstr, ktint - kstr, ktint * kstr, ktint / kstr, ktint DIV kstr, ktint % kstr, ktint & kstr, ktint | kstr, ktint ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_53 """
		select id, ktint + kdt, ktint - kdt, ktint * kdt, ktint / kdt, ktint DIV kdt, ktint % kdt, ktint & kdt, ktint | kdt, ktint ^ kdt from expr_test order by id"""
	qt_sql_test_54_notn """
		select id, ktint + kdt, ktint - kdt, ktint * kdt, ktint / kdt, ktint DIV kdt, ktint % kdt, ktint & kdt, ktint | kdt, ktint ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_55 """
		select id, ktint + kdtm, ktint - kdtm, ktint * kdtm, ktint / kdtm, ktint DIV kdtm, ktint % kdtm, ktint & kdtm, ktint | kdtm, ktint ^ kdtm from expr_test order by id"""
	qt_sql_test_56_notn """
		select id, ktint + kdtm, ktint - kdtm, ktint * kdtm, ktint / kdtm, ktint DIV kdtm, ktint % kdtm, ktint & kdtm, ktint | kdtm, ktint ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_57 """
		select id, ktint + kdtv2, ktint - kdtv2, ktint * kdtv2, ktint / kdtv2, ktint DIV kdtv2, ktint % kdtv2, ktint & kdtv2, ktint | kdtv2, ktint ^ kdtv2 from expr_test order by id"""
	qt_sql_test_58_notn """
		select id, ktint + kdtv2, ktint - kdtv2, ktint * kdtv2, ktint / kdtv2, ktint DIV kdtv2, ktint % kdtv2, ktint & kdtv2, ktint | kdtv2, ktint ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_59 """
		select id, ktint + kdtmv2, ktint - kdtmv2, ktint * kdtmv2, ktint / kdtmv2, ktint DIV kdtmv2, ktint % kdtmv2, ktint & kdtmv2, ktint | kdtmv2, ktint ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_60_notn """
		select id, ktint + kdtmv2, ktint - kdtmv2, ktint * kdtmv2, ktint / kdtmv2, ktint DIV kdtmv2, ktint % kdtmv2, ktint & kdtmv2, ktint | kdtmv2, ktint ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_61 """
		select id, ksint + kbool, ksint - kbool, ksint * kbool, ksint / kbool, ksint DIV kbool, ksint % kbool, ksint & kbool, ksint | kbool, ksint ^ kbool from expr_test order by id"""
	qt_sql_test_62_notn """
		select id, ksint + kbool, ksint - kbool, ksint * kbool, ksint / kbool, ksint DIV kbool, ksint % kbool, ksint & kbool, ksint | kbool, ksint ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_63 """
		select id, ksint + ktint, ksint - ktint, ksint * ktint, ksint / ktint, ksint DIV ktint, ksint % ktint, ksint & ktint, ksint | ktint, ksint ^ ktint from expr_test order by id"""
	qt_sql_test_64_notn """
		select id, ksint + ktint, ksint - ktint, ksint * ktint, ksint / ktint, ksint DIV ktint, ksint % ktint, ksint & ktint, ksint | ktint, ksint ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_65 """
		select id, ksint + ksint, ksint - ksint, ksint * ksint, ksint / ksint, ksint DIV ksint, ksint % ksint, ksint & ksint, ksint | ksint, ksint ^ ksint from expr_test order by id"""
	qt_sql_test_66_notn """
		select id, ksint + ksint, ksint - ksint, ksint * ksint, ksint / ksint, ksint DIV ksint, ksint % ksint, ksint & ksint, ksint | ksint, ksint ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_67 """
		select id, ksint + kint, ksint - kint, ksint * kint, ksint / kint, ksint DIV kint, ksint % kint, ksint & kint, ksint | kint, ksint ^ kint from expr_test order by id"""
	qt_sql_test_68_notn """
		select id, ksint + kint, ksint - kint, ksint * kint, ksint / kint, ksint DIV kint, ksint % kint, ksint & kint, ksint | kint, ksint ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_69 """
		select id, ksint + kbint, ksint - kbint, ksint * kbint, ksint / kbint, ksint DIV kbint, ksint % kbint, ksint & kbint, ksint | kbint, ksint ^ kbint from expr_test order by id"""
	qt_sql_test_70_notn """
		select id, ksint + kbint, ksint - kbint, ksint * kbint, ksint / kbint, ksint DIV kbint, ksint % kbint, ksint & kbint, ksint | kbint, ksint ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_71 """
		select id, ksint + klint, ksint - klint, ksint * klint, ksint / klint, ksint DIV klint, ksint % klint, ksint & klint, ksint | klint, ksint ^ klint from expr_test order by id"""
	qt_sql_test_72_notn """
		select id, ksint + klint, ksint - klint, ksint * klint, ksint / klint, ksint DIV klint, ksint % klint, ksint & klint, ksint | klint, ksint ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_73 """
		select id, ksint + kfloat, ksint - kfloat, ksint * kfloat, ksint / kfloat, ksint DIV kfloat, ksint % kfloat, ksint & kfloat, ksint | kfloat, ksint ^ kfloat from expr_test order by id"""
	qt_sql_test_74_notn """
		select id, ksint + kfloat, ksint - kfloat, ksint * kfloat, ksint / kfloat, ksint DIV kfloat, ksint % kfloat, ksint & kfloat, ksint | kfloat, ksint ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_75 """
		select id, ksint + kdbl, ksint - kdbl, ksint * kdbl, ksint / kdbl, ksint DIV kdbl, ksint % kdbl, ksint & kdbl, ksint | kdbl, ksint ^ kdbl from expr_test order by id"""
	qt_sql_test_76_notn """
		select id, ksint + kdbl, ksint - kdbl, ksint * kdbl, ksint / kdbl, ksint DIV kdbl, ksint % kdbl, ksint & kdbl, ksint | kdbl, ksint ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_77 """
		select id, ksint + kchr, ksint - kchr, ksint * kchr, ksint / kchr, ksint DIV kchr, ksint % kchr, ksint & kchr, ksint | kchr, ksint ^ kchr from expr_test order by id"""
	qt_sql_test_78_notn """
		select id, ksint + kchr, ksint - kchr, ksint * kchr, ksint / kchr, ksint DIV kchr, ksint % kchr, ksint & kchr, ksint | kchr, ksint ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_79 """
		select id, ksint + kvchr, ksint - kvchr, ksint * kvchr, ksint / kvchr, ksint DIV kvchr, ksint % kvchr, ksint & kvchr, ksint | kvchr, ksint ^ kvchr from expr_test order by id"""
	qt_sql_test_80_notn """
		select id, ksint + kvchr, ksint - kvchr, ksint * kvchr, ksint / kvchr, ksint DIV kvchr, ksint % kvchr, ksint & kvchr, ksint | kvchr, ksint ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_81 """
		select id, ksint + kstr, ksint - kstr, ksint * kstr, ksint / kstr, ksint DIV kstr, ksint % kstr, ksint & kstr, ksint | kstr, ksint ^ kstr from expr_test order by id"""
	qt_sql_test_82_notn """
		select id, ksint + kstr, ksint - kstr, ksint * kstr, ksint / kstr, ksint DIV kstr, ksint % kstr, ksint & kstr, ksint | kstr, ksint ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_83 """
		select id, ksint + kdt, ksint - kdt, ksint * kdt, ksint / kdt, ksint DIV kdt, ksint % kdt, ksint & kdt, ksint | kdt, ksint ^ kdt from expr_test order by id"""
	qt_sql_test_84_notn """
		select id, ksint + kdt, ksint - kdt, ksint * kdt, ksint / kdt, ksint DIV kdt, ksint % kdt, ksint & kdt, ksint | kdt, ksint ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_85 """
		select id, ksint + kdtm, ksint - kdtm, ksint * kdtm, ksint / kdtm, ksint DIV kdtm, ksint % kdtm, ksint & kdtm, ksint | kdtm, ksint ^ kdtm from expr_test order by id"""
	qt_sql_test_86_notn """
		select id, ksint + kdtm, ksint - kdtm, ksint * kdtm, ksint / kdtm, ksint DIV kdtm, ksint % kdtm, ksint & kdtm, ksint | kdtm, ksint ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_87 """
		select id, ksint + kdtv2, ksint - kdtv2, ksint * kdtv2, ksint / kdtv2, ksint DIV kdtv2, ksint % kdtv2, ksint & kdtv2, ksint | kdtv2, ksint ^ kdtv2 from expr_test order by id"""
	qt_sql_test_88_notn """
		select id, ksint + kdtv2, ksint - kdtv2, ksint * kdtv2, ksint / kdtv2, ksint DIV kdtv2, ksint % kdtv2, ksint & kdtv2, ksint | kdtv2, ksint ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_89 """
		select id, ksint + kdtmv2, ksint - kdtmv2, ksint * kdtmv2, ksint / kdtmv2, ksint DIV kdtmv2, ksint % kdtmv2, ksint & kdtmv2, ksint | kdtmv2, ksint ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_90_notn """
		select id, ksint + kdtmv2, ksint - kdtmv2, ksint * kdtmv2, ksint / kdtmv2, ksint DIV kdtmv2, ksint % kdtmv2, ksint & kdtmv2, ksint | kdtmv2, ksint ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_91 """
		select id, kint + kbool, kint - kbool, kint * kbool, kint / kbool, kint DIV kbool, kint % kbool, kint & kbool, kint | kbool, kint ^ kbool from expr_test order by id"""
	qt_sql_test_92_notn """
		select id, kint + kbool, kint - kbool, kint * kbool, kint / kbool, kint DIV kbool, kint % kbool, kint & kbool, kint | kbool, kint ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_93 """
		select id, kint + ktint, kint - ktint, kint * ktint, kint / ktint, kint DIV ktint, kint % ktint, kint & ktint, kint | ktint, kint ^ ktint from expr_test order by id"""
	qt_sql_test_94_notn """
		select id, kint + ktint, kint - ktint, kint * ktint, kint / ktint, kint DIV ktint, kint % ktint, kint & ktint, kint | ktint, kint ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_95 """
		select id, kint + ksint, kint - ksint, kint * ksint, kint / ksint, kint DIV ksint, kint % ksint, kint & ksint, kint | ksint, kint ^ ksint from expr_test order by id"""
	qt_sql_test_96_notn """
		select id, kint + ksint, kint - ksint, kint * ksint, kint / ksint, kint DIV ksint, kint % ksint, kint & ksint, kint | ksint, kint ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_97 """
		select id, kint + kint, kint - kint, kint * kint, kint / kint, kint DIV kint, kint % kint, kint & kint, kint | kint, kint ^ kint from expr_test order by id"""
	qt_sql_test_98_notn """
		select id, kint + kint, kint - kint, kint * kint, kint / kint, kint DIV kint, kint % kint, kint & kint, kint | kint, kint ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_99 """
		select id, kint + kbint, kint - kbint, kint * kbint, kint / kbint, kint DIV kbint, kint % kbint, kint & kbint, kint | kbint, kint ^ kbint from expr_test order by id"""
	qt_sql_test_100_notn """
		select id, kint + kbint, kint - kbint, kint * kbint, kint / kbint, kint DIV kbint, kint % kbint, kint & kbint, kint | kbint, kint ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_101 """
		select id, kint + klint, kint - klint, kint * klint, kint / klint, kint DIV klint, kint % klint, kint & klint, kint | klint, kint ^ klint from expr_test order by id"""
	qt_sql_test_102_notn """
		select id, kint + klint, kint - klint, kint * klint, kint / klint, kint DIV klint, kint % klint, kint & klint, kint | klint, kint ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_103 """
		select id, kint + kfloat, kint - kfloat, kint * kfloat, kint / kfloat, kint DIV kfloat, kint % kfloat, kint & kfloat, kint | kfloat, kint ^ kfloat from expr_test order by id"""
	qt_sql_test_104_notn """
		select id, kint + kfloat, kint - kfloat, kint * kfloat, kint / kfloat, kint DIV kfloat, kint % kfloat, kint & kfloat, kint | kfloat, kint ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_105 """
		select id, kint + kdbl, kint - kdbl, kint * kdbl, kint / kdbl, kint DIV kdbl, kint % kdbl, kint & kdbl, kint | kdbl, kint ^ kdbl from expr_test order by id"""
	qt_sql_test_106_notn """
		select id, kint + kdbl, kint - kdbl, kint * kdbl, kint / kdbl, kint DIV kdbl, kint % kdbl, kint & kdbl, kint | kdbl, kint ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_107 """
		select id, kint + kchr, kint - kchr, kint * kchr, kint / kchr, kint DIV kchr, kint % kchr, kint & kchr, kint | kchr, kint ^ kchr from expr_test order by id"""
	qt_sql_test_108_notn """
		select id, kint + kchr, kint - kchr, kint * kchr, kint / kchr, kint DIV kchr, kint % kchr, kint & kchr, kint | kchr, kint ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_109 """
		select id, kint + kvchr, kint - kvchr, kint * kvchr, kint / kvchr, kint DIV kvchr, kint % kvchr, kint & kvchr, kint | kvchr, kint ^ kvchr from expr_test order by id"""
	qt_sql_test_110_notn """
		select id, kint + kvchr, kint - kvchr, kint * kvchr, kint / kvchr, kint DIV kvchr, kint % kvchr, kint & kvchr, kint | kvchr, kint ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_111 """
		select id, kint + kstr, kint - kstr, kint * kstr, kint / kstr, kint DIV kstr, kint % kstr, kint & kstr, kint | kstr, kint ^ kstr from expr_test order by id"""
	qt_sql_test_112_notn """
		select id, kint + kstr, kint - kstr, kint * kstr, kint / kstr, kint DIV kstr, kint % kstr, kint & kstr, kint | kstr, kint ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_113 """
		select id, kint + kdt, kint - kdt, kint * kdt, kint / kdt, kint DIV kdt, kint % kdt, kint & kdt, kint | kdt, kint ^ kdt from expr_test order by id"""
	qt_sql_test_114_notn """
		select id, kint + kdt, kint - kdt, kint * kdt, kint / kdt, kint DIV kdt, kint % kdt, kint & kdt, kint | kdt, kint ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_115 """
		select id, kint + kdtm, kint - kdtm, kint * kdtm, kint / kdtm, kint DIV kdtm, kint % kdtm, kint & kdtm, kint | kdtm, kint ^ kdtm from expr_test order by id"""
	qt_sql_test_116_notn """
		select id, kint + kdtm, kint - kdtm, kint * kdtm, kint / kdtm, kint DIV kdtm, kint % kdtm, kint & kdtm, kint | kdtm, kint ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_117 """
		select id, kint + kdtv2, kint - kdtv2, kint * kdtv2, kint / kdtv2, kint DIV kdtv2, kint % kdtv2, kint & kdtv2, kint | kdtv2, kint ^ kdtv2 from expr_test order by id"""
	qt_sql_test_118_notn """
		select id, kint + kdtv2, kint - kdtv2, kint * kdtv2, kint / kdtv2, kint DIV kdtv2, kint % kdtv2, kint & kdtv2, kint | kdtv2, kint ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_119 """
		select id, kint + kdtmv2, kint - kdtmv2, kint * kdtmv2, kint / kdtmv2, kint DIV kdtmv2, kint % kdtmv2, kint & kdtmv2, kint | kdtmv2, kint ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_120_notn """
		select id, kint + kdtmv2, kint - kdtmv2, kint * kdtmv2, kint / kdtmv2, kint DIV kdtmv2, kint % kdtmv2, kint & kdtmv2, kint | kdtmv2, kint ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_121 """
		select id, kbint + kbool, kbint - kbool, kbint * kbool, kbint / kbool, kbint DIV kbool, kbint % kbool, kbint & kbool, kbint | kbool, kbint ^ kbool from expr_test order by id"""
	qt_sql_test_122_notn """
		select id, kbint + kbool, kbint - kbool, kbint * kbool, kbint / kbool, kbint DIV kbool, kbint % kbool, kbint & kbool, kbint | kbool, kbint ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_123 """
		select id, kbint + ktint, kbint - ktint, kbint * ktint, kbint / ktint, kbint DIV ktint, kbint % ktint, kbint & ktint, kbint | ktint, kbint ^ ktint from expr_test order by id"""
	qt_sql_test_124_notn """
		select id, kbint + ktint, kbint - ktint, kbint * ktint, kbint / ktint, kbint DIV ktint, kbint % ktint, kbint & ktint, kbint | ktint, kbint ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_125 """
		select id, kbint + ksint, kbint - ksint, kbint * ksint, kbint / ksint, kbint DIV ksint, kbint % ksint, kbint & ksint, kbint | ksint, kbint ^ ksint from expr_test order by id"""
	qt_sql_test_126_notn """
		select id, kbint + ksint, kbint - ksint, kbint * ksint, kbint / ksint, kbint DIV ksint, kbint % ksint, kbint & ksint, kbint | ksint, kbint ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_127 """
		select id, kbint + kint, kbint - kint, kbint * kint, kbint / kint, kbint DIV kint, kbint % kint, kbint & kint, kbint | kint, kbint ^ kint from expr_test order by id"""
	qt_sql_test_128_notn """
		select id, kbint + kint, kbint - kint, kbint * kint, kbint / kint, kbint DIV kint, kbint % kint, kbint & kint, kbint | kint, kbint ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_129 """
		select id, kbint + kbint, kbint - kbint, kbint * kbint, kbint / kbint, kbint DIV kbint, kbint % kbint, kbint & kbint, kbint | kbint, kbint ^ kbint from expr_test order by id"""
	qt_sql_test_130_notn """
		select id, kbint + kbint, kbint - kbint, kbint * kbint, kbint / kbint, kbint DIV kbint, kbint % kbint, kbint & kbint, kbint | kbint, kbint ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_131 """
		select id, kbint + klint, kbint - klint, kbint * klint, kbint / klint, kbint DIV klint, kbint % klint, kbint & klint, kbint | klint, kbint ^ klint from expr_test order by id"""
	qt_sql_test_132_notn """
		select id, kbint + klint, kbint - klint, kbint * klint, kbint / klint, kbint DIV klint, kbint % klint, kbint & klint, kbint | klint, kbint ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_133 """
		select id, kbint + kfloat, kbint - kfloat, kbint * kfloat, kbint / kfloat, kbint DIV kfloat, kbint % kfloat, kbint & kfloat, kbint | kfloat, kbint ^ kfloat from expr_test order by id"""
	qt_sql_test_134_notn """
		select id, kbint + kfloat, kbint - kfloat, kbint * kfloat, kbint / kfloat, kbint DIV kfloat, kbint % kfloat, kbint & kfloat, kbint | kfloat, kbint ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_135 """
		select id, kbint + kdbl, kbint - kdbl, kbint * kdbl, kbint / kdbl, kbint DIV kdbl, kbint % kdbl, kbint & kdbl, kbint | kdbl, kbint ^ kdbl from expr_test order by id"""
	qt_sql_test_136_notn """
		select id, kbint + kdbl, kbint - kdbl, kbint * kdbl, kbint / kdbl, kbint DIV kdbl, kbint % kdbl, kbint & kdbl, kbint | kdbl, kbint ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_137 """
		select id, kbint + kchr, kbint - kchr, kbint * kchr, kbint / kchr, kbint DIV kchr, kbint % kchr, kbint & kchr, kbint | kchr, kbint ^ kchr from expr_test order by id"""
	qt_sql_test_138_notn """
		select id, kbint + kchr, kbint - kchr, kbint * kchr, kbint / kchr, kbint DIV kchr, kbint % kchr, kbint & kchr, kbint | kchr, kbint ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_139 """
		select id, kbint + kvchr, kbint - kvchr, kbint * kvchr, kbint / kvchr, kbint DIV kvchr, kbint % kvchr, kbint & kvchr, kbint | kvchr, kbint ^ kvchr from expr_test order by id"""
	qt_sql_test_140_notn """
		select id, kbint + kvchr, kbint - kvchr, kbint * kvchr, kbint / kvchr, kbint DIV kvchr, kbint % kvchr, kbint & kvchr, kbint | kvchr, kbint ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_141 """
		select id, kbint + kstr, kbint - kstr, kbint * kstr, kbint / kstr, kbint DIV kstr, kbint % kstr, kbint & kstr, kbint | kstr, kbint ^ kstr from expr_test order by id"""
	qt_sql_test_142_notn """
		select id, kbint + kstr, kbint - kstr, kbint * kstr, kbint / kstr, kbint DIV kstr, kbint % kstr, kbint & kstr, kbint | kstr, kbint ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_143 """
		select id, kbint + kdt, kbint - kdt, kbint * kdt, kbint / kdt, kbint DIV kdt, kbint % kdt, kbint & kdt, kbint | kdt, kbint ^ kdt from expr_test order by id"""
	qt_sql_test_144_notn """
		select id, kbint + kdt, kbint - kdt, kbint * kdt, kbint / kdt, kbint DIV kdt, kbint % kdt, kbint & kdt, kbint | kdt, kbint ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_145 """
		select id, kbint + kdtm, kbint - kdtm, kbint * kdtm, kbint / kdtm, kbint DIV kdtm, kbint % kdtm, kbint & kdtm, kbint | kdtm, kbint ^ kdtm from expr_test order by id"""
	qt_sql_test_146_notn """
		select id, kbint + kdtm, kbint - kdtm, kbint * kdtm, kbint / kdtm, kbint DIV kdtm, kbint % kdtm, kbint & kdtm, kbint | kdtm, kbint ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_147 """
		select id, kbint + kdtv2, kbint - kdtv2, kbint * kdtv2, kbint / kdtv2, kbint DIV kdtv2, kbint % kdtv2, kbint & kdtv2, kbint | kdtv2, kbint ^ kdtv2 from expr_test order by id"""
	qt_sql_test_148_notn """
		select id, kbint + kdtv2, kbint - kdtv2, kbint * kdtv2, kbint / kdtv2, kbint DIV kdtv2, kbint % kdtv2, kbint & kdtv2, kbint | kdtv2, kbint ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_149 """
		select id, kbint + kdtmv2, kbint - kdtmv2, kbint * kdtmv2, kbint / kdtmv2, kbint DIV kdtmv2, kbint % kdtmv2, kbint & kdtmv2, kbint | kdtmv2, kbint ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_150_notn """
		select id, kbint + kdtmv2, kbint - kdtmv2, kbint * kdtmv2, kbint / kdtmv2, kbint DIV kdtmv2, kbint % kdtmv2, kbint & kdtmv2, kbint | kdtmv2, kbint ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_151 """
		select id, klint + kbool, klint - kbool, klint * kbool, klint / kbool, klint DIV kbool, klint % kbool, klint & kbool, klint | kbool, klint ^ kbool from expr_test order by id"""
	qt_sql_test_152_notn """
		select id, klint + kbool, klint - kbool, klint * kbool, klint / kbool, klint DIV kbool, klint % kbool, klint & kbool, klint | kbool, klint ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_153 """
		select id, klint + ktint, klint - ktint, klint * ktint, klint / ktint, klint DIV ktint, klint % ktint, klint & ktint, klint | ktint, klint ^ ktint from expr_test order by id"""
	qt_sql_test_154_notn """
		select id, klint + ktint, klint - ktint, klint * ktint, klint / ktint, klint DIV ktint, klint % ktint, klint & ktint, klint | ktint, klint ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_155 """
		select id, klint + ksint, klint - ksint, klint * ksint, klint / ksint, klint DIV ksint, klint % ksint, klint & ksint, klint | ksint, klint ^ ksint from expr_test order by id"""
	qt_sql_test_156_notn """
		select id, klint + ksint, klint - ksint, klint * ksint, klint / ksint, klint DIV ksint, klint % ksint, klint & ksint, klint | ksint, klint ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_157 """
		select id, klint + kint, klint - kint, klint * kint, klint / kint, klint DIV kint, klint % kint, klint & kint, klint | kint, klint ^ kint from expr_test order by id"""
	qt_sql_test_158_notn """
		select id, klint + kint, klint - kint, klint * kint, klint / kint, klint DIV kint, klint % kint, klint & kint, klint | kint, klint ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_159 """
		select id, klint + kbint, klint - kbint, klint * kbint, klint / kbint, klint DIV kbint, klint % kbint, klint & kbint, klint | kbint, klint ^ kbint from expr_test order by id"""
	qt_sql_test_160_notn """
		select id, klint + kbint, klint - kbint, klint * kbint, klint / kbint, klint DIV kbint, klint % kbint, klint & kbint, klint | kbint, klint ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_161 """
		select id, klint + klint, klint - klint, klint * klint, klint / klint, klint DIV klint, klint % klint, klint & klint, klint | klint, klint ^ klint from expr_test order by id"""
	qt_sql_test_162_notn """
		select id, klint + klint, klint - klint, klint * klint, klint / klint, klint DIV klint, klint % klint, klint & klint, klint | klint, klint ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_163 """
		select id, klint + kfloat, klint - kfloat, klint * kfloat, klint / kfloat, klint DIV kfloat, klint % kfloat, klint & kfloat, klint | kfloat, klint ^ kfloat from expr_test order by id"""
	qt_sql_test_164_notn """
		select id, klint + kfloat, klint - kfloat, klint * kfloat, klint / kfloat, klint DIV kfloat, klint % kfloat, klint & kfloat, klint | kfloat, klint ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_165 """
		select id, klint + kdbl, klint - kdbl, klint * kdbl, klint / kdbl, klint DIV kdbl, klint % kdbl, klint & kdbl, klint | kdbl, klint ^ kdbl from expr_test order by id"""
	qt_sql_test_166_notn """
		select id, klint + kdbl, klint - kdbl, klint * kdbl, klint / kdbl, klint DIV kdbl, klint % kdbl, klint & kdbl, klint | kdbl, klint ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_167 """
		select id, klint + kchr, klint - kchr, klint * kchr, klint / kchr, klint DIV kchr, klint % kchr, klint & kchr, klint | kchr, klint ^ kchr from expr_test order by id"""
	qt_sql_test_168_notn """
		select id, klint + kchr, klint - kchr, klint * kchr, klint / kchr, klint DIV kchr, klint % kchr, klint & kchr, klint | kchr, klint ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_169 """
		select id, klint + kvchr, klint - kvchr, klint * kvchr, klint / kvchr, klint DIV kvchr, klint % kvchr, klint & kvchr, klint | kvchr, klint ^ kvchr from expr_test order by id"""
	qt_sql_test_170_notn """
		select id, klint + kvchr, klint - kvchr, klint * kvchr, klint / kvchr, klint DIV kvchr, klint % kvchr, klint & kvchr, klint | kvchr, klint ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_171 """
		select id, klint + kstr, klint - kstr, klint * kstr, klint / kstr, klint DIV kstr, klint % kstr, klint & kstr, klint | kstr, klint ^ kstr from expr_test order by id"""
	qt_sql_test_172_notn """
		select id, klint + kstr, klint - kstr, klint * kstr, klint / kstr, klint DIV kstr, klint % kstr, klint & kstr, klint | kstr, klint ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_173 """
		select id, klint + kdt, klint - kdt, klint * kdt, klint / kdt, klint DIV kdt, klint % kdt, klint & kdt, klint | kdt, klint ^ kdt from expr_test order by id"""
	qt_sql_test_174_notn """
		select id, klint + kdt, klint - kdt, klint * kdt, klint / kdt, klint DIV kdt, klint % kdt, klint & kdt, klint | kdt, klint ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_175 """
		select id, klint + kdtm, klint - kdtm, klint * kdtm, klint / kdtm, klint DIV kdtm, klint % kdtm, klint & kdtm, klint | kdtm, klint ^ kdtm from expr_test order by id"""
	qt_sql_test_176_notn """
		select id, klint + kdtm, klint - kdtm, klint * kdtm, klint / kdtm, klint DIV kdtm, klint % kdtm, klint & kdtm, klint | kdtm, klint ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_177 """
		select id, klint + kdtv2, klint - kdtv2, klint * kdtv2, klint / kdtv2, klint DIV kdtv2, klint % kdtv2, klint & kdtv2, klint | kdtv2, klint ^ kdtv2 from expr_test order by id"""
	qt_sql_test_178_notn """
		select id, klint + kdtv2, klint - kdtv2, klint * kdtv2, klint / kdtv2, klint DIV kdtv2, klint % kdtv2, klint & kdtv2, klint | kdtv2, klint ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_179 """
		select id, klint + kdtmv2, klint - kdtmv2, klint * kdtmv2, klint / kdtmv2, klint DIV kdtmv2, klint % kdtmv2, klint & kdtmv2, klint | kdtmv2, klint ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_180_notn """
		select id, klint + kdtmv2, klint - kdtmv2, klint * kdtmv2, klint / kdtmv2, klint DIV kdtmv2, klint % kdtmv2, klint & kdtmv2, klint | kdtmv2, klint ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_181 """
		select id, kfloat + kbool, kfloat - kbool, kfloat * kbool, kfloat / kbool, kfloat DIV kbool, kfloat % kbool, kfloat & kbool, kfloat | kbool, kfloat ^ kbool from expr_test order by id"""
	qt_sql_test_182_notn """
		select id, kfloat + kbool, kfloat - kbool, kfloat * kbool, kfloat / kbool, kfloat DIV kbool, kfloat % kbool, kfloat & kbool, kfloat | kbool, kfloat ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_183 """
		select id, kfloat + ktint, kfloat - ktint, kfloat * ktint, kfloat / ktint, kfloat DIV ktint, kfloat % ktint, kfloat & ktint, kfloat | ktint, kfloat ^ ktint from expr_test order by id"""
	qt_sql_test_184_notn """
		select id, kfloat + ktint, kfloat - ktint, kfloat * ktint, kfloat / ktint, kfloat DIV ktint, kfloat % ktint, kfloat & ktint, kfloat | ktint, kfloat ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_185 """
		select id, kfloat + ksint, kfloat - ksint, kfloat * ksint, kfloat / ksint, kfloat DIV ksint, kfloat % ksint, kfloat & ksint, kfloat | ksint, kfloat ^ ksint from expr_test order by id"""
	qt_sql_test_186_notn """
		select id, kfloat + ksint, kfloat - ksint, kfloat * ksint, kfloat / ksint, kfloat DIV ksint, kfloat % ksint, kfloat & ksint, kfloat | ksint, kfloat ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_187 """
		select id, kfloat + kint, kfloat - kint, kfloat * kint, kfloat / kint, kfloat DIV kint, kfloat % kint, kfloat & kint, kfloat | kint, kfloat ^ kint from expr_test order by id"""
	qt_sql_test_188_notn """
		select id, kfloat + kint, kfloat - kint, kfloat * kint, kfloat / kint, kfloat DIV kint, kfloat % kint, kfloat & kint, kfloat | kint, kfloat ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_189 """
		select id, kfloat + kbint, kfloat - kbint, kfloat * kbint, kfloat / kbint, kfloat DIV kbint, kfloat % kbint, kfloat & kbint, kfloat | kbint, kfloat ^ kbint from expr_test order by id"""
	qt_sql_test_190_notn """
		select id, kfloat + kbint, kfloat - kbint, kfloat * kbint, kfloat / kbint, kfloat DIV kbint, kfloat % kbint, kfloat & kbint, kfloat | kbint, kfloat ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_191 """
		select id, kfloat + klint, kfloat - klint, kfloat * klint, kfloat / klint, kfloat DIV klint, kfloat % klint, kfloat & klint, kfloat | klint, kfloat ^ klint from expr_test order by id"""
	qt_sql_test_192_notn """
		select id, kfloat + klint, kfloat - klint, kfloat * klint, kfloat / klint, kfloat DIV klint, kfloat % klint, kfloat & klint, kfloat | klint, kfloat ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_193 """
		select id, kfloat + kfloat, kfloat - kfloat, kfloat * kfloat, kfloat / kfloat, kfloat DIV kfloat, kfloat % kfloat, kfloat & kfloat, kfloat | kfloat, kfloat ^ kfloat from expr_test order by id"""
	qt_sql_test_194_notn """
		select id, kfloat + kfloat, kfloat - kfloat, kfloat * kfloat, kfloat / kfloat, kfloat DIV kfloat, kfloat % kfloat, kfloat & kfloat, kfloat | kfloat, kfloat ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_195 """
		select id, kfloat + kdbl, kfloat - kdbl, kfloat * kdbl, kfloat / kdbl, kfloat DIV kdbl, kfloat % kdbl, kfloat & kdbl, kfloat | kdbl, kfloat ^ kdbl from expr_test order by id"""
	qt_sql_test_196_notn """
		select id, kfloat + kdbl, kfloat - kdbl, kfloat * kdbl, kfloat / kdbl, kfloat DIV kdbl, kfloat % kdbl, kfloat & kdbl, kfloat | kdbl, kfloat ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_197 """
		select id, kfloat + kchr, kfloat - kchr, kfloat * kchr, kfloat / kchr, kfloat DIV kchr, kfloat % kchr, kfloat & kchr, kfloat | kchr, kfloat ^ kchr from expr_test order by id"""
	qt_sql_test_198_notn """
		select id, kfloat + kchr, kfloat - kchr, kfloat * kchr, kfloat / kchr, kfloat DIV kchr, kfloat % kchr, kfloat & kchr, kfloat | kchr, kfloat ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_199 """
		select id, kfloat + kvchr, kfloat - kvchr, kfloat * kvchr, kfloat / kvchr, kfloat DIV kvchr, kfloat % kvchr, kfloat & kvchr, kfloat | kvchr, kfloat ^ kvchr from expr_test order by id"""
	qt_sql_test_200_notn """
		select id, kfloat + kvchr, kfloat - kvchr, kfloat * kvchr, kfloat / kvchr, kfloat DIV kvchr, kfloat % kvchr, kfloat & kvchr, kfloat | kvchr, kfloat ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_201 """
		select id, kfloat + kstr, kfloat - kstr, kfloat * kstr, kfloat / kstr, kfloat DIV kstr, kfloat % kstr, kfloat & kstr, kfloat | kstr, kfloat ^ kstr from expr_test order by id"""
	qt_sql_test_202_notn """
		select id, kfloat + kstr, kfloat - kstr, kfloat * kstr, kfloat / kstr, kfloat DIV kstr, kfloat % kstr, kfloat & kstr, kfloat | kstr, kfloat ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_203 """
		select id, kfloat + kdt, kfloat - kdt, kfloat * kdt, kfloat / kdt, kfloat DIV kdt, kfloat % kdt, kfloat & kdt, kfloat | kdt, kfloat ^ kdt from expr_test order by id"""
	qt_sql_test_204_notn """
		select id, kfloat + kdt, kfloat - kdt, kfloat * kdt, kfloat / kdt, kfloat DIV kdt, kfloat % kdt, kfloat & kdt, kfloat | kdt, kfloat ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_205 """
		select id, kfloat + kdtm, kfloat - kdtm, kfloat * kdtm, kfloat / kdtm, kfloat DIV kdtm, kfloat % kdtm, kfloat & kdtm, kfloat | kdtm, kfloat ^ kdtm from expr_test order by id"""
	qt_sql_test_206_notn """
		select id, kfloat + kdtm, kfloat - kdtm, kfloat * kdtm, kfloat / kdtm, kfloat DIV kdtm, kfloat % kdtm, kfloat & kdtm, kfloat | kdtm, kfloat ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_207 """
		select id, kfloat + kdtv2, kfloat - kdtv2, kfloat * kdtv2, kfloat / kdtv2, kfloat DIV kdtv2, kfloat % kdtv2, kfloat & kdtv2, kfloat | kdtv2, kfloat ^ kdtv2 from expr_test order by id"""
	qt_sql_test_208_notn """
		select id, kfloat + kdtv2, kfloat - kdtv2, kfloat * kdtv2, kfloat / kdtv2, kfloat DIV kdtv2, kfloat % kdtv2, kfloat & kdtv2, kfloat | kdtv2, kfloat ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_209 """
		select id, kfloat + kdtmv2, kfloat - kdtmv2, kfloat * kdtmv2, kfloat / kdtmv2, kfloat DIV kdtmv2, kfloat % kdtmv2, kfloat & kdtmv2, kfloat | kdtmv2, kfloat ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_210_notn """
		select id, kfloat + kdtmv2, kfloat - kdtmv2, kfloat * kdtmv2, kfloat / kdtmv2, kfloat DIV kdtmv2, kfloat % kdtmv2, kfloat & kdtmv2, kfloat | kdtmv2, kfloat ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_211 """
		select id, kdbl + kbool, kdbl - kbool, kdbl * kbool, kdbl / kbool, kdbl DIV kbool, kdbl % kbool, kdbl & kbool, kdbl | kbool, kdbl ^ kbool from expr_test order by id"""
	qt_sql_test_212_notn """
		select id, kdbl + kbool, kdbl - kbool, kdbl * kbool, kdbl / kbool, kdbl DIV kbool, kdbl % kbool, kdbl & kbool, kdbl | kbool, kdbl ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_213 """
		select id, kdbl + ktint, kdbl - ktint, kdbl * ktint, kdbl / ktint, kdbl DIV ktint, kdbl % ktint, kdbl & ktint, kdbl | ktint, kdbl ^ ktint from expr_test order by id"""
	qt_sql_test_214_notn """
		select id, kdbl + ktint, kdbl - ktint, kdbl * ktint, kdbl / ktint, kdbl DIV ktint, kdbl % ktint, kdbl & ktint, kdbl | ktint, kdbl ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_215 """
		select id, kdbl + ksint, kdbl - ksint, kdbl * ksint, kdbl / ksint, kdbl DIV ksint, kdbl % ksint, kdbl & ksint, kdbl | ksint, kdbl ^ ksint from expr_test order by id"""
	qt_sql_test_216_notn """
		select id, kdbl + ksint, kdbl - ksint, kdbl * ksint, kdbl / ksint, kdbl DIV ksint, kdbl % ksint, kdbl & ksint, kdbl | ksint, kdbl ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_217 """
		select id, kdbl + kint, kdbl - kint, kdbl * kint, kdbl / kint, kdbl DIV kint, kdbl % kint, kdbl & kint, kdbl | kint, kdbl ^ kint from expr_test order by id"""
	qt_sql_test_218_notn """
		select id, kdbl + kint, kdbl - kint, kdbl * kint, kdbl / kint, kdbl DIV kint, kdbl % kint, kdbl & kint, kdbl | kint, kdbl ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_219 """
		select id, kdbl + kbint, kdbl - kbint, kdbl * kbint, kdbl / kbint, kdbl DIV kbint, kdbl % kbint, kdbl & kbint, kdbl | kbint, kdbl ^ kbint from expr_test order by id"""
	qt_sql_test_220_notn """
		select id, kdbl + kbint, kdbl - kbint, kdbl * kbint, kdbl / kbint, kdbl DIV kbint, kdbl % kbint, kdbl & kbint, kdbl | kbint, kdbl ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_221 """
		select id, kdbl + klint, kdbl - klint, kdbl * klint, kdbl / klint, kdbl DIV klint, kdbl % klint, kdbl & klint, kdbl | klint, kdbl ^ klint from expr_test order by id"""
	qt_sql_test_222_notn """
		select id, kdbl + klint, kdbl - klint, kdbl * klint, kdbl / klint, kdbl DIV klint, kdbl % klint, kdbl & klint, kdbl | klint, kdbl ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_223 """
		select id, kdbl + kfloat, kdbl - kfloat, kdbl * kfloat, kdbl / kfloat, kdbl DIV kfloat, kdbl % kfloat, kdbl & kfloat, kdbl | kfloat, kdbl ^ kfloat from expr_test order by id"""
	qt_sql_test_224_notn """
		select id, kdbl + kfloat, kdbl - kfloat, kdbl * kfloat, kdbl / kfloat, kdbl DIV kfloat, kdbl % kfloat, kdbl & kfloat, kdbl | kfloat, kdbl ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_225 """
		select id, kdbl + kdbl, kdbl - kdbl, kdbl * kdbl, kdbl / kdbl, kdbl DIV kdbl, kdbl % kdbl, kdbl & kdbl, kdbl | kdbl, kdbl ^ kdbl from expr_test order by id"""
	qt_sql_test_226_notn """
		select id, kdbl + kdbl, kdbl - kdbl, kdbl * kdbl, kdbl / kdbl, kdbl DIV kdbl, kdbl % kdbl, kdbl & kdbl, kdbl | kdbl, kdbl ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_227 """
		select id, kdbl + kchr, kdbl - kchr, kdbl * kchr, kdbl / kchr, kdbl DIV kchr, kdbl % kchr, kdbl & kchr, kdbl | kchr, kdbl ^ kchr from expr_test order by id"""
	qt_sql_test_228_notn """
		select id, kdbl + kchr, kdbl - kchr, kdbl * kchr, kdbl / kchr, kdbl DIV kchr, kdbl % kchr, kdbl & kchr, kdbl | kchr, kdbl ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_229 """
		select id, kdbl + kvchr, kdbl - kvchr, kdbl * kvchr, kdbl / kvchr, kdbl DIV kvchr, kdbl % kvchr, kdbl & kvchr, kdbl | kvchr, kdbl ^ kvchr from expr_test order by id"""
	qt_sql_test_230_notn """
		select id, kdbl + kvchr, kdbl - kvchr, kdbl * kvchr, kdbl / kvchr, kdbl DIV kvchr, kdbl % kvchr, kdbl & kvchr, kdbl | kvchr, kdbl ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_231 """
		select id, kdbl + kstr, kdbl - kstr, kdbl * kstr, kdbl / kstr, kdbl DIV kstr, kdbl % kstr, kdbl & kstr, kdbl | kstr, kdbl ^ kstr from expr_test order by id"""
	qt_sql_test_232_notn """
		select id, kdbl + kstr, kdbl - kstr, kdbl * kstr, kdbl / kstr, kdbl DIV kstr, kdbl % kstr, kdbl & kstr, kdbl | kstr, kdbl ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_233 """
		select id, kdbl + kdt, kdbl - kdt, kdbl * kdt, kdbl / kdt, kdbl DIV kdt, kdbl % kdt, kdbl & kdt, kdbl | kdt, kdbl ^ kdt from expr_test order by id"""
	qt_sql_test_234_notn """
		select id, kdbl + kdt, kdbl - kdt, kdbl * kdt, kdbl / kdt, kdbl DIV kdt, kdbl % kdt, kdbl & kdt, kdbl | kdt, kdbl ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_235 """
		select id, kdbl + kdtm, kdbl - kdtm, kdbl * kdtm, kdbl / kdtm, kdbl DIV kdtm, kdbl % kdtm, kdbl & kdtm, kdbl | kdtm, kdbl ^ kdtm from expr_test order by id"""
	qt_sql_test_236_notn """
		select id, kdbl + kdtm, kdbl - kdtm, kdbl * kdtm, kdbl / kdtm, kdbl DIV kdtm, kdbl % kdtm, kdbl & kdtm, kdbl | kdtm, kdbl ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_237 """
		select id, kdbl + kdtv2, kdbl - kdtv2, kdbl * kdtv2, kdbl / kdtv2, kdbl DIV kdtv2, kdbl % kdtv2, kdbl & kdtv2, kdbl | kdtv2, kdbl ^ kdtv2 from expr_test order by id"""
	qt_sql_test_238_notn """
		select id, kdbl + kdtv2, kdbl - kdtv2, kdbl * kdtv2, kdbl / kdtv2, kdbl DIV kdtv2, kdbl % kdtv2, kdbl & kdtv2, kdbl | kdtv2, kdbl ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_239 """
		select id, kdbl + kdtmv2, kdbl - kdtmv2, kdbl * kdtmv2, kdbl / kdtmv2, kdbl DIV kdtmv2, kdbl % kdtmv2, kdbl & kdtmv2, kdbl | kdtmv2, kdbl ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_240_notn """
		select id, kdbl + kdtmv2, kdbl - kdtmv2, kdbl * kdtmv2, kdbl / kdtmv2, kdbl DIV kdtmv2, kdbl % kdtmv2, kdbl & kdtmv2, kdbl | kdtmv2, kdbl ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_241 """
		select id, kchr + kbool, kchr - kbool, kchr * kbool, kchr / kbool, kchr DIV kbool, kchr % kbool, kchr & kbool, kchr | kbool, kchr ^ kbool from expr_test order by id"""
	qt_sql_test_242_notn """
		select id, kchr + kbool, kchr - kbool, kchr * kbool, kchr / kbool, kchr DIV kbool, kchr % kbool, kchr & kbool, kchr | kbool, kchr ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_243 """
		select id, kchr + ktint, kchr - ktint, kchr * ktint, kchr / ktint, kchr DIV ktint, kchr % ktint, kchr & ktint, kchr | ktint, kchr ^ ktint from expr_test order by id"""
	qt_sql_test_244_notn """
		select id, kchr + ktint, kchr - ktint, kchr * ktint, kchr / ktint, kchr DIV ktint, kchr % ktint, kchr & ktint, kchr | ktint, kchr ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_245 """
		select id, kchr + ksint, kchr - ksint, kchr * ksint, kchr / ksint, kchr DIV ksint, kchr % ksint, kchr & ksint, kchr | ksint, kchr ^ ksint from expr_test order by id"""
	qt_sql_test_246_notn """
		select id, kchr + ksint, kchr - ksint, kchr * ksint, kchr / ksint, kchr DIV ksint, kchr % ksint, kchr & ksint, kchr | ksint, kchr ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_247 """
		select id, kchr + kint, kchr - kint, kchr * kint, kchr / kint, kchr DIV kint, kchr % kint, kchr & kint, kchr | kint, kchr ^ kint from expr_test order by id"""
	qt_sql_test_248_notn """
		select id, kchr + kint, kchr - kint, kchr * kint, kchr / kint, kchr DIV kint, kchr % kint, kchr & kint, kchr | kint, kchr ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_249 """
		select id, kchr + kbint, kchr - kbint, kchr * kbint, kchr / kbint, kchr DIV kbint, kchr % kbint, kchr & kbint, kchr | kbint, kchr ^ kbint from expr_test order by id"""
	qt_sql_test_250_notn """
		select id, kchr + kbint, kchr - kbint, kchr * kbint, kchr / kbint, kchr DIV kbint, kchr % kbint, kchr & kbint, kchr | kbint, kchr ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_251 """
		select id, kchr + klint, kchr - klint, kchr * klint, kchr / klint, kchr DIV klint, kchr % klint, kchr & klint, kchr | klint, kchr ^ klint from expr_test order by id"""
	qt_sql_test_252_notn """
		select id, kchr + klint, kchr - klint, kchr * klint, kchr / klint, kchr DIV klint, kchr % klint, kchr & klint, kchr | klint, kchr ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_253 """
		select id, kchr + kfloat, kchr - kfloat, kchr * kfloat, kchr / kfloat, kchr DIV kfloat, kchr % kfloat, kchr & kfloat, kchr | kfloat, kchr ^ kfloat from expr_test order by id"""
	qt_sql_test_254_notn """
		select id, kchr + kfloat, kchr - kfloat, kchr * kfloat, kchr / kfloat, kchr DIV kfloat, kchr % kfloat, kchr & kfloat, kchr | kfloat, kchr ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_255 """
		select id, kchr + kdbl, kchr - kdbl, kchr * kdbl, kchr / kdbl, kchr DIV kdbl, kchr % kdbl, kchr & kdbl, kchr | kdbl, kchr ^ kdbl from expr_test order by id"""
	qt_sql_test_256_notn """
		select id, kchr + kdbl, kchr - kdbl, kchr * kdbl, kchr / kdbl, kchr DIV kdbl, kchr % kdbl, kchr & kdbl, kchr | kdbl, kchr ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_257 """
		select id, kchr + kchr, kchr - kchr, kchr * kchr, kchr / kchr, kchr DIV kchr, kchr % kchr, kchr & kchr, kchr | kchr, kchr ^ kchr from expr_test order by id"""
	qt_sql_test_258_notn """
		select id, kchr + kchr, kchr - kchr, kchr * kchr, kchr / kchr, kchr DIV kchr, kchr % kchr, kchr & kchr, kchr | kchr, kchr ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_259 """
		select id, kchr + kvchr, kchr - kvchr, kchr * kvchr, kchr / kvchr, kchr DIV kvchr, kchr % kvchr, kchr & kvchr, kchr | kvchr, kchr ^ kvchr from expr_test order by id"""
	qt_sql_test_260_notn """
		select id, kchr + kvchr, kchr - kvchr, kchr * kvchr, kchr / kvchr, kchr DIV kvchr, kchr % kvchr, kchr & kvchr, kchr | kvchr, kchr ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_261 """
		select id, kchr + kstr, kchr - kstr, kchr * kstr, kchr / kstr, kchr DIV kstr, kchr % kstr, kchr & kstr, kchr | kstr, kchr ^ kstr from expr_test order by id"""
	qt_sql_test_262_notn """
		select id, kchr + kstr, kchr - kstr, kchr * kstr, kchr / kstr, kchr DIV kstr, kchr % kstr, kchr & kstr, kchr | kstr, kchr ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_263 """
		select id, kchr + kdt, kchr - kdt, kchr * kdt, kchr / kdt, kchr DIV kdt, kchr % kdt, kchr & kdt, kchr | kdt, kchr ^ kdt from expr_test order by id"""
	qt_sql_test_264_notn """
		select id, kchr + kdt, kchr - kdt, kchr * kdt, kchr / kdt, kchr DIV kdt, kchr % kdt, kchr & kdt, kchr | kdt, kchr ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_265 """
		select id, kchr + kdtm, kchr - kdtm, kchr * kdtm, kchr / kdtm, kchr DIV kdtm, kchr % kdtm, kchr & kdtm, kchr | kdtm, kchr ^ kdtm from expr_test order by id"""
	qt_sql_test_266_notn """
		select id, kchr + kdtm, kchr - kdtm, kchr * kdtm, kchr / kdtm, kchr DIV kdtm, kchr % kdtm, kchr & kdtm, kchr | kdtm, kchr ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_267 """
		select id, kchr + kdtv2, kchr - kdtv2, kchr * kdtv2, kchr / kdtv2, kchr DIV kdtv2, kchr % kdtv2, kchr & kdtv2, kchr | kdtv2, kchr ^ kdtv2 from expr_test order by id"""
	qt_sql_test_268_notn """
		select id, kchr + kdtv2, kchr - kdtv2, kchr * kdtv2, kchr / kdtv2, kchr DIV kdtv2, kchr % kdtv2, kchr & kdtv2, kchr | kdtv2, kchr ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_269 """
		select id, kchr + kdtmv2, kchr - kdtmv2, kchr * kdtmv2, kchr / kdtmv2, kchr DIV kdtmv2, kchr % kdtmv2, kchr & kdtmv2, kchr | kdtmv2, kchr ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_270_notn """
		select id, kchr + kdtmv2, kchr - kdtmv2, kchr * kdtmv2, kchr / kdtmv2, kchr DIV kdtmv2, kchr % kdtmv2, kchr & kdtmv2, kchr | kdtmv2, kchr ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_271 """
		select id, kvchr + kbool, kvchr - kbool, kvchr * kbool, kvchr / kbool, kvchr DIV kbool, kvchr % kbool, kvchr & kbool, kvchr | kbool, kvchr ^ kbool from expr_test order by id"""
	qt_sql_test_272_notn """
		select id, kvchr + kbool, kvchr - kbool, kvchr * kbool, kvchr / kbool, kvchr DIV kbool, kvchr % kbool, kvchr & kbool, kvchr | kbool, kvchr ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_273 """
		select id, kvchr + ktint, kvchr - ktint, kvchr * ktint, kvchr / ktint, kvchr DIV ktint, kvchr % ktint, kvchr & ktint, kvchr | ktint, kvchr ^ ktint from expr_test order by id"""
	qt_sql_test_274_notn """
		select id, kvchr + ktint, kvchr - ktint, kvchr * ktint, kvchr / ktint, kvchr DIV ktint, kvchr % ktint, kvchr & ktint, kvchr | ktint, kvchr ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_275 """
		select id, kvchr + ksint, kvchr - ksint, kvchr * ksint, kvchr / ksint, kvchr DIV ksint, kvchr % ksint, kvchr & ksint, kvchr | ksint, kvchr ^ ksint from expr_test order by id"""
	qt_sql_test_276_notn """
		select id, kvchr + ksint, kvchr - ksint, kvchr * ksint, kvchr / ksint, kvchr DIV ksint, kvchr % ksint, kvchr & ksint, kvchr | ksint, kvchr ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_277 """
		select id, kvchr + kint, kvchr - kint, kvchr * kint, kvchr / kint, kvchr DIV kint, kvchr % kint, kvchr & kint, kvchr | kint, kvchr ^ kint from expr_test order by id"""
	qt_sql_test_278_notn """
		select id, kvchr + kint, kvchr - kint, kvchr * kint, kvchr / kint, kvchr DIV kint, kvchr % kint, kvchr & kint, kvchr | kint, kvchr ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_279 """
		select id, kvchr + kbint, kvchr - kbint, kvchr * kbint, kvchr / kbint, kvchr DIV kbint, kvchr % kbint, kvchr & kbint, kvchr | kbint, kvchr ^ kbint from expr_test order by id"""
	qt_sql_test_280_notn """
		select id, kvchr + kbint, kvchr - kbint, kvchr * kbint, kvchr / kbint, kvchr DIV kbint, kvchr % kbint, kvchr & kbint, kvchr | kbint, kvchr ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_281 """
		select id, kvchr + klint, kvchr - klint, kvchr * klint, kvchr / klint, kvchr DIV klint, kvchr % klint, kvchr & klint, kvchr | klint, kvchr ^ klint from expr_test order by id"""
	qt_sql_test_282_notn """
		select id, kvchr + klint, kvchr - klint, kvchr * klint, kvchr / klint, kvchr DIV klint, kvchr % klint, kvchr & klint, kvchr | klint, kvchr ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_283 """
		select id, kvchr + kfloat, kvchr - kfloat, kvchr * kfloat, kvchr / kfloat, kvchr DIV kfloat, kvchr % kfloat, kvchr & kfloat, kvchr | kfloat, kvchr ^ kfloat from expr_test order by id"""
	qt_sql_test_284_notn """
		select id, kvchr + kfloat, kvchr - kfloat, kvchr * kfloat, kvchr / kfloat, kvchr DIV kfloat, kvchr % kfloat, kvchr & kfloat, kvchr | kfloat, kvchr ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_285 """
		select id, kvchr + kdbl, kvchr - kdbl, kvchr * kdbl, kvchr / kdbl, kvchr DIV kdbl, kvchr % kdbl, kvchr & kdbl, kvchr | kdbl, kvchr ^ kdbl from expr_test order by id"""
	qt_sql_test_286_notn """
		select id, kvchr + kdbl, kvchr - kdbl, kvchr * kdbl, kvchr / kdbl, kvchr DIV kdbl, kvchr % kdbl, kvchr & kdbl, kvchr | kdbl, kvchr ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_287 """
		select id, kvchr + kchr, kvchr - kchr, kvchr * kchr, kvchr / kchr, kvchr DIV kchr, kvchr % kchr, kvchr & kchr, kvchr | kchr, kvchr ^ kchr from expr_test order by id"""
	qt_sql_test_288_notn """
		select id, kvchr + kchr, kvchr - kchr, kvchr * kchr, kvchr / kchr, kvchr DIV kchr, kvchr % kchr, kvchr & kchr, kvchr | kchr, kvchr ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_289 """
		select id, kvchr + kvchr, kvchr - kvchr, kvchr * kvchr, kvchr / kvchr, kvchr DIV kvchr, kvchr % kvchr, kvchr & kvchr, kvchr | kvchr, kvchr ^ kvchr from expr_test order by id"""
	qt_sql_test_290_notn """
		select id, kvchr + kvchr, kvchr - kvchr, kvchr * kvchr, kvchr / kvchr, kvchr DIV kvchr, kvchr % kvchr, kvchr & kvchr, kvchr | kvchr, kvchr ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_291 """
		select id, kvchr + kstr, kvchr - kstr, kvchr * kstr, kvchr / kstr, kvchr DIV kstr, kvchr % kstr, kvchr & kstr, kvchr | kstr, kvchr ^ kstr from expr_test order by id"""
	qt_sql_test_292_notn """
		select id, kvchr + kstr, kvchr - kstr, kvchr * kstr, kvchr / kstr, kvchr DIV kstr, kvchr % kstr, kvchr & kstr, kvchr | kstr, kvchr ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_293 """
		select id, kvchr + kdt, kvchr - kdt, kvchr * kdt, kvchr / kdt, kvchr DIV kdt, kvchr % kdt, kvchr & kdt, kvchr | kdt, kvchr ^ kdt from expr_test order by id"""
	qt_sql_test_294_notn """
		select id, kvchr + kdt, kvchr - kdt, kvchr * kdt, kvchr / kdt, kvchr DIV kdt, kvchr % kdt, kvchr & kdt, kvchr | kdt, kvchr ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_295 """
		select id, kvchr + kdtm, kvchr - kdtm, kvchr * kdtm, kvchr / kdtm, kvchr DIV kdtm, kvchr % kdtm, kvchr & kdtm, kvchr | kdtm, kvchr ^ kdtm from expr_test order by id"""
	qt_sql_test_296_notn """
		select id, kvchr + kdtm, kvchr - kdtm, kvchr * kdtm, kvchr / kdtm, kvchr DIV kdtm, kvchr % kdtm, kvchr & kdtm, kvchr | kdtm, kvchr ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_297 """
		select id, kvchr + kdtv2, kvchr - kdtv2, kvchr * kdtv2, kvchr / kdtv2, kvchr DIV kdtv2, kvchr % kdtv2, kvchr & kdtv2, kvchr | kdtv2, kvchr ^ kdtv2 from expr_test order by id"""
	qt_sql_test_298_notn """
		select id, kvchr + kdtv2, kvchr - kdtv2, kvchr * kdtv2, kvchr / kdtv2, kvchr DIV kdtv2, kvchr % kdtv2, kvchr & kdtv2, kvchr | kdtv2, kvchr ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_299 """
		select id, kvchr + kdtmv2, kvchr - kdtmv2, kvchr * kdtmv2, kvchr / kdtmv2, kvchr DIV kdtmv2, kvchr % kdtmv2, kvchr & kdtmv2, kvchr | kdtmv2, kvchr ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_300_notn """
		select id, kvchr + kdtmv2, kvchr - kdtmv2, kvchr * kdtmv2, kvchr / kdtmv2, kvchr DIV kdtmv2, kvchr % kdtmv2, kvchr & kdtmv2, kvchr | kdtmv2, kvchr ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_301 """
		select id, kstr + kbool, kstr - kbool, kstr * kbool, kstr / kbool, kstr DIV kbool, kstr % kbool, kstr & kbool, kstr | kbool, kstr ^ kbool from expr_test order by id"""
	qt_sql_test_302_notn """
		select id, kstr + kbool, kstr - kbool, kstr * kbool, kstr / kbool, kstr DIV kbool, kstr % kbool, kstr & kbool, kstr | kbool, kstr ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_303 """
		select id, kstr + ktint, kstr - ktint, kstr * ktint, kstr / ktint, kstr DIV ktint, kstr % ktint, kstr & ktint, kstr | ktint, kstr ^ ktint from expr_test order by id"""
	qt_sql_test_304_notn """
		select id, kstr + ktint, kstr - ktint, kstr * ktint, kstr / ktint, kstr DIV ktint, kstr % ktint, kstr & ktint, kstr | ktint, kstr ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_305 """
		select id, kstr + ksint, kstr - ksint, kstr * ksint, kstr / ksint, kstr DIV ksint, kstr % ksint, kstr & ksint, kstr | ksint, kstr ^ ksint from expr_test order by id"""
	qt_sql_test_306_notn """
		select id, kstr + ksint, kstr - ksint, kstr * ksint, kstr / ksint, kstr DIV ksint, kstr % ksint, kstr & ksint, kstr | ksint, kstr ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_307 """
		select id, kstr + kint, kstr - kint, kstr * kint, kstr / kint, kstr DIV kint, kstr % kint, kstr & kint, kstr | kint, kstr ^ kint from expr_test order by id"""
	qt_sql_test_308_notn """
		select id, kstr + kint, kstr - kint, kstr * kint, kstr / kint, kstr DIV kint, kstr % kint, kstr & kint, kstr | kint, kstr ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_309 """
		select id, kstr + kbint, kstr - kbint, kstr * kbint, kstr / kbint, kstr DIV kbint, kstr % kbint, kstr & kbint, kstr | kbint, kstr ^ kbint from expr_test order by id"""
	qt_sql_test_310_notn """
		select id, kstr + kbint, kstr - kbint, kstr * kbint, kstr / kbint, kstr DIV kbint, kstr % kbint, kstr & kbint, kstr | kbint, kstr ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_311 """
		select id, kstr + klint, kstr - klint, kstr * klint, kstr / klint, kstr DIV klint, kstr % klint, kstr & klint, kstr | klint, kstr ^ klint from expr_test order by id"""
	qt_sql_test_312_notn """
		select id, kstr + klint, kstr - klint, kstr * klint, kstr / klint, kstr DIV klint, kstr % klint, kstr & klint, kstr | klint, kstr ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_313 """
		select id, kstr + kfloat, kstr - kfloat, kstr * kfloat, kstr / kfloat, kstr DIV kfloat, kstr % kfloat, kstr & kfloat, kstr | kfloat, kstr ^ kfloat from expr_test order by id"""
	qt_sql_test_314_notn """
		select id, kstr + kfloat, kstr - kfloat, kstr * kfloat, kstr / kfloat, kstr DIV kfloat, kstr % kfloat, kstr & kfloat, kstr | kfloat, kstr ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_315 """
		select id, kstr + kdbl, kstr - kdbl, kstr * kdbl, kstr / kdbl, kstr DIV kdbl, kstr % kdbl, kstr & kdbl, kstr | kdbl, kstr ^ kdbl from expr_test order by id"""
	qt_sql_test_316_notn """
		select id, kstr + kdbl, kstr - kdbl, kstr * kdbl, kstr / kdbl, kstr DIV kdbl, kstr % kdbl, kstr & kdbl, kstr | kdbl, kstr ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_317 """
		select id, kstr + kchr, kstr - kchr, kstr * kchr, kstr / kchr, kstr DIV kchr, kstr % kchr, kstr & kchr, kstr | kchr, kstr ^ kchr from expr_test order by id"""
	qt_sql_test_318_notn """
		select id, kstr + kchr, kstr - kchr, kstr * kchr, kstr / kchr, kstr DIV kchr, kstr % kchr, kstr & kchr, kstr | kchr, kstr ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_319 """
		select id, kstr + kvchr, kstr - kvchr, kstr * kvchr, kstr / kvchr, kstr DIV kvchr, kstr % kvchr, kstr & kvchr, kstr | kvchr, kstr ^ kvchr from expr_test order by id"""
	qt_sql_test_320_notn """
		select id, kstr + kvchr, kstr - kvchr, kstr * kvchr, kstr / kvchr, kstr DIV kvchr, kstr % kvchr, kstr & kvchr, kstr | kvchr, kstr ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_321 """
		select id, kstr + kstr, kstr - kstr, kstr * kstr, kstr / kstr, kstr DIV kstr, kstr % kstr, kstr & kstr, kstr | kstr, kstr ^ kstr from expr_test order by id"""
	qt_sql_test_322_notn """
		select id, kstr + kstr, kstr - kstr, kstr * kstr, kstr / kstr, kstr DIV kstr, kstr % kstr, kstr & kstr, kstr | kstr, kstr ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_323 """
		select id, kstr + kdt, kstr - kdt, kstr * kdt, kstr / kdt, kstr DIV kdt, kstr % kdt, kstr & kdt, kstr | kdt, kstr ^ kdt from expr_test order by id"""
	qt_sql_test_324_notn """
		select id, kstr + kdt, kstr - kdt, kstr * kdt, kstr / kdt, kstr DIV kdt, kstr % kdt, kstr & kdt, kstr | kdt, kstr ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_325 """
		select id, kstr + kdtm, kstr - kdtm, kstr * kdtm, kstr / kdtm, kstr DIV kdtm, kstr % kdtm, kstr & kdtm, kstr | kdtm, kstr ^ kdtm from expr_test order by id"""
	qt_sql_test_326_notn """
		select id, kstr + kdtm, kstr - kdtm, kstr * kdtm, kstr / kdtm, kstr DIV kdtm, kstr % kdtm, kstr & kdtm, kstr | kdtm, kstr ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_327 """
		select id, kstr + kdtv2, kstr - kdtv2, kstr * kdtv2, kstr / kdtv2, kstr DIV kdtv2, kstr % kdtv2, kstr & kdtv2, kstr | kdtv2, kstr ^ kdtv2 from expr_test order by id"""
	qt_sql_test_328_notn """
		select id, kstr + kdtv2, kstr - kdtv2, kstr * kdtv2, kstr / kdtv2, kstr DIV kdtv2, kstr % kdtv2, kstr & kdtv2, kstr | kdtv2, kstr ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_329 """
		select id, kstr + kdtmv2, kstr - kdtmv2, kstr * kdtmv2, kstr / kdtmv2, kstr DIV kdtmv2, kstr % kdtmv2, kstr & kdtmv2, kstr | kdtmv2, kstr ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_330_notn """
		select id, kstr + kdtmv2, kstr - kdtmv2, kstr * kdtmv2, kstr / kdtmv2, kstr DIV kdtmv2, kstr % kdtmv2, kstr & kdtmv2, kstr | kdtmv2, kstr ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_331 """
		select id, kdt + kbool, kdt - kbool, kdt * kbool, kdt / kbool, kdt DIV kbool, kdt % kbool, kdt & kbool, kdt | kbool, kdt ^ kbool from expr_test order by id"""
	qt_sql_test_332_notn """
		select id, kdt + kbool, kdt - kbool, kdt * kbool, kdt / kbool, kdt DIV kbool, kdt % kbool, kdt & kbool, kdt | kbool, kdt ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_333 """
		select id, kdt + ktint, kdt - ktint, kdt * ktint, kdt / ktint, kdt DIV ktint, kdt % ktint, kdt & ktint, kdt | ktint, kdt ^ ktint from expr_test order by id"""
	qt_sql_test_334_notn """
		select id, kdt + ktint, kdt - ktint, kdt * ktint, kdt / ktint, kdt DIV ktint, kdt % ktint, kdt & ktint, kdt | ktint, kdt ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_335 """
		select id, kdt + ksint, kdt - ksint, kdt * ksint, kdt / ksint, kdt DIV ksint, kdt % ksint, kdt & ksint, kdt | ksint, kdt ^ ksint from expr_test order by id"""
	qt_sql_test_336_notn """
		select id, kdt + ksint, kdt - ksint, kdt * ksint, kdt / ksint, kdt DIV ksint, kdt % ksint, kdt & ksint, kdt | ksint, kdt ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_337 """
		select id, kdt + kint, kdt - kint, kdt * kint, kdt / kint, kdt DIV kint, kdt % kint, kdt & kint, kdt | kint, kdt ^ kint from expr_test order by id"""
	qt_sql_test_338_notn """
		select id, kdt + kint, kdt - kint, kdt * kint, kdt / kint, kdt DIV kint, kdt % kint, kdt & kint, kdt | kint, kdt ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_339 """
		select id, kdt + kbint, kdt - kbint, kdt * kbint, kdt / kbint, kdt DIV kbint, kdt % kbint, kdt & kbint, kdt | kbint, kdt ^ kbint from expr_test order by id"""
	qt_sql_test_340_notn """
		select id, kdt + kbint, kdt - kbint, kdt * kbint, kdt / kbint, kdt DIV kbint, kdt % kbint, kdt & kbint, kdt | kbint, kdt ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_341 """
		select id, kdt + klint, kdt - klint, kdt * klint, kdt / klint, kdt DIV klint, kdt % klint, kdt & klint, kdt | klint, kdt ^ klint from expr_test order by id"""
	qt_sql_test_342_notn """
		select id, kdt + klint, kdt - klint, kdt * klint, kdt / klint, kdt DIV klint, kdt % klint, kdt & klint, kdt | klint, kdt ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_343 """
		select id, kdt + kfloat, kdt - kfloat, kdt * kfloat, kdt / kfloat, kdt DIV kfloat, kdt % kfloat, kdt & kfloat, kdt | kfloat, kdt ^ kfloat from expr_test order by id"""
	qt_sql_test_344_notn """
		select id, kdt + kfloat, kdt - kfloat, kdt * kfloat, kdt / kfloat, kdt DIV kfloat, kdt % kfloat, kdt & kfloat, kdt | kfloat, kdt ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_345 """
		select id, kdt + kdbl, kdt - kdbl, kdt * kdbl, kdt / kdbl, kdt DIV kdbl, kdt % kdbl, kdt & kdbl, kdt | kdbl, kdt ^ kdbl from expr_test order by id"""
	qt_sql_test_346_notn """
		select id, kdt + kdbl, kdt - kdbl, kdt * kdbl, kdt / kdbl, kdt DIV kdbl, kdt % kdbl, kdt & kdbl, kdt | kdbl, kdt ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_347 """
		select id, kdt + kchr, kdt - kchr, kdt * kchr, kdt / kchr, kdt DIV kchr, kdt % kchr, kdt & kchr, kdt | kchr, kdt ^ kchr from expr_test order by id"""
	qt_sql_test_348_notn """
		select id, kdt + kchr, kdt - kchr, kdt * kchr, kdt / kchr, kdt DIV kchr, kdt % kchr, kdt & kchr, kdt | kchr, kdt ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_349 """
		select id, kdt + kvchr, kdt - kvchr, kdt * kvchr, kdt / kvchr, kdt DIV kvchr, kdt % kvchr, kdt & kvchr, kdt | kvchr, kdt ^ kvchr from expr_test order by id"""
	qt_sql_test_350_notn """
		select id, kdt + kvchr, kdt - kvchr, kdt * kvchr, kdt / kvchr, kdt DIV kvchr, kdt % kvchr, kdt & kvchr, kdt | kvchr, kdt ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_351 """
		select id, kdt + kstr, kdt - kstr, kdt * kstr, kdt / kstr, kdt DIV kstr, kdt % kstr, kdt & kstr, kdt | kstr, kdt ^ kstr from expr_test order by id"""
	qt_sql_test_352_notn """
		select id, kdt + kstr, kdt - kstr, kdt * kstr, kdt / kstr, kdt DIV kstr, kdt % kstr, kdt & kstr, kdt | kstr, kdt ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_353 """
		select id, kdt + kdt, kdt - kdt, kdt * kdt, kdt / kdt, kdt DIV kdt, kdt % kdt, kdt & kdt, kdt | kdt, kdt ^ kdt from expr_test order by id"""
	qt_sql_test_354_notn """
		select id, kdt + kdt, kdt - kdt, kdt * kdt, kdt / kdt, kdt DIV kdt, kdt % kdt, kdt & kdt, kdt | kdt, kdt ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_355 """
		select id, kdt + kdtm, kdt - kdtm, kdt * kdtm, kdt / kdtm, kdt DIV kdtm, kdt % kdtm, kdt & kdtm, kdt | kdtm, kdt ^ kdtm from expr_test order by id"""
	qt_sql_test_356_notn """
		select id, kdt + kdtm, kdt - kdtm, kdt * kdtm, kdt / kdtm, kdt DIV kdtm, kdt % kdtm, kdt & kdtm, kdt | kdtm, kdt ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_357 """
		select id, kdt + kdtv2, kdt - kdtv2, kdt * kdtv2, kdt / kdtv2, kdt DIV kdtv2, kdt % kdtv2, kdt & kdtv2, kdt | kdtv2, kdt ^ kdtv2 from expr_test order by id"""
	qt_sql_test_358_notn """
		select id, kdt + kdtv2, kdt - kdtv2, kdt * kdtv2, kdt / kdtv2, kdt DIV kdtv2, kdt % kdtv2, kdt & kdtv2, kdt | kdtv2, kdt ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_359 """
		select id, kdt + kdtmv2, kdt - kdtmv2, kdt * kdtmv2, kdt / kdtmv2, kdt DIV kdtmv2, kdt % kdtmv2, kdt & kdtmv2, kdt | kdtmv2, kdt ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_360_notn """
		select id, kdt + kdtmv2, kdt - kdtmv2, kdt * kdtmv2, kdt / kdtmv2, kdt DIV kdtmv2, kdt % kdtmv2, kdt & kdtmv2, kdt | kdtmv2, kdt ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_361 """
		select id, kdtm + kbool, kdtm - kbool, kdtm * kbool, kdtm / kbool, kdtm DIV kbool, kdtm % kbool, kdtm & kbool, kdtm | kbool, kdtm ^ kbool from expr_test order by id"""
	qt_sql_test_362_notn """
		select id, kdtm + kbool, kdtm - kbool, kdtm * kbool, kdtm / kbool, kdtm DIV kbool, kdtm % kbool, kdtm & kbool, kdtm | kbool, kdtm ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_363 """
		select id, kdtm + ktint, kdtm - ktint, kdtm * ktint, kdtm / ktint, kdtm DIV ktint, kdtm % ktint, kdtm & ktint, kdtm | ktint, kdtm ^ ktint from expr_test order by id"""
	qt_sql_test_364_notn """
		select id, kdtm + ktint, kdtm - ktint, kdtm * ktint, kdtm / ktint, kdtm DIV ktint, kdtm % ktint, kdtm & ktint, kdtm | ktint, kdtm ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_365 """
		select id, kdtm + ksint, kdtm - ksint, kdtm * ksint, kdtm / ksint, kdtm DIV ksint, kdtm % ksint, kdtm & ksint, kdtm | ksint, kdtm ^ ksint from expr_test order by id"""
	qt_sql_test_366_notn """
		select id, kdtm + ksint, kdtm - ksint, kdtm * ksint, kdtm / ksint, kdtm DIV ksint, kdtm % ksint, kdtm & ksint, kdtm | ksint, kdtm ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_367 """
		select id, kdtm + kint, kdtm - kint, kdtm * kint, kdtm / kint, kdtm DIV kint, kdtm % kint, kdtm & kint, kdtm | kint, kdtm ^ kint from expr_test order by id"""
	qt_sql_test_368_notn """
		select id, kdtm + kint, kdtm - kint, kdtm * kint, kdtm / kint, kdtm DIV kint, kdtm % kint, kdtm & kint, kdtm | kint, kdtm ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_369 """
		select id, kdtm + kbint, kdtm - kbint, kdtm * kbint, kdtm / kbint, kdtm DIV kbint, kdtm % kbint, kdtm & kbint, kdtm | kbint, kdtm ^ kbint from expr_test order by id"""
	qt_sql_test_370_notn """
		select id, kdtm + kbint, kdtm - kbint, kdtm * kbint, kdtm / kbint, kdtm DIV kbint, kdtm % kbint, kdtm & kbint, kdtm | kbint, kdtm ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_371 """
		select id, kdtm + klint, kdtm - klint, kdtm * klint, kdtm / klint, kdtm DIV klint, kdtm % klint, kdtm & klint, kdtm | klint, kdtm ^ klint from expr_test order by id"""
	qt_sql_test_372_notn """
		select id, kdtm + klint, kdtm - klint, kdtm * klint, kdtm / klint, kdtm DIV klint, kdtm % klint, kdtm & klint, kdtm | klint, kdtm ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_373 """
		select id, kdtm + kfloat, kdtm - kfloat, kdtm * kfloat, kdtm / kfloat, kdtm DIV kfloat, kdtm % kfloat, kdtm & kfloat, kdtm | kfloat, kdtm ^ kfloat from expr_test order by id"""
	qt_sql_test_374_notn """
		select id, kdtm + kfloat, kdtm - kfloat, kdtm * kfloat, kdtm / kfloat, kdtm DIV kfloat, kdtm % kfloat, kdtm & kfloat, kdtm | kfloat, kdtm ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_375 """
		select id, kdtm + kdbl, kdtm - kdbl, kdtm * kdbl, kdtm / kdbl, kdtm DIV kdbl, kdtm % kdbl, kdtm & kdbl, kdtm | kdbl, kdtm ^ kdbl from expr_test order by id"""
	qt_sql_test_376_notn """
		select id, kdtm + kdbl, kdtm - kdbl, kdtm * kdbl, kdtm / kdbl, kdtm DIV kdbl, kdtm % kdbl, kdtm & kdbl, kdtm | kdbl, kdtm ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_377 """
		select id, kdtm + kchr, kdtm - kchr, kdtm * kchr, kdtm / kchr, kdtm DIV kchr, kdtm % kchr, kdtm & kchr, kdtm | kchr, kdtm ^ kchr from expr_test order by id"""
	qt_sql_test_378_notn """
		select id, kdtm + kchr, kdtm - kchr, kdtm * kchr, kdtm / kchr, kdtm DIV kchr, kdtm % kchr, kdtm & kchr, kdtm | kchr, kdtm ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_379 """
		select id, kdtm + kvchr, kdtm - kvchr, kdtm * kvchr, kdtm / kvchr, kdtm DIV kvchr, kdtm % kvchr, kdtm & kvchr, kdtm | kvchr, kdtm ^ kvchr from expr_test order by id"""
	qt_sql_test_380_notn """
		select id, kdtm + kvchr, kdtm - kvchr, kdtm * kvchr, kdtm / kvchr, kdtm DIV kvchr, kdtm % kvchr, kdtm & kvchr, kdtm | kvchr, kdtm ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_381 """
		select id, kdtm + kstr, kdtm - kstr, kdtm * kstr, kdtm / kstr, kdtm DIV kstr, kdtm % kstr, kdtm & kstr, kdtm | kstr, kdtm ^ kstr from expr_test order by id"""
	qt_sql_test_382_notn """
		select id, kdtm + kstr, kdtm - kstr, kdtm * kstr, kdtm / kstr, kdtm DIV kstr, kdtm % kstr, kdtm & kstr, kdtm | kstr, kdtm ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_383 """
		select id, kdtm + kdt, kdtm - kdt, kdtm * kdt, kdtm / kdt, kdtm DIV kdt, kdtm % kdt, kdtm & kdt, kdtm | kdt, kdtm ^ kdt from expr_test order by id"""
	qt_sql_test_384_notn """
		select id, kdtm + kdt, kdtm - kdt, kdtm * kdt, kdtm / kdt, kdtm DIV kdt, kdtm % kdt, kdtm & kdt, kdtm | kdt, kdtm ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_385 """
		select id, kdtm + kdtm, kdtm - kdtm, kdtm * kdtm, kdtm / kdtm, kdtm DIV kdtm, kdtm % kdtm, kdtm & kdtm, kdtm | kdtm, kdtm ^ kdtm from expr_test order by id"""
	qt_sql_test_386_notn """
		select id, kdtm + kdtm, kdtm - kdtm, kdtm * kdtm, kdtm / kdtm, kdtm DIV kdtm, kdtm % kdtm, kdtm & kdtm, kdtm | kdtm, kdtm ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_387 """
		select id, kdtm + kdtv2, kdtm - kdtv2, kdtm * kdtv2, kdtm / kdtv2, kdtm DIV kdtv2, kdtm % kdtv2, kdtm & kdtv2, kdtm | kdtv2, kdtm ^ kdtv2 from expr_test order by id"""
	qt_sql_test_388_notn """
		select id, kdtm + kdtv2, kdtm - kdtv2, kdtm * kdtv2, kdtm / kdtv2, kdtm DIV kdtv2, kdtm % kdtv2, kdtm & kdtv2, kdtm | kdtv2, kdtm ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_389 """
		select id, kdtm + kdtmv2, kdtm - kdtmv2, kdtm * kdtmv2, kdtm / kdtmv2, kdtm DIV kdtmv2, kdtm % kdtmv2, kdtm & kdtmv2, kdtm | kdtmv2, kdtm ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_390_notn """
		select id, kdtm + kdtmv2, kdtm - kdtmv2, kdtm * kdtmv2, kdtm / kdtmv2, kdtm DIV kdtmv2, kdtm % kdtmv2, kdtm & kdtmv2, kdtm | kdtmv2, kdtm ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_391 """
		select id, kdtv2 + kbool, kdtv2 - kbool, kdtv2 * kbool, kdtv2 / kbool, kdtv2 DIV kbool, kdtv2 % kbool, kdtv2 & kbool, kdtv2 | kbool, kdtv2 ^ kbool from expr_test order by id"""
	qt_sql_test_392_notn """
		select id, kdtv2 + kbool, kdtv2 - kbool, kdtv2 * kbool, kdtv2 / kbool, kdtv2 DIV kbool, kdtv2 % kbool, kdtv2 & kbool, kdtv2 | kbool, kdtv2 ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_393 """
		select id, kdtv2 + ktint, kdtv2 - ktint, kdtv2 * ktint, kdtv2 / ktint, kdtv2 DIV ktint, kdtv2 % ktint, kdtv2 & ktint, kdtv2 | ktint, kdtv2 ^ ktint from expr_test order by id"""
	qt_sql_test_394_notn """
		select id, kdtv2 + ktint, kdtv2 - ktint, kdtv2 * ktint, kdtv2 / ktint, kdtv2 DIV ktint, kdtv2 % ktint, kdtv2 & ktint, kdtv2 | ktint, kdtv2 ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_395 """
		select id, kdtv2 + ksint, kdtv2 - ksint, kdtv2 * ksint, kdtv2 / ksint, kdtv2 DIV ksint, kdtv2 % ksint, kdtv2 & ksint, kdtv2 | ksint, kdtv2 ^ ksint from expr_test order by id"""
	qt_sql_test_396_notn """
		select id, kdtv2 + ksint, kdtv2 - ksint, kdtv2 * ksint, kdtv2 / ksint, kdtv2 DIV ksint, kdtv2 % ksint, kdtv2 & ksint, kdtv2 | ksint, kdtv2 ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_397 """
		select id, kdtv2 + kint, kdtv2 - kint, kdtv2 * kint, kdtv2 / kint, kdtv2 DIV kint, kdtv2 % kint, kdtv2 & kint, kdtv2 | kint, kdtv2 ^ kint from expr_test order by id"""
	qt_sql_test_398_notn """
		select id, kdtv2 + kint, kdtv2 - kint, kdtv2 * kint, kdtv2 / kint, kdtv2 DIV kint, kdtv2 % kint, kdtv2 & kint, kdtv2 | kint, kdtv2 ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_399 """
		select id, kdtv2 + kbint, kdtv2 - kbint, kdtv2 * kbint, kdtv2 / kbint, kdtv2 DIV kbint, kdtv2 % kbint, kdtv2 & kbint, kdtv2 | kbint, kdtv2 ^ kbint from expr_test order by id"""
	qt_sql_test_400_notn """
		select id, kdtv2 + kbint, kdtv2 - kbint, kdtv2 * kbint, kdtv2 / kbint, kdtv2 DIV kbint, kdtv2 % kbint, kdtv2 & kbint, kdtv2 | kbint, kdtv2 ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_401 """
		select id, kdtv2 + klint, kdtv2 - klint, kdtv2 * klint, kdtv2 / klint, kdtv2 DIV klint, kdtv2 % klint, kdtv2 & klint, kdtv2 | klint, kdtv2 ^ klint from expr_test order by id"""
	qt_sql_test_402_notn """
		select id, kdtv2 + klint, kdtv2 - klint, kdtv2 * klint, kdtv2 / klint, kdtv2 DIV klint, kdtv2 % klint, kdtv2 & klint, kdtv2 | klint, kdtv2 ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_403 """
		select id, kdtv2 + kfloat, kdtv2 - kfloat, kdtv2 * kfloat, kdtv2 / kfloat, kdtv2 DIV kfloat, kdtv2 % kfloat, kdtv2 & kfloat, kdtv2 | kfloat, kdtv2 ^ kfloat from expr_test order by id"""
	qt_sql_test_404_notn """
		select id, kdtv2 + kfloat, kdtv2 - kfloat, kdtv2 * kfloat, kdtv2 / kfloat, kdtv2 DIV kfloat, kdtv2 % kfloat, kdtv2 & kfloat, kdtv2 | kfloat, kdtv2 ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_405 """
		select id, kdtv2 + kdbl, kdtv2 - kdbl, kdtv2 * kdbl, kdtv2 / kdbl, kdtv2 DIV kdbl, kdtv2 % kdbl, kdtv2 & kdbl, kdtv2 | kdbl, kdtv2 ^ kdbl from expr_test order by id"""
	qt_sql_test_406_notn """
		select id, kdtv2 + kdbl, kdtv2 - kdbl, kdtv2 * kdbl, kdtv2 / kdbl, kdtv2 DIV kdbl, kdtv2 % kdbl, kdtv2 & kdbl, kdtv2 | kdbl, kdtv2 ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_407 """
		select id, kdtv2 + kchr, kdtv2 - kchr, kdtv2 * kchr, kdtv2 / kchr, kdtv2 DIV kchr, kdtv2 % kchr, kdtv2 & kchr, kdtv2 | kchr, kdtv2 ^ kchr from expr_test order by id"""
	qt_sql_test_408_notn """
		select id, kdtv2 + kchr, kdtv2 - kchr, kdtv2 * kchr, kdtv2 / kchr, kdtv2 DIV kchr, kdtv2 % kchr, kdtv2 & kchr, kdtv2 | kchr, kdtv2 ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_409 """
		select id, kdtv2 + kvchr, kdtv2 - kvchr, kdtv2 * kvchr, kdtv2 / kvchr, kdtv2 DIV kvchr, kdtv2 % kvchr, kdtv2 & kvchr, kdtv2 | kvchr, kdtv2 ^ kvchr from expr_test order by id"""
	qt_sql_test_410_notn """
		select id, kdtv2 + kvchr, kdtv2 - kvchr, kdtv2 * kvchr, kdtv2 / kvchr, kdtv2 DIV kvchr, kdtv2 % kvchr, kdtv2 & kvchr, kdtv2 | kvchr, kdtv2 ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_411 """
		select id, kdtv2 + kstr, kdtv2 - kstr, kdtv2 * kstr, kdtv2 / kstr, kdtv2 DIV kstr, kdtv2 % kstr, kdtv2 & kstr, kdtv2 | kstr, kdtv2 ^ kstr from expr_test order by id"""
	qt_sql_test_412_notn """
		select id, kdtv2 + kstr, kdtv2 - kstr, kdtv2 * kstr, kdtv2 / kstr, kdtv2 DIV kstr, kdtv2 % kstr, kdtv2 & kstr, kdtv2 | kstr, kdtv2 ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_413 """
		select id, kdtv2 + kdt, kdtv2 - kdt, kdtv2 * kdt, kdtv2 / kdt, kdtv2 DIV kdt, kdtv2 % kdt, kdtv2 & kdt, kdtv2 | kdt, kdtv2 ^ kdt from expr_test order by id"""
	qt_sql_test_414_notn """
		select id, kdtv2 + kdt, kdtv2 - kdt, kdtv2 * kdt, kdtv2 / kdt, kdtv2 DIV kdt, kdtv2 % kdt, kdtv2 & kdt, kdtv2 | kdt, kdtv2 ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_415 """
		select id, kdtv2 + kdtm, kdtv2 - kdtm, kdtv2 * kdtm, kdtv2 / kdtm, kdtv2 DIV kdtm, kdtv2 % kdtm, kdtv2 & kdtm, kdtv2 | kdtm, kdtv2 ^ kdtm from expr_test order by id"""
	qt_sql_test_416_notn """
		select id, kdtv2 + kdtm, kdtv2 - kdtm, kdtv2 * kdtm, kdtv2 / kdtm, kdtv2 DIV kdtm, kdtv2 % kdtm, kdtv2 & kdtm, kdtv2 | kdtm, kdtv2 ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_417 """
		select id, kdtv2 + kdtv2, kdtv2 - kdtv2, kdtv2 * kdtv2, kdtv2 / kdtv2, kdtv2 DIV kdtv2, kdtv2 % kdtv2, kdtv2 & kdtv2, kdtv2 | kdtv2, kdtv2 ^ kdtv2 from expr_test order by id"""
	qt_sql_test_418_notn """
		select id, kdtv2 + kdtv2, kdtv2 - kdtv2, kdtv2 * kdtv2, kdtv2 / kdtv2, kdtv2 DIV kdtv2, kdtv2 % kdtv2, kdtv2 & kdtv2, kdtv2 | kdtv2, kdtv2 ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_419 """
		select id, kdtv2 + kdtmv2, kdtv2 - kdtmv2, kdtv2 * kdtmv2, kdtv2 / kdtmv2, kdtv2 DIV kdtmv2, kdtv2 % kdtmv2, kdtv2 & kdtmv2, kdtv2 | kdtmv2, kdtv2 ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_420_notn """
		select id, kdtv2 + kdtmv2, kdtv2 - kdtmv2, kdtv2 * kdtmv2, kdtv2 / kdtmv2, kdtv2 DIV kdtmv2, kdtv2 % kdtmv2, kdtv2 & kdtmv2, kdtv2 | kdtmv2, kdtv2 ^ kdtmv2 from expr_test_not_nullable order by id"""
	qt_sql_test_421 """
		select id, kdtmv2 + kbool, kdtmv2 - kbool, kdtmv2 * kbool, kdtmv2 / kbool, kdtmv2 DIV kbool, kdtmv2 % kbool, kdtmv2 & kbool, kdtmv2 | kbool, kdtmv2 ^ kbool from expr_test order by id"""
	qt_sql_test_422_notn """
		select id, kdtmv2 + kbool, kdtmv2 - kbool, kdtmv2 * kbool, kdtmv2 / kbool, kdtmv2 DIV kbool, kdtmv2 % kbool, kdtmv2 & kbool, kdtmv2 | kbool, kdtmv2 ^ kbool from expr_test_not_nullable order by id"""
	qt_sql_test_423 """
		select id, kdtmv2 + ktint, kdtmv2 - ktint, kdtmv2 * ktint, kdtmv2 / ktint, kdtmv2 DIV ktint, kdtmv2 % ktint, kdtmv2 & ktint, kdtmv2 | ktint, kdtmv2 ^ ktint from expr_test order by id"""
	qt_sql_test_424_notn """
		select id, kdtmv2 + ktint, kdtmv2 - ktint, kdtmv2 * ktint, kdtmv2 / ktint, kdtmv2 DIV ktint, kdtmv2 % ktint, kdtmv2 & ktint, kdtmv2 | ktint, kdtmv2 ^ ktint from expr_test_not_nullable order by id"""
	qt_sql_test_425 """
		select id, kdtmv2 + ksint, kdtmv2 - ksint, kdtmv2 * ksint, kdtmv2 / ksint, kdtmv2 DIV ksint, kdtmv2 % ksint, kdtmv2 & ksint, kdtmv2 | ksint, kdtmv2 ^ ksint from expr_test order by id"""
	qt_sql_test_426_notn """
		select id, kdtmv2 + ksint, kdtmv2 - ksint, kdtmv2 * ksint, kdtmv2 / ksint, kdtmv2 DIV ksint, kdtmv2 % ksint, kdtmv2 & ksint, kdtmv2 | ksint, kdtmv2 ^ ksint from expr_test_not_nullable order by id"""
	qt_sql_test_427 """
		select id, kdtmv2 + kint, kdtmv2 - kint, kdtmv2 * kint, kdtmv2 / kint, kdtmv2 DIV kint, kdtmv2 % kint, kdtmv2 & kint, kdtmv2 | kint, kdtmv2 ^ kint from expr_test order by id"""
	qt_sql_test_428_notn """
		select id, kdtmv2 + kint, kdtmv2 - kint, kdtmv2 * kint, kdtmv2 / kint, kdtmv2 DIV kint, kdtmv2 % kint, kdtmv2 & kint, kdtmv2 | kint, kdtmv2 ^ kint from expr_test_not_nullable order by id"""
	qt_sql_test_429 """
		select id, kdtmv2 + kbint, kdtmv2 - kbint, kdtmv2 * kbint, kdtmv2 / kbint, kdtmv2 DIV kbint, kdtmv2 % kbint, kdtmv2 & kbint, kdtmv2 | kbint, kdtmv2 ^ kbint from expr_test order by id"""
	qt_sql_test_430_notn """
		select id, kdtmv2 + kbint, kdtmv2 - kbint, kdtmv2 * kbint, kdtmv2 / kbint, kdtmv2 DIV kbint, kdtmv2 % kbint, kdtmv2 & kbint, kdtmv2 | kbint, kdtmv2 ^ kbint from expr_test_not_nullable order by id"""
	qt_sql_test_431 """
		select id, kdtmv2 + klint, kdtmv2 - klint, kdtmv2 * klint, kdtmv2 / klint, kdtmv2 DIV klint, kdtmv2 % klint, kdtmv2 & klint, kdtmv2 | klint, kdtmv2 ^ klint from expr_test order by id"""
	qt_sql_test_432_notn """
		select id, kdtmv2 + klint, kdtmv2 - klint, kdtmv2 * klint, kdtmv2 / klint, kdtmv2 DIV klint, kdtmv2 % klint, kdtmv2 & klint, kdtmv2 | klint, kdtmv2 ^ klint from expr_test_not_nullable order by id"""
	qt_sql_test_433 """
		select id, kdtmv2 + kfloat, kdtmv2 - kfloat, kdtmv2 * kfloat, kdtmv2 / kfloat, kdtmv2 DIV kfloat, kdtmv2 % kfloat, kdtmv2 & kfloat, kdtmv2 | kfloat, kdtmv2 ^ kfloat from expr_test order by id"""
	qt_sql_test_434_notn """
		select id, kdtmv2 + kfloat, kdtmv2 - kfloat, kdtmv2 * kfloat, kdtmv2 / kfloat, kdtmv2 DIV kfloat, kdtmv2 % kfloat, kdtmv2 & kfloat, kdtmv2 | kfloat, kdtmv2 ^ kfloat from expr_test_not_nullable order by id"""
	qt_sql_test_435 """
		select id, kdtmv2 + kdbl, kdtmv2 - kdbl, kdtmv2 * kdbl, kdtmv2 / kdbl, kdtmv2 DIV kdbl, kdtmv2 % kdbl, kdtmv2 & kdbl, kdtmv2 | kdbl, kdtmv2 ^ kdbl from expr_test order by id"""
	qt_sql_test_436_notn """
		select id, kdtmv2 + kdbl, kdtmv2 - kdbl, kdtmv2 * kdbl, kdtmv2 / kdbl, kdtmv2 DIV kdbl, kdtmv2 % kdbl, kdtmv2 & kdbl, kdtmv2 | kdbl, kdtmv2 ^ kdbl from expr_test_not_nullable order by id"""
	qt_sql_test_437 """
		select id, kdtmv2 + kchr, kdtmv2 - kchr, kdtmv2 * kchr, kdtmv2 / kchr, kdtmv2 DIV kchr, kdtmv2 % kchr, kdtmv2 & kchr, kdtmv2 | kchr, kdtmv2 ^ kchr from expr_test order by id"""
	qt_sql_test_438_notn """
		select id, kdtmv2 + kchr, kdtmv2 - kchr, kdtmv2 * kchr, kdtmv2 / kchr, kdtmv2 DIV kchr, kdtmv2 % kchr, kdtmv2 & kchr, kdtmv2 | kchr, kdtmv2 ^ kchr from expr_test_not_nullable order by id"""
	qt_sql_test_439 """
		select id, kdtmv2 + kvchr, kdtmv2 - kvchr, kdtmv2 * kvchr, kdtmv2 / kvchr, kdtmv2 DIV kvchr, kdtmv2 % kvchr, kdtmv2 & kvchr, kdtmv2 | kvchr, kdtmv2 ^ kvchr from expr_test order by id"""
	qt_sql_test_440_notn """
		select id, kdtmv2 + kvchr, kdtmv2 - kvchr, kdtmv2 * kvchr, kdtmv2 / kvchr, kdtmv2 DIV kvchr, kdtmv2 % kvchr, kdtmv2 & kvchr, kdtmv2 | kvchr, kdtmv2 ^ kvchr from expr_test_not_nullable order by id"""
	qt_sql_test_441 """
		select id, kdtmv2 + kstr, kdtmv2 - kstr, kdtmv2 * kstr, kdtmv2 / kstr, kdtmv2 DIV kstr, kdtmv2 % kstr, kdtmv2 & kstr, kdtmv2 | kstr, kdtmv2 ^ kstr from expr_test order by id"""
	qt_sql_test_442_notn """
		select id, kdtmv2 + kstr, kdtmv2 - kstr, kdtmv2 * kstr, kdtmv2 / kstr, kdtmv2 DIV kstr, kdtmv2 % kstr, kdtmv2 & kstr, kdtmv2 | kstr, kdtmv2 ^ kstr from expr_test_not_nullable order by id"""
	qt_sql_test_443 """
		select id, kdtmv2 + kdt, kdtmv2 - kdt, kdtmv2 * kdt, kdtmv2 / kdt, kdtmv2 DIV kdt, kdtmv2 % kdt, kdtmv2 & kdt, kdtmv2 | kdt, kdtmv2 ^ kdt from expr_test order by id"""
	qt_sql_test_444_notn """
		select id, kdtmv2 + kdt, kdtmv2 - kdt, kdtmv2 * kdt, kdtmv2 / kdt, kdtmv2 DIV kdt, kdtmv2 % kdt, kdtmv2 & kdt, kdtmv2 | kdt, kdtmv2 ^ kdt from expr_test_not_nullable order by id"""
	qt_sql_test_445 """
		select id, kdtmv2 + kdtm, kdtmv2 - kdtm, kdtmv2 * kdtm, kdtmv2 / kdtm, kdtmv2 DIV kdtm, kdtmv2 % kdtm, kdtmv2 & kdtm, kdtmv2 | kdtm, kdtmv2 ^ kdtm from expr_test order by id"""
	qt_sql_test_446_notn """
		select id, kdtmv2 + kdtm, kdtmv2 - kdtm, kdtmv2 * kdtm, kdtmv2 / kdtm, kdtmv2 DIV kdtm, kdtmv2 % kdtm, kdtmv2 & kdtm, kdtmv2 | kdtm, kdtmv2 ^ kdtm from expr_test_not_nullable order by id"""
	qt_sql_test_447 """
		select id, kdtmv2 + kdtv2, kdtmv2 - kdtv2, kdtmv2 * kdtv2, kdtmv2 / kdtv2, kdtmv2 DIV kdtv2, kdtmv2 % kdtv2, kdtmv2 & kdtv2, kdtmv2 | kdtv2, kdtmv2 ^ kdtv2 from expr_test order by id"""
	qt_sql_test_448_notn """
		select id, kdtmv2 + kdtv2, kdtmv2 - kdtv2, kdtmv2 * kdtv2, kdtmv2 / kdtv2, kdtmv2 DIV kdtv2, kdtmv2 % kdtv2, kdtmv2 & kdtv2, kdtmv2 | kdtv2, kdtmv2 ^ kdtv2 from expr_test_not_nullable order by id"""
	qt_sql_test_449 """
		select id, kdtmv2 + kdtmv2, kdtmv2 - kdtmv2, kdtmv2 * kdtmv2, kdtmv2 / kdtmv2, kdtmv2 DIV kdtmv2, kdtmv2 % kdtmv2, kdtmv2 & kdtmv2, kdtmv2 | kdtmv2, kdtmv2 ^ kdtmv2 from expr_test order by id"""
	qt_sql_test_450_notn """
		select id, kdtmv2 + kdtmv2, kdtmv2 - kdtmv2, kdtmv2 * kdtmv2, kdtmv2 / kdtmv2, kdtmv2 DIV kdtmv2, kdtmv2 % kdtmv2, kdtmv2 & kdtmv2, kdtmv2 | kdtmv2, kdtmv2 ^ kdtmv2 from expr_test_not_nullable order by id"""
}