CREATE TABLE IF NOT EXISTS region (
  R_REGIONKEY  INTEGER NOT NULL,
  R_NAME       CHAR(25) NOT NULL,
  R_COMMENT    VARCHAR(152)
)
UNIQUE KEY(R_REGIONKEY)
CLUSTER BY(R_NAME, R_COMMENT)
DISTRIBUTED BY HASH(R_REGIONKEY) BUCKETS 1
PROPERTIES (
  "replication_num" = "1"
)

