// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

suite("nereids_scalar_fn") {
    sql "set enable_nereids_planner=true"
    sql "set enable_fallback_to_original_planner=false"

    sql "select abs(kdbl) from t order by kdbl"
    sql "select abs(kfloat) from t order by kfloat"
    sql "select abs(klint) from t order by klint"
    sql "select abs(kbint) from t order by kbint"
    sql "select abs(ksint) from t order by ksint"
    sql "select abs(kint) from t order by kint"
    sql "select abs(ktint) from t order by ktint"
    sql "select abs(kdcmls1) from t order by kdcmls1"
    sql "select acos(kdbl) from t order by kdbl"
    sql "select aes_decrypt(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select aes_decrypt(kstr, kstr) from t order by kstr, kstr"
    sql "select aes_decrypt(kvchrs1, kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1, kvchrs1"
    sql "select aes_decrypt(kstr, kstr, kstr) from t order by kstr, kstr, kstr"
    sql "select aes_decrypt(kvchrs1, kvchrs1, kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1, kvchrs1, kvchrs1"
    sql "select aes_decrypt(kstr, kstr, kstr, kstr) from t order by kstr, kstr, kstr, kstr"
    sql "select aes_encrypt(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select aes_encrypt(kstr, kstr) from t order by kstr, kstr"
    sql "select aes_encrypt(kvchrs1, kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1, kvchrs1"
    sql "select aes_encrypt(kstr, kstr, kstr) from t order by kstr, kstr, kstr"
    sql "select aes_encrypt(kvchrs1, kvchrs1, kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1, kvchrs1, kvchrs1"
    sql "select aes_encrypt(kstr, kstr, kstr, kstr) from t order by kstr, kstr, kstr, kstr"
    sql "select append_trailing_char_if_absent(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select append_trailing_char_if_absent(kstr, kstr) from t order by kstr, kstr"
    sql "select ascii(kvchrs1) from t order by kvchrs1"
    sql "select ascii(kstr) from t order by kstr"
    sql "select asin(kdbl) from t order by kdbl"
    sql "select atan(kdbl) from t order by kdbl"
    sql "select bin(kbint) from t order by kbint"
    sql "select bit_length(kvchrs1) from t order by kvchrs1"
    sql "select bit_length(kstr) from t order by kstr"
// function bitmap_and(bitmap, bitmap) is unsupported for the test suite.
// function bitmap_and_count(bitmap, bitmap) is unsupported for the test suite.
// function bitmap_and_not(bitmap, bitmap) is unsupported for the test suite.
// function bitmap_and_not_count(bitmap, bitmap) is unsupported for the test suite.
// function bitmap_contains(bitmap, bigint) is unsupported for the test suite.
// function bitmap_count(bitmap) is unsupported for the test suite.
// function bitmap_empty() is unsupported for the test suite.
    sql "select bitmap_from_string(kvchrs1) from t order by kvchrs1"
    sql "select bitmap_from_string(kstr) from t order by kstr"
// function bitmap_has_all(bitmap, bitmap) is unsupported for the test suite.
// function bitmap_has_any(bitmap, bitmap) is unsupported for the test suite.
    sql "select bitmap_hash(kvchrs1) from t order by kvchrs1"
    sql "select bitmap_hash(kstr) from t order by kstr"
    sql "select bitmap_hash64(kvchrs1) from t order by kvchrs1"
    sql "select bitmap_hash64(kstr) from t order by kstr"
// function bitmap_max(bitmap) is unsupported for the test suite.
// function bitmap_min(bitmap) is unsupported for the test suite.
// function bitmap_not(bitmap, bitmap) is unsupported for the test suite.
// function bitmap_or(bitmap, bitmap) is unsupported for the test suite.
// function bitmap_or_count(bitmap, bitmap) is unsupported for the test suite.
// function bitmap_subset_in_range(bitmap, bigint, bigint) is unsupported for the test suite.
// function bitmap_subset_limit(bitmap, bigint, bigint) is unsupported for the test suite.
// function bitmap_to_string(bitmap) is unsupported for the test suite.
// function bitmap_xor(bitmap, bitmap) is unsupported for the test suite.
// function bitmap_xor_count(bitmap, bitmap) is unsupported for the test suite.
    sql "select cbrt(kdbl) from t order by kdbl"
    sql "select ceil(kdbl) from t order by kdbl"
    sql "select ceiling(kdbl) from t order by kdbl"
    sql "select character_length(kvchrs1) from t order by kvchrs1"
    sql "select character_length(kstr) from t order by kstr"
// function coalesce(boolean) is unsupported for the test suite.
    sql "select coalesce(ktint) from t order by ktint"
    sql "select coalesce(ksint) from t order by ksint"
    sql "select coalesce(kint) from t order by kint"
    sql "select coalesce(kbint) from t order by kbint"
    sql "select coalesce(klint) from t order by klint"
    sql "select coalesce(kfloat) from t order by kfloat"
    sql "select coalesce(kdbl) from t order by kdbl"
    sql "select coalesce(kdtm) from t order by kdtm"
    sql "select coalesce(kdt) from t order by kdt"
    sql "select coalesce(kdtmv2s1) from t order by kdtmv2s1"
    sql "select coalesce(kdtv2) from t order by kdtv2"
    sql "select coalesce(kdcmls1) from t order by kdcmls1"
// function coalesce(bitmap) is unsupported for the test suite.
    sql "select coalesce(kvchrs1) from t order by kvchrs1"
    sql "select coalesce(kstr) from t order by kstr"
    sql "select concat(kvchrs1) from t order by kvchrs1"
    sql "select concat(kstr) from t order by kstr"
// function connection_id() is unsupported for the test suite.
    sql "select conv(kbint, ktint, ktint) from t order by kbint, ktint, ktint"
    sql "select conv(kvchrs1, ktint, ktint) from t order by kvchrs1, ktint, ktint"
    sql "select conv(kstr, ktint, ktint) from t order by kstr, ktint, ktint"
    sql "select convert_to(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select convert_tz(kdtm, kvchrs1, kvchrs1) from t order by kdtm, kvchrs1, kvchrs1"
    sql "select convert_tz(kdtmv2s1, kvchrs1, kvchrs1) from t order by kdtmv2s1, kvchrs1, kvchrs1"
    sql "select convert_tz(kdtv2, kvchrs1, kvchrs1) from t order by kdtv2, kvchrs1, kvchrs1"
    sql "select cos(kdbl) from t order by kdbl"
// function current_date() is unsupported for the test suite.
// function current_time() is unsupported for the test suite.
// function current_timestamp() is unsupported for the test suite.
    sql "select current_timestamp(kint) from t order by kint"
// function current_user() is unsupported for the test suite.
// function curtime() is unsupported for the test suite.
// function database() is unsupported for the test suite.
    sql "select date(kdtm) from t order by kdtm"
    sql "select date(kdtmv2s1) from t order by kdtmv2s1"
    sql "select date_diff(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select date_diff(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select date_diff(kdtmv2s1, kdtv2) from t order by kdtmv2s1, kdtv2"
    sql "select date_diff(kdtv2, kdtmv2s1) from t order by kdtv2, kdtmv2s1"
    sql "select date_diff(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select date_diff(kdtmv2s1, kdtm) from t order by kdtmv2s1, kdtm"
    sql "select date_diff(kdtv2, kdtm) from t order by kdtv2, kdtm"
    sql "select date_format(kdtm, kvchrs1) from t order by kdtm, kvchrs1"
    sql "select date_format(kdt, kvchrs1) from t order by kdt, kvchrs1"
    sql "select date_format(kdtmv2s1, kvchrs1) from t order by kdtmv2s1, kvchrs1"
    sql "select date_format(kdtv2, kvchrs1) from t order by kdtv2, kvchrs1"
    sql "select date_trunc(kdtm, kvchrs1) from t order by kdtm, kvchrs1"
    sql "select date_trunc(kdtmv2s1, kvchrs1) from t order by kdtmv2s1, kvchrs1"
    sql "select date_v2(kdtmv2s1) from t order by kdtmv2s1"
    sql "select day(kdtm) from t order by kdtm"
    sql "select day(kdtmv2s1) from t order by kdtmv2s1"
    sql "select day(kdtv2) from t order by kdtv2"
    sql "select day_ceil(kdtm) from t order by kdtm"
    sql "select day_ceil(kdtmv2s1) from t order by kdtmv2s1"
    sql "select day_ceil(kdtv2) from t order by kdtv2"
    sql "select day_ceil(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select day_ceil(kdtm, kint) from t order by kdtm, kint"
    sql "select day_ceil(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select day_ceil(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select day_ceil(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select day_ceil(kdtv2, kint) from t order by kdtv2, kint"
    sql "select day_ceil(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select day_ceil(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select day_ceil(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select day_floor(kdtm) from t order by kdtm"
    sql "select day_floor(kdtmv2s1) from t order by kdtmv2s1"
    sql "select day_floor(kdtv2) from t order by kdtv2"
    sql "select day_floor(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select day_floor(kdtm, kint) from t order by kdtm, kint"
    sql "select day_floor(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select day_floor(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select day_floor(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select day_floor(kdtv2, kint) from t order by kdtv2, kint"
    sql "select day_floor(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select day_floor(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select day_floor(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select day_name(kdtm) from t order by kdtm"
    sql "select day_name(kdtmv2s1) from t order by kdtmv2s1"
    sql "select day_name(kdtv2) from t order by kdtv2"
    sql "select day_of_month(kdtm) from t order by kdtm"
    sql "select day_of_month(kdtmv2s1) from t order by kdtmv2s1"
    sql "select day_of_month(kdtv2) from t order by kdtv2"
    sql "select day_of_week(kdtm) from t order by kdtm"
    sql "select day_of_week(kdtmv2s1) from t order by kdtmv2s1"
    sql "select day_of_week(kdtv2) from t order by kdtv2"
    sql "select day_of_year(kdtm) from t order by kdtm"
    sql "select day_of_year(kdtmv2s1) from t order by kdtmv2s1"
    sql "select day_of_year(kdtv2) from t order by kdtv2"
    sql "select days_add(kdtm, kint) from t order by kdtm, kint"
    sql "select days_add(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select days_add(kdt, kint) from t order by kdt, kint"
    sql "select days_add(kdtv2, kint) from t order by kdtv2, kint"
    sql "select days_diff(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select days_diff(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select days_diff(kdtv2, kdtmv2s1) from t order by kdtv2, kdtmv2s1"
    sql "select days_diff(kdtmv2s1, kdtv2) from t order by kdtmv2s1, kdtv2"
    sql "select days_diff(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select days_diff(kdtv2, kdtm) from t order by kdtv2, kdtm"
    sql "select days_diff(kdtm, kdtv2) from t order by kdtm, kdtv2"
    sql "select days_diff(kdtmv2s1, kdtm) from t order by kdtmv2s1, kdtm"
    sql "select days_diff(kdtm, kdtmv2s1) from t order by kdtm, kdtmv2s1"
    sql "select days_sub(kdtm, kint) from t order by kdtm, kint"
    sql "select days_sub(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select days_sub(kdt, kint) from t order by kdt, kint"
    sql "select days_sub(kdtv2, kint) from t order by kdtv2, kint"
    sql "select dceil(kdbl) from t order by kdbl"
    sql "select degrees(kdbl) from t order by kdbl"
    sql "select dexp(kdbl) from t order by kdbl"
    sql "select dfloor(kdbl) from t order by kdbl"
    sql "select digital_masking(kbint) from t order by kbint"
    sql "select dlog1(kdbl) from t order by kdbl"
    sql "select dlog10(kdbl) from t order by kdbl"
    sql "select domain(kstr) from t order by kstr"
    sql "select domain_without_www(kstr) from t order by kstr"
    sql "select dpow(kdbl, kdbl) from t order by kdbl, kdbl"
    sql "select dround(kdbl) from t order by kdbl"
    sql "select dround(kdbl, kint) from t order by kdbl, kint"
    sql "select dsqrt(kdbl) from t order by kdbl"
// function e() is unsupported for the test suite.
    sql "select elt(kint, kvchrs1) from t order by kint, kvchrs1"
    sql "select elt(kint, kstr) from t order by kint, kstr"
    sql "select ends_with(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select ends_with(kstr, kstr) from t order by kstr, kstr"
    sql "select es_query(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select exp(kdbl) from t order by kdbl"
    sql "select extract_url_parameter(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select field(ktint) from t order by ktint"
    sql "select field(ksint) from t order by ksint"
    sql "select field(kint) from t order by kint"
    sql "select field(kbint) from t order by kbint"
    sql "select field(klint) from t order by klint"
    sql "select field(kfloat) from t order by kfloat"
    sql "select field(kdbl) from t order by kdbl"
    sql "select field(kdcmls1) from t order by kdcmls1"
    sql "select field(kdtv2) from t order by kdtv2"
    sql "select field(kdtmv2s1) from t order by kdtmv2s1"
    sql "select field(kvchrs1) from t order by kvchrs1"
    sql "select field(kstr) from t order by kstr"
    sql "select find_in_set(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select find_in_set(kstr, kstr) from t order by kstr, kstr"
    sql "select floor(kdbl) from t order by kdbl"
    sql "select fmod(kfloat, kfloat) from t order by kfloat, kfloat"
    sql "select fmod(kdbl, kdbl) from t order by kdbl, kdbl"
    sql "select fpow(kdbl, kdbl) from t order by kdbl, kdbl"
    sql "select from_base64(kvchrs1) from t order by kvchrs1"
    sql "select from_base64(kstr) from t order by kstr"
    sql "select from_days(kint) from t order by kint"
    sql "select from_unixtime(kint) from t order by kint"
    sql "select from_unixtime(kint, kvchrs1) from t order by kint, kvchrs1"
    sql "select from_unixtime(kint, kstr) from t order by kint, kstr"
    sql "select get_json_double(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select get_json_double(kstr, kstr) from t order by kstr, kstr"
    sql "select get_json_int(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select get_json_int(kstr, kstr) from t order by kstr, kstr"
    sql "select get_json_string(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select get_json_string(kstr, kstr) from t order by kstr, kstr"
    sql "select greatest(ktint) from t order by ktint"
    sql "select greatest(ksint) from t order by ksint"
    sql "select greatest(kint) from t order by kint"
    sql "select greatest(kbint) from t order by kbint"
    sql "select greatest(klint) from t order by klint"
    sql "select greatest(kfloat) from t order by kfloat"
    sql "select greatest(kdbl) from t order by kdbl"
    sql "select greatest(kdcmls1) from t order by kdcmls1"
    sql "select greatest(kdtm) from t order by kdtm"
    sql "select greatest(kdtmv2s1) from t order by kdtmv2s1"
    sql "select greatest(kvchrs1) from t order by kvchrs1"
    sql "select greatest(kstr) from t order by kstr"
    sql "select hex(kbint) from t order by kbint"
    sql "select hex(kvchrs1) from t order by kvchrs1"
    sql "select hex(kstr) from t order by kstr"
// function hll_cardinality(hll) is unsupported for the test suite.
// function hll_empty() is unsupported for the test suite.
    sql "select hll_hash(kvchrs1) from t order by kvchrs1"
    sql "select hll_hash(kstr) from t order by kstr"
    sql "select hour(kdtm) from t order by kdtm"
    sql "select hour(kdtmv2s1) from t order by kdtmv2s1"
    sql "select hour(kdtv2) from t order by kdtv2"
    sql "select hour_ceil(kdtm) from t order by kdtm"
    sql "select hour_ceil(kdtmv2s1) from t order by kdtmv2s1"
    sql "select hour_ceil(kdtv2) from t order by kdtv2"
    sql "select hour_ceil(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select hour_ceil(kdtm, kint) from t order by kdtm, kint"
    sql "select hour_ceil(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select hour_ceil(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select hour_ceil(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select hour_ceil(kdtv2, kint) from t order by kdtv2, kint"
    sql "select hour_ceil(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select hour_ceil(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select hour_ceil(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select hour_floor(kdtm) from t order by kdtm"
    sql "select hour_floor(kdtmv2s1) from t order by kdtmv2s1"
    sql "select hour_floor(kdtv2) from t order by kdtv2"
    sql "select hour_floor(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select hour_floor(kdtm, kint) from t order by kdtm, kint"
    sql "select hour_floor(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select hour_floor(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select hour_floor(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select hour_floor(kdtv2, kint) from t order by kdtv2, kint"
    sql "select hour_floor(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select hour_floor(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select hour_floor(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select hours_add(kdtm, kint) from t order by kdtm, kint"
    sql "select hours_add(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select hours_add(kdt, kint) from t order by kdt, kint"
    sql "select hours_add(kdtv2, kint) from t order by kdtv2, kint"
    sql "select hours_diff(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select hours_diff(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select hours_diff(kdtv2, kdtmv2s1) from t order by kdtv2, kdtmv2s1"
    sql "select hours_diff(kdtmv2s1, kdtv2) from t order by kdtmv2s1, kdtv2"
    sql "select hours_diff(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select hours_diff(kdtv2, kdtm) from t order by kdtv2, kdtm"
    sql "select hours_diff(kdtm, kdtv2) from t order by kdtm, kdtv2"
    sql "select hours_diff(kdtmv2s1, kdtm) from t order by kdtmv2s1, kdtm"
    sql "select hours_diff(kdtm, kdtmv2s1) from t order by kdtm, kdtmv2s1"
    sql "select hours_sub(kdtm, kint) from t order by kdtm, kint"
    sql "select hours_sub(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select hours_sub(kdt, kint) from t order by kdt, kint"
    sql "select hours_sub(kdtv2, kint) from t order by kdtv2, kint"
    sql "select initcap(kvchrs1) from t order by kvchrs1"
    sql "select instr(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select instr(kstr, kstr) from t order by kstr, kstr"
    sql "select json_array(kvchrs1) from t order by kvchrs1"
    sql "select json_object(kvchrs1) from t order by kvchrs1"
    sql "select json_quote(kvchrs1) from t order by kvchrs1"
// function jsonb_exists_path(json, varchar) is unsupported for the test suite.
// function jsonb_exists_path(json, string) is unsupported for the test suite.
// function jsonb_extract(json, varchar) is unsupported for the test suite.
// function jsonb_extract(json, string) is unsupported for the test suite.
// function jsonb_extract_bigint(json, varchar) is unsupported for the test suite.
// function jsonb_extract_bigint(json, string) is unsupported for the test suite.
// function jsonb_extract_bool(json, varchar) is unsupported for the test suite.
// function jsonb_extract_bool(json, string) is unsupported for the test suite.
// function jsonb_extract_double(json, varchar) is unsupported for the test suite.
// function jsonb_extract_double(json, string) is unsupported for the test suite.
// function jsonb_extract_int(json, varchar) is unsupported for the test suite.
// function jsonb_extract_int(json, string) is unsupported for the test suite.
// function jsonb_extract_isnull(json, varchar) is unsupported for the test suite.
// function jsonb_extract_isnull(json, string) is unsupported for the test suite.
// function jsonb_extract_string(json, varchar) is unsupported for the test suite.
// function jsonb_extract_string(json, string) is unsupported for the test suite.
    sql "select jsonb_parse(kvchrs1) from t order by kvchrs1"
    sql "select jsonb_parse_error_to_invalid(kvchrs1) from t order by kvchrs1"
    sql "select jsonb_parse_error_to_null(kvchrs1) from t order by kvchrs1"
    sql "select jsonb_parse_error_to_value(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select jsonb_parse_notnull(kvchrs1) from t order by kvchrs1"
    sql "select jsonb_parse_notnull_error_to_invalid(kvchrs1) from t order by kvchrs1"
    sql "select jsonb_parse_notnull_error_to_value(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select jsonb_parse_nullable(kvchrs1) from t order by kvchrs1"
    sql "select jsonb_parse_nullable_error_to_invalid(kvchrs1) from t order by kvchrs1"
    sql "select jsonb_parse_nullable_error_to_null(kvchrs1) from t order by kvchrs1"
    sql "select jsonb_parse_nullable_error_to_value(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
// function jsonb_type(json, string) is unsupported for the test suite.
    sql "select last_day(kdtm) from t order by kdtm"
    sql "select last_day(kdt) from t order by kdt"
    sql "select last_day(kdtmv2s1) from t order by kdtmv2s1"
    sql "select last_day(kdtv2) from t order by kdtv2"
    sql "select least(ktint) from t order by ktint"
    sql "select least(ksint) from t order by ksint"
    sql "select least(kint) from t order by kint"
    sql "select least(kbint) from t order by kbint"
    sql "select least(klint) from t order by klint"
    sql "select least(kfloat) from t order by kfloat"
    sql "select least(kdbl) from t order by kdbl"
    sql "select least(kdtm) from t order by kdtm"
    sql "select least(kdcmls1) from t order by kdcmls1"
    sql "select least(kvchrs1) from t order by kvchrs1"
    sql "select least(kstr) from t order by kstr"
    sql "select left(kvchrs1, kint) from t order by kvchrs1, kint"
    sql "select left(kstr, kint) from t order by kstr, kint"
    sql "select length(kvchrs1) from t order by kvchrs1"
    sql "select length(kstr) from t order by kstr"
    sql "select ln(kdbl) from t order by kdbl"
// function local_time() is unsupported for the test suite.
    sql "select local_time(kint) from t order by kint"
// function local_timestamp() is unsupported for the test suite.
    sql "select local_timestamp(kint) from t order by kint"
    sql "select locate(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select locate(kstr, kstr) from t order by kstr, kstr"
    sql "select locate(kvchrs1, kvchrs1, kint) from t order by kvchrs1, kvchrs1, kint"
    sql "select locate(kstr, kstr, kint) from t order by kstr, kstr, kint"
    sql "select log(kdbl, kdbl) from t order by kdbl, kdbl"
    sql "select log10(kdbl) from t order by kdbl"
    sql "select log2(kdbl) from t order by kdbl"
    sql "select lower(kvchrs1) from t order by kvchrs1"
    sql "select lower(kstr) from t order by kstr"
    sql "select lpad(kvchrs1, kint, kvchrs1) from t order by kvchrs1, kint, kvchrs1"
    sql "select lpad(kstr, kint, kstr) from t order by kstr, kint, kstr"
    sql "select ltrim(kvchrs1) from t order by kvchrs1"
    sql "select ltrim(kstr) from t order by kstr"
    sql "select make_date(kint, kint) from t order by kint, kint"
    sql "select mask(kvchrs1) from t order by kvchrs1"
    sql "select mask(kstr) from t order by kstr"
    sql "select mask_first_n(kvchrs1) from t order by kvchrs1"
    sql "select mask_first_n(kstr) from t order by kstr"
    sql "select mask_first_n(kvchrs1, kint) from t order by kvchrs1, kint"
    sql "select mask_first_n(kstr, kint) from t order by kstr, kint"
    sql "select mask_last_n(kvchrs1) from t order by kvchrs1"
    sql "select mask_last_n(kstr) from t order by kstr"
    sql "select mask_last_n(kvchrs1, kint) from t order by kvchrs1, kint"
    sql "select mask_last_n(kstr, kint) from t order by kstr, kint"
    sql "select md5(kvchrs1) from t order by kvchrs1"
    sql "select md5(kstr) from t order by kstr"
    sql "select md5_sum(kvchrs1) from t order by kvchrs1"
    sql "select md5_sum(kstr) from t order by kstr"
    sql "select minute(kdtm) from t order by kdtm"
    sql "select minute(kdtmv2s1) from t order by kdtmv2s1"
    sql "select minute(kdtv2) from t order by kdtv2"
    sql "select minute_ceil(kdtm) from t order by kdtm"
    sql "select minute_ceil(kdtmv2s1) from t order by kdtmv2s1"
    sql "select minute_ceil(kdtv2) from t order by kdtv2"
    sql "select minute_ceil(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select minute_ceil(kdtm, kint) from t order by kdtm, kint"
    sql "select minute_ceil(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select minute_ceil(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select minute_ceil(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select minute_ceil(kdtv2, kint) from t order by kdtv2, kint"
    sql "select minute_ceil(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select minute_ceil(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select minute_ceil(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select minute_floor(kdtm) from t order by kdtm"
    sql "select minute_floor(kdtmv2s1) from t order by kdtmv2s1"
    sql "select minute_floor(kdtv2) from t order by kdtv2"
    sql "select minute_floor(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select minute_floor(kdtm, kint) from t order by kdtm, kint"
    sql "select minute_floor(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select minute_floor(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select minute_floor(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select minute_floor(kdtv2, kint) from t order by kdtv2, kint"
    sql "select minute_floor(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select minute_floor(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select minute_floor(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select minutes_add(kdtm, kint) from t order by kdtm, kint"
    sql "select minutes_add(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select minutes_add(kdt, kint) from t order by kdt, kint"
    sql "select minutes_add(kdtv2, kint) from t order by kdtv2, kint"
    sql "select minutes_diff(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select minutes_diff(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select minutes_diff(kdtv2, kdtmv2s1) from t order by kdtv2, kdtmv2s1"
    sql "select minutes_diff(kdtmv2s1, kdtv2) from t order by kdtmv2s1, kdtv2"
    sql "select minutes_diff(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select minutes_diff(kdtv2, kdtm) from t order by kdtv2, kdtm"
    sql "select minutes_diff(kdtm, kdtv2) from t order by kdtm, kdtv2"
    sql "select minutes_diff(kdtmv2s1, kdtm) from t order by kdtmv2s1, kdtm"
    sql "select minutes_diff(kdtm, kdtmv2s1) from t order by kdtm, kdtmv2s1"
    sql "select minutes_sub(kdtm, kint) from t order by kdtm, kint"
    sql "select minutes_sub(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select minutes_sub(kdt, kint) from t order by kdt, kint"
    sql "select minutes_sub(kdtv2, kint) from t order by kdtv2, kint"
    sql "select money_format(kbint) from t order by kbint"
    sql "select money_format(klint) from t order by klint"
    sql "select money_format(kdbl) from t order by kdbl"
    sql "select money_format(kdcmls1) from t order by kdcmls1"
    sql "select month(kdtm) from t order by kdtm"
    sql "select month(kdtmv2s1) from t order by kdtmv2s1"
    sql "select month(kdtv2) from t order by kdtv2"
    sql "select month_ceil(kdtm) from t order by kdtm"
    sql "select month_ceil(kdtmv2s1) from t order by kdtmv2s1"
    sql "select month_ceil(kdtv2) from t order by kdtv2"
    sql "select month_ceil(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select month_ceil(kdtm, kint) from t order by kdtm, kint"
    sql "select month_ceil(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select month_ceil(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select month_ceil(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select month_ceil(kdtv2, kint) from t order by kdtv2, kint"
    sql "select month_ceil(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select month_ceil(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select month_ceil(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select month_floor(kdtm) from t order by kdtm"
    sql "select month_floor(kdtmv2s1) from t order by kdtmv2s1"
    sql "select month_floor(kdtv2) from t order by kdtv2"
    sql "select month_floor(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select month_floor(kdtm, kint) from t order by kdtm, kint"
    sql "select month_floor(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select month_floor(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select month_floor(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select month_floor(kdtv2, kint) from t order by kdtv2, kint"
    sql "select month_floor(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select month_floor(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select month_floor(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select month_name(kdtm) from t order by kdtm"
    sql "select month_name(kdtmv2s1) from t order by kdtmv2s1"
    sql "select month_name(kdtv2) from t order by kdtv2"
    sql "select months_add(kdtm, kint) from t order by kdtm, kint"
    sql "select months_add(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select months_add(kdt, kint) from t order by kdt, kint"
    sql "select months_add(kdtv2, kint) from t order by kdtv2, kint"
    sql "select months_diff(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select months_diff(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select months_diff(kdtv2, kdtmv2s1) from t order by kdtv2, kdtmv2s1"
    sql "select months_diff(kdtmv2s1, kdtv2) from t order by kdtmv2s1, kdtv2"
    sql "select months_diff(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select months_diff(kdtv2, kdtm) from t order by kdtv2, kdtm"
    sql "select months_diff(kdtm, kdtv2) from t order by kdtm, kdtv2"
    sql "select months_diff(kdtmv2s1, kdtm) from t order by kdtmv2s1, kdtm"
    sql "select months_diff(kdtm, kdtmv2s1) from t order by kdtm, kdtmv2s1"
    sql "select months_sub(kdtm, kint) from t order by kdtm, kint"
    sql "select months_sub(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select months_sub(kdt, kint) from t order by kdt, kint"
    sql "select months_sub(kdtv2, kint) from t order by kdtv2, kint"
    sql "select murmur_hash332(kvchrs1) from t order by kvchrs1"
    sql "select murmur_hash332(kstr) from t order by kstr"
    sql "select murmur_hash364(kvchrs1) from t order by kvchrs1"
    sql "select murmur_hash364(kstr) from t order by kstr"
    sql "select negative(kbint) from t order by kbint"
    sql "select negative(kdbl) from t order by kdbl"
    sql "select negative(kdcmls1) from t order by kdcmls1"
    sql "select not_null_or_empty(kvchrs1) from t order by kvchrs1"
    sql "select not_null_or_empty(kstr) from t order by kstr"
// function now() is unsupported for the test suite.
    sql "select now(kint) from t order by kint"
// function null_if(boolean, boolean) is unsupported for the test suite.
    sql "select null_if(ktint, ktint) from t order by ktint, ktint"
    sql "select null_if(ksint, ksint) from t order by ksint, ksint"
    sql "select null_if(kint, kint) from t order by kint, kint"
    sql "select null_if(kbint, kbint) from t order by kbint, kbint"
    sql "select null_if(klint, klint) from t order by klint, klint"
    sql "select null_if(kfloat, kfloat) from t order by kfloat, kfloat"
    sql "select null_if(kdbl, kdbl) from t order by kdbl, kdbl"
    sql "select null_if(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select null_if(kdt, kdt) from t order by kdt, kdt"
    sql "select null_if(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select null_if(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select null_if(kdcmls1, kdcmls1) from t order by kdcmls1, kdcmls1"
    sql "select null_if(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select null_if(kstr, kstr) from t order by kstr, kstr"
    sql "select null_or_empty(kvchrs1) from t order by kvchrs1"
    sql "select null_or_empty(kstr) from t order by kstr"
// function nvl(boolean, boolean) is unsupported for the test suite.
    sql "select nvl(ktint, ktint) from t order by ktint, ktint"
    sql "select nvl(ksint, ksint) from t order by ksint, ksint"
    sql "select nvl(kint, kint) from t order by kint, kint"
    sql "select nvl(kbint, kbint) from t order by kbint, kbint"
    sql "select nvl(klint, klint) from t order by klint, klint"
    sql "select nvl(kfloat, kfloat) from t order by kfloat, kfloat"
    sql "select nvl(kdbl, kdbl) from t order by kdbl, kdbl"
    sql "select nvl(kdt, kdt) from t order by kdt, kdt"
    sql "select nvl(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select nvl(kdt, kdtm) from t order by kdt, kdtm"
    sql "select nvl(kdtm, kdt) from t order by kdtm, kdt"
    sql "select nvl(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select nvl(kdtv2, kdtmv2s1) from t order by kdtv2, kdtmv2s1"
    sql "select nvl(kdtmv2s1, kdtv2) from t order by kdtmv2s1, kdtv2"
    sql "select nvl(kdcmls1, kdcmls1) from t order by kdcmls1, kdcmls1"
// function nvl(bitmap, bitmap) is unsupported for the test suite.
    sql "select nvl(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select nvl(kstr, kstr) from t order by kstr, kstr"
    sql "select parse_url(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select parse_url(kstr, kstr) from t order by kstr, kstr"
    sql "select parse_url(kvchrs1, kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1, kvchrs1"
    sql "select parse_url(kstr, kstr, kstr) from t order by kstr, kstr, kstr"
// function pi() is unsupported for the test suite.
    sql "select pmod(kbint, kbint) from t order by kbint, kbint"
    sql "select pmod(kdbl, kdbl) from t order by kdbl, kdbl"
    sql "select positive(kbint) from t order by kbint"
    sql "select positive(kdbl) from t order by kdbl"
    sql "select positive(kdcmls1) from t order by kdcmls1"
    sql "select pow(kdbl, kdbl) from t order by kdbl, kdbl"
    sql "select power(kdbl, kdbl) from t order by kdbl, kdbl"
    sql "select protocol(kstr) from t order by kstr"
// function quantile_percent(quantilestate, float) is unsupported for the test suite.
    sql "select quarter(kdtm) from t order by kdtm"
    sql "select quarter(kdtmv2s1) from t order by kdtmv2s1"
    sql "select quarter(kdtv2) from t order by kdtv2"
    sql "select radians(kdbl) from t order by kdbl"
// function random() is unsupported for the test suite.
    sql "select random(kbint) from t order by kbint"
    sql "select regexp_extract(kvchrs1, kvchrs1, kbint) from t order by kvchrs1, kvchrs1, kbint"
    sql "select regexp_extract(kstr, kstr, kbint) from t order by kstr, kstr, kbint"
    sql "select regexp_extract_all(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select regexp_extract_all(kstr, kstr) from t order by kstr, kstr"
    sql "select regexp_replace(kvchrs1, kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1, kvchrs1"
    sql "select regexp_replace(kstr, kstr, kstr) from t order by kstr, kstr, kstr"
    sql "select regexp_replace_one(kvchrs1, kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1, kvchrs1"
    sql "select regexp_replace_one(kstr, kstr, kstr) from t order by kstr, kstr, kstr"
    sql "select repeat(kvchrs1, kint) from t order by kvchrs1, kint"
    sql "select repeat(kstr, kint) from t order by kstr, kint"
    sql "select replace(kvchrs1, kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1, kvchrs1"
    sql "select replace(kstr, kstr, kstr) from t order by kstr, kstr, kstr"
    sql "select right(kvchrs1, kint) from t order by kvchrs1, kint"
    sql "select right(kstr, kint) from t order by kstr, kint"
    sql "select round(kdbl) from t order by kdbl"
    sql "select round(kdbl, kint) from t order by kdbl, kint"
    sql "select round_bankers(kdbl) from t order by kdbl"
    sql "select round_bankers(kdbl, kint) from t order by kdbl, kint"
    sql "select rpad(kvchrs1, kint, kvchrs1) from t order by kvchrs1, kint, kvchrs1"
    sql "select rpad(kstr, kint, kstr) from t order by kstr, kint, kstr"
    sql "select rtrim(kvchrs1) from t order by kvchrs1"
    sql "select rtrim(kstr) from t order by kstr"
    sql "select running_difference(ktint) from t order by ktint"
    sql "select running_difference(ksint) from t order by ksint"
    sql "select running_difference(kint) from t order by kint"
    sql "select running_difference(kbint) from t order by kbint"
    sql "select running_difference(klint) from t order by klint"
    sql "select running_difference(kfloat) from t order by kfloat"
    sql "select running_difference(kdbl) from t order by kdbl"
    sql "select running_difference(kdcmls1) from t order by kdcmls1"
// function running_difference(decimalv3.defaultdecimal32) is unsupported for the test suite.
// function running_difference(decimalv3.defaultdecimal64) is unsupported for the test suite.
// function running_difference(decimalv3.defaultdecimal128) is unsupported for the test suite.
    sql "select running_difference(kdt) from t order by kdt"
    sql "select running_difference(kdtv2) from t order by kdtv2"
    sql "select running_difference(kdtm) from t order by kdtm"
    sql "select running_difference(kdtmv2s1) from t order by kdtmv2s1"
    sql "select second(kdtm) from t order by kdtm"
    sql "select second(kdtmv2s1) from t order by kdtmv2s1"
    sql "select second(kdtv2) from t order by kdtv2"
    sql "select second_ceil(kdtm) from t order by kdtm"
    sql "select second_ceil(kdtmv2s1) from t order by kdtmv2s1"
    sql "select second_ceil(kdtv2) from t order by kdtv2"
    sql "select second_ceil(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select second_ceil(kdtm, kint) from t order by kdtm, kint"
    sql "select second_ceil(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select second_ceil(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select second_ceil(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select second_ceil(kdtv2, kint) from t order by kdtv2, kint"
    sql "select second_ceil(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select second_ceil(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select second_ceil(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select second_floor(kdtm) from t order by kdtm"
    sql "select second_floor(kdtmv2s1) from t order by kdtmv2s1"
    sql "select second_floor(kdtv2) from t order by kdtv2"
    sql "select second_floor(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select second_floor(kdtm, kint) from t order by kdtm, kint"
    sql "select second_floor(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select second_floor(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select second_floor(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select second_floor(kdtv2, kint) from t order by kdtv2, kint"
    sql "select second_floor(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select second_floor(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select second_floor(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select seconds_add(kdtm, kint) from t order by kdtm, kint"
    sql "select seconds_add(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select seconds_add(kdt, kint) from t order by kdt, kint"
    sql "select seconds_add(kdtv2, kint) from t order by kdtv2, kint"
    sql "select seconds_diff(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select seconds_diff(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select seconds_diff(kdtv2, kdtmv2s1) from t order by kdtv2, kdtmv2s1"
    sql "select seconds_diff(kdtmv2s1, kdtv2) from t order by kdtmv2s1, kdtv2"
    sql "select seconds_diff(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select seconds_diff(kdtv2, kdtm) from t order by kdtv2, kdtm"
    sql "select seconds_diff(kdtm, kdtv2) from t order by kdtm, kdtv2"
    sql "select seconds_diff(kdtmv2s1, kdtm) from t order by kdtmv2s1, kdtm"
    sql "select seconds_diff(kdtm, kdtmv2s1) from t order by kdtm, kdtmv2s1"
    sql "select seconds_sub(kdtm, kint) from t order by kdtm, kint"
    sql "select seconds_sub(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select seconds_sub(kdt, kint) from t order by kdt, kint"
    sql "select seconds_sub(kdtv2, kint) from t order by kdtv2, kint"
    sql "select sign(kdbl) from t order by kdbl"
    sql "select sin(kdbl) from t order by kdbl"
    sql "select sleep(kint) from t order by kint"
    sql "select sm3(kvchrs1) from t order by kvchrs1"
    sql "select sm3(kstr) from t order by kstr"
    sql "select sm3sum(kvchrs1) from t order by kvchrs1"
    sql "select sm3sum(kstr) from t order by kstr"
    sql "select sm4_decrypt(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select sm4_decrypt(kstr, kstr) from t order by kstr, kstr"
    sql "select sm4_decrypt(kvchrs1, kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1, kvchrs1"
    sql "select sm4_decrypt(kstr, kstr, kstr) from t order by kstr, kstr, kstr"
    sql "select sm4_decrypt(kvchrs1, kvchrs1, kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1, kvchrs1, kvchrs1"
    sql "select sm4_decrypt(kstr, kstr, kstr, kstr) from t order by kstr, kstr, kstr, kstr"
    sql "select sm4_encrypt(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select sm4_encrypt(kstr, kstr) from t order by kstr, kstr"
    sql "select sm4_encrypt(kvchrs1, kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1, kvchrs1"
    sql "select sm4_encrypt(kstr, kstr, kstr) from t order by kstr, kstr, kstr"
    sql "select sm4_encrypt(kvchrs1, kvchrs1, kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1, kvchrs1, kvchrs1"
    sql "select sm4_encrypt(kstr, kstr, kstr, kstr) from t order by kstr, kstr, kstr, kstr"
    sql "select space(kint) from t order by kint"
    sql "select split_part(kvchrs1, kvchrs1, kint) from t order by kvchrs1, kvchrs1, kint"
    sql "select split_part(kstr, kstr, kint) from t order by kstr, kstr, kint"
    sql "select sqrt(kdbl) from t order by kdbl"
    sql "select st_astext(kvchrs1) from t order by kvchrs1"
    sql "select st_astext(kstr) from t order by kstr"
    sql "select st_aswkt(kvchrs1) from t order by kvchrs1"
    sql "select st_aswkt(kstr) from t order by kstr"
    sql "select st_circle(kdbl, kdbl, kdbl) from t order by kdbl, kdbl, kdbl"
    sql "select st_contains(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select st_distance_sphere(kdbl, kdbl, kdbl, kdbl) from t order by kdbl, kdbl, kdbl, kdbl"
    sql "select st_geometryfromtext(kvchrs1) from t order by kvchrs1"
    sql "select st_geometryfromtext(kstr) from t order by kstr"
    sql "select st_geomfromtext(kvchrs1) from t order by kvchrs1"
    sql "select st_geomfromtext(kstr) from t order by kstr"
    sql "select st_linefromtext(kvchrs1) from t order by kvchrs1"
    sql "select st_linefromtext(kstr) from t order by kstr"
    sql "select st_linestringfromtext(kvchrs1) from t order by kvchrs1"
    sql "select st_linestringfromtext(kstr) from t order by kstr"
    sql "select st_point(kdbl, kdbl) from t order by kdbl, kdbl"
    sql "select st_polyfromtext(kvchrs1) from t order by kvchrs1"
    sql "select st_polyfromtext(kstr) from t order by kstr"
    sql "select st_polygon(kvchrs1) from t order by kvchrs1"
    sql "select st_polygon(kstr) from t order by kstr"
    sql "select st_polygonfromtext(kvchrs1) from t order by kvchrs1"
    sql "select st_polygonfromtext(kstr) from t order by kstr"
    sql "select st_x(kvchrs1) from t order by kvchrs1"
    sql "select st_x(kstr) from t order by kstr"
    sql "select st_y(kvchrs1) from t order by kvchrs1"
    sql "select st_y(kstr) from t order by kstr"
    sql "select starts_with(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select starts_with(kstr, kstr) from t order by kstr, kstr"
    sql "select str_left(kvchrs1, kint) from t order by kvchrs1, kint"
    sql "select str_left(kstr, kint) from t order by kstr, kint"
    sql "select str_right(kvchrs1, kint) from t order by kvchrs1, kint"
    sql "select str_right(kstr, kint) from t order by kstr, kint"
    sql "select str_to_date(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select str_to_date(kstr, kstr) from t order by kstr, kstr"
// function sub_bitmap(bitmap, bigint, bigint) is unsupported for the test suite.
    sql "select sub_replace(kvchrs1, kvchrs1, kint) from t order by kvchrs1, kvchrs1, kint"
    sql "select sub_replace(kstr, kstr, kint) from t order by kstr, kstr, kint"
    sql "select sub_replace(kvchrs1, kvchrs1, kint, kint) from t order by kvchrs1, kvchrs1, kint, kint"
    sql "select sub_replace(kstr, kstr, kint, kint) from t order by kstr, kstr, kint, kint"
    sql "select substring(kvchrs1, kint) from t order by kvchrs1, kint"
    sql "select substring(kstr, kint) from t order by kstr, kint"
    sql "select substring(kvchrs1, kint, kint) from t order by kvchrs1, kint, kint"
    sql "select substring(kstr, kint, kint) from t order by kstr, kint, kint"
    sql "select substring_index(kvchrs1, kvchrs1, kint) from t order by kvchrs1, kvchrs1, kint"
    sql "select substring_index(kstr, kstr, kint) from t order by kstr, kstr, kint"
    sql "select tan(kdbl) from t order by kdbl"
    sql "select time_diff(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select time_diff(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select time_diff(kdtmv2s1, kdtv2) from t order by kdtmv2s1, kdtv2"
    sql "select time_diff(kdtv2, kdtmv2s1) from t order by kdtv2, kdtmv2s1"
    sql "select time_diff(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select time_diff(kdtmv2s1, kdtm) from t order by kdtmv2s1, kdtm"
    sql "select time_diff(kdtv2, kdtm) from t order by kdtv2, kdtm"
    sql "select timestamp(kdtm) from t order by kdtm"
    sql "select timestamp(kdtmv2s1) from t order by kdtmv2s1"
    sql "select to_base64(kstr) from t order by kstr"
    sql "select to_bitmap(kvchrs1) from t order by kvchrs1"
    sql "select to_bitmap(kstr) from t order by kstr"
    sql "select to_bitmap_with_check(kvchrs1) from t order by kvchrs1"
    sql "select to_bitmap_with_check(kstr) from t order by kstr"
    sql "select to_date(kdtm) from t order by kdtm"
    sql "select to_date(kdtmv2s1) from t order by kdtmv2s1"
    sql "select to_date_v2(kdtmv2s1) from t order by kdtmv2s1"
    sql "select to_days(kdt) from t order by kdt"
    sql "select to_days(kdtv2) from t order by kdtv2"
    sql "select to_monday(kdtmv2s1) from t order by kdtmv2s1"
    sql "select to_monday(kdtv2) from t order by kdtv2"
    sql "select to_monday(kdtm) from t order by kdtm"
    sql "select to_monday(kdt) from t order by kdt"
    sql "select to_quantile_state(kvchrs1, kfloat) from t order by kvchrs1, kfloat"
    sql "select trim(kvchrs1) from t order by kvchrs1"
    sql "select trim(kstr) from t order by kstr"
    sql "select truncate(kdbl, kint) from t order by kdbl, kint"
    sql "select unhex(kvchrs1) from t order by kvchrs1"
    sql "select unhex(kstr) from t order by kstr"
// function unix_timestamp() is unsupported for the test suite.
    sql "select unix_timestamp(kdtm) from t order by kdtm"
    sql "select unix_timestamp(kdt) from t order by kdt"
    sql "select unix_timestamp(kdtmv2s1) from t order by kdtmv2s1"
    sql "select unix_timestamp(kdtv2) from t order by kdtv2"
    sql "select unix_timestamp(kvchrs1, kvchrs1) from t order by kvchrs1, kvchrs1"
    sql "select unix_timestamp(kstr, kstr) from t order by kstr, kstr"
    sql "select upper(kvchrs1) from t order by kvchrs1"
    sql "select upper(kstr) from t order by kstr"
// function user() is unsupported for the test suite.
// function utc_timestamp() is unsupported for the test suite.
// function uuid() is unsupported for the test suite.
// function version() is unsupported for the test suite.
    sql "select week(kdtm) from t order by kdtm"
    sql "select week(kdtmv2s1) from t order by kdtmv2s1"
    sql "select week(kdtv2) from t order by kdtv2"
    sql "select week(kdtm, kint) from t order by kdtm, kint"
    sql "select week(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select week(kdtv2, kint) from t order by kdtv2, kint"
    sql "select week_ceil(kdtm) from t order by kdtm"
    sql "select week_ceil(kdtmv2s1) from t order by kdtmv2s1"
    sql "select week_ceil(kdtv2) from t order by kdtv2"
    sql "select week_ceil(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select week_ceil(kdtm, kint) from t order by kdtm, kint"
    sql "select week_ceil(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select week_ceil(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select week_ceil(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select week_ceil(kdtv2, kint) from t order by kdtv2, kint"
    sql "select week_ceil(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select week_ceil(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select week_ceil(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select week_floor(kdtm) from t order by kdtm"
    sql "select week_floor(kdtmv2s1) from t order by kdtmv2s1"
    sql "select week_floor(kdtv2) from t order by kdtv2"
    sql "select week_floor(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select week_floor(kdtm, kint) from t order by kdtm, kint"
    sql "select week_floor(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select week_floor(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select week_floor(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select week_floor(kdtv2, kint) from t order by kdtv2, kint"
    sql "select week_floor(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select week_floor(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select week_floor(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select week_of_year(kdtm) from t order by kdtm"
    sql "select week_of_year(kdtmv2s1) from t order by kdtmv2s1"
    sql "select week_of_year(kdtv2) from t order by kdtv2"
    sql "select weekday(kdtm) from t order by kdtm"
    sql "select weekday(kdtmv2s1) from t order by kdtmv2s1"
    sql "select weekday(kdtv2) from t order by kdtv2"
    sql "select weeks_diff(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select weeks_diff(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select weeks_diff(kdtv2, kdtmv2s1) from t order by kdtv2, kdtmv2s1"
    sql "select weeks_diff(kdtmv2s1, kdtv2) from t order by kdtmv2s1, kdtv2"
    sql "select weeks_diff(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select weeks_diff(kdtv2, kdtm) from t order by kdtv2, kdtm"
    sql "select weeks_diff(kdtm, kdtv2) from t order by kdtm, kdtv2"
    sql "select weeks_diff(kdtmv2s1, kdtm) from t order by kdtmv2s1, kdtm"
    sql "select weeks_diff(kdtm, kdtmv2s1) from t order by kdtm, kdtmv2s1"
    sql "select year(kdtv2) from t order by kdtv2"
    sql "select year(kdtm) from t order by kdtm"
    sql "select year(kdtmv2s1) from t order by kdtmv2s1"
    sql "select year_ceil(kdtm) from t order by kdtm"
    sql "select year_ceil(kdtmv2s1) from t order by kdtmv2s1"
    sql "select year_ceil(kdtv2) from t order by kdtv2"
    sql "select year_ceil(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select year_ceil(kdtm, kint) from t order by kdtm, kint"
    sql "select year_ceil(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select year_ceil(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select year_ceil(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select year_ceil(kdtv2, kint) from t order by kdtv2, kint"
    sql "select year_ceil(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select year_ceil(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select year_ceil(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select year_floor(kdtm) from t order by kdtm"
    sql "select year_floor(kdtmv2s1) from t order by kdtmv2s1"
    sql "select year_floor(kdtv2) from t order by kdtv2"
    sql "select year_floor(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select year_floor(kdtm, kint) from t order by kdtm, kint"
    sql "select year_floor(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select year_floor(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select year_floor(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select year_floor(kdtv2, kint) from t order by kdtv2, kint"
    sql "select year_floor(kdtm, kint, kdtm) from t order by kdtm, kint, kdtm"
    sql "select year_floor(kdtmv2s1, kint, kdtmv2s1) from t order by kdtmv2s1, kint, kdtmv2s1"
    sql "select year_floor(kdtv2, kint, kdtv2) from t order by kdtv2, kint, kdtv2"
    sql "select year_week(kdtm) from t order by kdtm"
    sql "select year_week(kdtmv2s1) from t order by kdtmv2s1"
    sql "select year_week(kdtv2) from t order by kdtv2"
    sql "select year_week(kdtm, kint) from t order by kdtm, kint"
    sql "select year_week(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select year_week(kdtv2, kint) from t order by kdtv2, kint"
    sql "select years_add(kdtm, kint) from t order by kdtm, kint"
    sql "select years_add(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select years_add(kdt, kint) from t order by kdt, kint"
    sql "select years_add(kdtv2, kint) from t order by kdtv2, kint"
    sql "select years_diff(kdtm, kdtm) from t order by kdtm, kdtm"
    sql "select years_diff(kdtmv2s1, kdtmv2s1) from t order by kdtmv2s1, kdtmv2s1"
    sql "select years_diff(kdtv2, kdtmv2s1) from t order by kdtv2, kdtmv2s1"
    sql "select years_diff(kdtmv2s1, kdtv2) from t order by kdtmv2s1, kdtv2"
    sql "select years_diff(kdtv2, kdtv2) from t order by kdtv2, kdtv2"
    sql "select years_diff(kdtv2, kdtm) from t order by kdtv2, kdtm"
    sql "select years_diff(kdtm, kdtv2) from t order by kdtm, kdtv2"
    sql "select years_diff(kdtmv2s1, kdtm) from t order by kdtmv2s1, kdtm"
    sql "select years_diff(kdtm, kdtmv2s1) from t order by kdtm, kdtmv2s1"
    sql "select years_sub(kdtm, kint) from t order by kdtm, kint"
    sql "select years_sub(kdtmv2s1, kint) from t order by kdtmv2s1, kint"
    sql "select years_sub(kdt, kint) from t order by kdt, kint"
    sql "select years_sub(kdtv2, kint) from t order by kdtv2, kint"
}
