set sql_dialect='presto';
set enable_fallback_to_original_planner=false;
set debug_skip_fold_constant=false;
-- SELECT INTERVAL '124-30' YEAR TO MONTH;
-- SELECT INTERVAL '124' YEAR TO MONTH;
-- SELECT INTERVAL '30' MONTH;
-- SELECT INTERVAL '32767' YEAR;
-- SELECT INTERVAL '32767' MONTH;
-- SELECT INTERVAL '32767-32767' YEAR TO MONTH
set debug_skip_fold_constant=true;
-- SELECT INTERVAL '124-30' YEAR TO MONTH;
-- SELECT INTERVAL '124' YEAR TO MONTH;
-- SELECT INTERVAL '30' MONTH;
-- SELECT INTERVAL '32767' YEAR;
-- SELECT INTERVAL '32767' MONTH;
-- SELECT INTERVAL '32767-32767' YEAR TO MONTH;