-- SELECT
--     cast(v:repo.name as string),
--     number,
--     count() AS comments,
--     count(distinct cast(v:actor.login as string)) AS authors
-- FROM github_events
-- WHERE cast(v:type as string) = 'IssueCommentEvent' AND (cast(v:payload.action as string) = 'created') AND (number > 10)
-- GROUP BY cast(v:repo.name as string), number
-- HAVING authors >= 10
-- ORDER BY comments DESC
-- LIMIT 50
