// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

suite("nereids_win1_fn") {
	sql 'use regression_test_nereids_function_p0'
	sql 'set enable_nereids_planner=true'
	sql 'set enable_fallback_to_original_planner=false'
	qt_sql_count '''
		select kint, ksint, count(kbint) over() as wf from fn_test order by kint'''
	qt_sql_count_notnull '''
		select kint, ksint, count(kbint) over() as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_1 '''
		select kint, ksint, count(kbint) over(order by kint rows unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_1 '''
		select kint, ksint, count(kbint) over(order by kint rows unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_2 '''
		select kint, ksint, count(kbint) over(order by kint rows 2 preceding) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_2 '''
		select kint, ksint, count(kbint) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_3 '''
		select kint, ksint, count(kbint) over(order by kint rows current row) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_3 '''
		select kint, ksint, count(kbint) over(order by kint rows current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_4 '''
		select kint, ksint, count(kbint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_4 '''
		select kint, ksint, count(kbint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_5 '''
		select kint, ksint, count(kbint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_5 '''
		select kint, ksint, count(kbint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_6 '''
		select kint, ksint, count(kbint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_6 '''
		select kint, ksint, count(kbint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_7 '''
		select kint, ksint, count(kbint) over(order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_7 '''
		select kint, ksint, count(kbint) over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_8 '''
		select kint, ksint, count(kbint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_8 '''
		select kint, ksint, count(kbint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_9 '''
		select kint, ksint, count(kbint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_9 '''
		select kint, ksint, count(kbint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_10 '''
		select kint, ksint, count(kbint) over(order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_10 '''
		select kint, ksint, count(kbint) over(order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_11 '''
		select kint, ksint, count(kbint) over(order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_11 '''
		select kint, ksint, count(kbint) over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_12 '''
		select kint, ksint, count(kbint) over(order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_12 '''
		select kint, ksint, count(kbint) over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_13 '''
		select kint, ksint, count(kbint) over(order by kint range unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_13 '''
		select kint, ksint, count(kbint) over(order by kint range unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_14 '''
		select kint, ksint, count(kbint) over(order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_14 '''
		select kint, ksint, count(kbint) over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_15 '''
		select kint, ksint, count(kbint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_15 '''
		select kint, ksint, count(kbint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_16 '''
		select kint, ksint, count(kbint) over(order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_count_f_notnull_16 '''
		select kint, ksint, count(kbint) over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_pb '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint) as wf from fn_test order by kint'''
	qt_sql_count_pb_notnull '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_1 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_1 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_2 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_2 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_3 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows current row) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_3 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_4 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_4 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_5 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_5 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_6 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_6 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_7 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_7 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_8 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_8 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_9 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_9 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_10 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_10 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_11 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_11 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_12 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_12 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_13 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint range unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_13 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint range unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_14 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_14 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_15 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_15 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_count_f_pb_16 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_count_f_pb_notnull_16 '''
		select kint, ksint, count(kbint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''

	qt_sql_avg '''
		select kint, ksint, avg(kbint) over() as wf from fn_test order by kint'''
	qt_sql_avg_notnull '''
		select kint, ksint, avg(kbint) over() as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_1 '''
		select kint, ksint, avg(kbint) over(order by kint rows unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_1 '''
		select kint, ksint, avg(kbint) over(order by kint rows unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_2 '''
		select kint, ksint, avg(kbint) over(order by kint rows 2 preceding) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_2 '''
		select kint, ksint, avg(kbint) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_3 '''
		select kint, ksint, avg(kbint) over(order by kint rows current row) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_3 '''
		select kint, ksint, avg(kbint) over(order by kint rows current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_4 '''
		select kint, ksint, avg(kbint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_4 '''
		select kint, ksint, avg(kbint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_5 '''
		select kint, ksint, avg(kbint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_5 '''
		select kint, ksint, avg(kbint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_6 '''
		select kint, ksint, avg(kbint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_6 '''
		select kint, ksint, avg(kbint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_7 '''
		select kint, ksint, avg(kbint) over(order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_7 '''
		select kint, ksint, avg(kbint) over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_8 '''
		select kint, ksint, avg(kbint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_8 '''
		select kint, ksint, avg(kbint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_9 '''
		select kint, ksint, avg(kbint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_9 '''
		select kint, ksint, avg(kbint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_10 '''
		select kint, ksint, avg(kbint) over(order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_10 '''
		select kint, ksint, avg(kbint) over(order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_11 '''
		select kint, ksint, avg(kbint) over(order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_11 '''
		select kint, ksint, avg(kbint) over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_12 '''
		select kint, ksint, avg(kbint) over(order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_12 '''
		select kint, ksint, avg(kbint) over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_13 '''
		select kint, ksint, avg(kbint) over(order by kint range unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_13 '''
		select kint, ksint, avg(kbint) over(order by kint range unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_14 '''
		select kint, ksint, avg(kbint) over(order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_14 '''
		select kint, ksint, avg(kbint) over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_15 '''
		select kint, ksint, avg(kbint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_15 '''
		select kint, ksint, avg(kbint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_16 '''
		select kint, ksint, avg(kbint) over(order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_avg_f_notnull_16 '''
		select kint, ksint, avg(kbint) over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_pb '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint) as wf from fn_test order by kint'''
	qt_sql_avg_pb_notnull '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_1 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_1 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_2 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_2 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_3 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows current row) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_3 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_4 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_4 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_5 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_5 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_6 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_6 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_7 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_7 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_8 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_8 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_9 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_9 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_10 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_10 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_11 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_11 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_12 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_12 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_13 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint range unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_13 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint range unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_14 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_14 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_15 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_15 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_avg_f_pb_16 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_avg_f_pb_notnull_16 '''
		select kint, ksint, avg(kbint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''

	qt_sql_min '''
		select kint, ksint, min(kbint) over() as wf from fn_test order by kint'''
	qt_sql_min_notnull '''
		select kint, ksint, min(kbint) over() as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_1 '''
		select kint, ksint, min(kbint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_min_f_notnull_1 '''
		select kint, ksint, min(kbint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_2 '''
		select kint, ksint, min(kbint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_min_f_notnull_2 '''
		select kint, ksint, min(kbint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_3 '''
		select kint, ksint, min(kbint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_min_f_notnull_3 '''
		select kint, ksint, min(kbint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_4 '''
		select kint, ksint, min(kbint) over(order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_min_f_notnull_4 '''
		select kint, ksint, min(kbint) over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_5 '''
		select kint, ksint, min(kbint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_min_f_notnull_5 '''
		select kint, ksint, min(kbint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_6 '''
		select kint, ksint, min(kbint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_min_f_notnull_6 '''
		select kint, ksint, min(kbint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_7 '''
		select kint, ksint, min(kbint) over(order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_min_f_notnull_7 '''
		select kint, ksint, min(kbint) over(order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_8 '''
		select kint, ksint, min(kbint) over(order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_min_f_notnull_8 '''
		select kint, ksint, min(kbint) over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_9 '''
		select kint, ksint, min(kbint) over(order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_min_f_notnull_9 '''
		select kint, ksint, min(kbint) over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_10 '''
		select kint, ksint, min(kbint) over(order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_min_f_notnull_10 '''
		select kint, ksint, min(kbint) over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_11 '''
		select kint, ksint, min(kbint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_min_f_notnull_11 '''
		select kint, ksint, min(kbint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_12 '''
		select kint, ksint, min(kbint) over(order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_min_f_notnull_12 '''
		select kint, ksint, min(kbint) over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_pb '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint) as wf from fn_test order by kint'''
	qt_sql_min_pb_notnull '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_pb_1 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_min_f_pb_notnull_1 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_pb_2 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_min_f_pb_notnull_2 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_pb_3 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_min_f_pb_notnull_3 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_pb_4 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_min_f_pb_notnull_4 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_pb_5 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_min_f_pb_notnull_5 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_pb_6 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_min_f_pb_notnull_6 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_pb_7 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_min_f_pb_notnull_7 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_pb_8 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_min_f_pb_notnull_8 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_pb_9 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_min_f_pb_notnull_9 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_pb_10 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_min_f_pb_notnull_10 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_pb_11 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_min_f_pb_notnull_11 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_min_f_pb_12 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_min_f_pb_notnull_12 '''
		select kint, ksint, min(kbint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''

	qt_sql_max '''
		select kint, ksint, max(kbint) over() as wf from fn_test order by kint'''
	qt_sql_max_notnull '''
		select kint, ksint, max(kbint) over() as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_1 '''
		select kint, ksint, max(kbint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_max_f_notnull_1 '''
		select kint, ksint, max(kbint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_2 '''
		select kint, ksint, max(kbint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_max_f_notnull_2 '''
		select kint, ksint, max(kbint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_3 '''
		select kint, ksint, max(kbint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_max_f_notnull_3 '''
		select kint, ksint, max(kbint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_4 '''
		select kint, ksint, max(kbint) over(order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_max_f_notnull_4 '''
		select kint, ksint, max(kbint) over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_5 '''
		select kint, ksint, max(kbint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_max_f_notnull_5 '''
		select kint, ksint, max(kbint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_6 '''
		select kint, ksint, max(kbint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_max_f_notnull_6 '''
		select kint, ksint, max(kbint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_7 '''
		select kint, ksint, max(kbint) over(order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_max_f_notnull_7 '''
		select kint, ksint, max(kbint) over(order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_8 '''
		select kint, ksint, max(kbint) over(order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_max_f_notnull_8 '''
		select kint, ksint, max(kbint) over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_9 '''
		select kint, ksint, max(kbint) over(order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_max_f_notnull_9 '''
		select kint, ksint, max(kbint) over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_10 '''
		select kint, ksint, max(kbint) over(order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_max_f_notnull_10 '''
		select kint, ksint, max(kbint) over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_11 '''
		select kint, ksint, max(kbint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_max_f_notnull_11 '''
		select kint, ksint, max(kbint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_12 '''
		select kint, ksint, max(kbint) over(order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_max_f_notnull_12 '''
		select kint, ksint, max(kbint) over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_pb '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint) as wf from fn_test order by kint'''
	qt_sql_max_pb_notnull '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_pb_1 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_max_f_pb_notnull_1 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_pb_2 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_max_f_pb_notnull_2 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_pb_3 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_max_f_pb_notnull_3 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_pb_4 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_max_f_pb_notnull_4 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_pb_5 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_max_f_pb_notnull_5 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_pb_6 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_max_f_pb_notnull_6 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_pb_7 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_max_f_pb_notnull_7 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_pb_8 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_max_f_pb_notnull_8 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_pb_9 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_max_f_pb_notnull_9 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_pb_10 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_max_f_pb_notnull_10 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_pb_11 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_max_f_pb_notnull_11 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_max_f_pb_12 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_max_f_pb_notnull_12 '''
		select kint, ksint, max(kbint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''

	qt_sql_sum '''
		select kint, ksint, sum(kbint) over() as wf from fn_test order by kint'''
	qt_sql_sum_notnull '''
		select kint, ksint, sum(kbint) over() as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_1 '''
		select kint, ksint, sum(kbint) over(order by kint rows unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_1 '''
		select kint, ksint, sum(kbint) over(order by kint rows unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_2 '''
		select kint, ksint, sum(kbint) over(order by kint rows 2 preceding) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_2 '''
		select kint, ksint, sum(kbint) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_3 '''
		select kint, ksint, sum(kbint) over(order by kint rows current row) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_3 '''
		select kint, ksint, sum(kbint) over(order by kint rows current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_4 '''
		select kint, ksint, sum(kbint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_4 '''
		select kint, ksint, sum(kbint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_5 '''
		select kint, ksint, sum(kbint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_5 '''
		select kint, ksint, sum(kbint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_6 '''
		select kint, ksint, sum(kbint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_6 '''
		select kint, ksint, sum(kbint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_7 '''
		select kint, ksint, sum(kbint) over(order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_7 '''
		select kint, ksint, sum(kbint) over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_8 '''
		select kint, ksint, sum(kbint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_8 '''
		select kint, ksint, sum(kbint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_9 '''
		select kint, ksint, sum(kbint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_9 '''
		select kint, ksint, sum(kbint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_10 '''
		select kint, ksint, sum(kbint) over(order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_10 '''
		select kint, ksint, sum(kbint) over(order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_11 '''
		select kint, ksint, sum(kbint) over(order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_11 '''
		select kint, ksint, sum(kbint) over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_12 '''
		select kint, ksint, sum(kbint) over(order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_12 '''
		select kint, ksint, sum(kbint) over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_13 '''
		select kint, ksint, sum(kbint) over(order by kint range unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_13 '''
		select kint, ksint, sum(kbint) over(order by kint range unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_14 '''
		select kint, ksint, sum(kbint) over(order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_14 '''
		select kint, ksint, sum(kbint) over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_15 '''
		select kint, ksint, sum(kbint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_15 '''
		select kint, ksint, sum(kbint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_16 '''
		select kint, ksint, sum(kbint) over(order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_sum_f_notnull_16 '''
		select kint, ksint, sum(kbint) over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_pb '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint) as wf from fn_test order by kint'''
	qt_sql_sum_pb_notnull '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_1 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_1 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_2 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_2 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_3 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows current row) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_3 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_4 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_4 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_5 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_5 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_6 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_6 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_7 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_7 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_8 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_8 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_9 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_9 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_10 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_10 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_11 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_11 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_12 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_12 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_13 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint range unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_13 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint range unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_14 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_14 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_15 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_15 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_sum_f_pb_16 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_sum_f_pb_notnull_16 '''
		select kint, ksint, sum(kbint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''

	qt_sql_dense_rank '''
		select kint, ksint, dense_rank() over() as wf from fn_test order by kint'''
	qt_sql_dense_rank_notnull '''
		select kint, ksint, dense_rank() over() as wf from fn_test_not_nullable order by kint'''
	qt_sql_dense_rank_pb '''
		select kint, ksint, dense_rank() over(partition by kstr order by kint) as wf from fn_test order by kint'''
	qt_sql_dense_rank_pb_notnull '''
		select kint, ksint, dense_rank() over(partition by kstr order by kint) as wf from fn_test_not_nullable order by kint'''

	qt_sql_first_value '''
		select kint, ksint, first_value(kint) over() as wf from fn_test order by kint'''
	qt_sql_first_value_notnull '''
		select kint, ksint, first_value(kint) over() as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_1 '''
		select kint, ksint, first_value(kint) over(order by kint rows unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_1 '''
		select kint, ksint, first_value(kint) over(order by kint rows unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_2 '''
		select kint, ksint, first_value(kint) over(order by kint rows 2 preceding) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_2 '''
		select kint, ksint, first_value(kint) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_3 '''
		select kint, ksint, first_value(kint) over(order by kint rows current row) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_3 '''
		select kint, ksint, first_value(kint) over(order by kint rows current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_4 '''
		select kint, ksint, first_value(kint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_4 '''
		select kint, ksint, first_value(kint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_5 '''
		select kint, ksint, first_value(kint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_5 '''
		select kint, ksint, first_value(kint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_6 '''
		select kint, ksint, first_value(kint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_6 '''
		select kint, ksint, first_value(kint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_7 '''
		select kint, ksint, first_value(kint) over(order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_7 '''
		select kint, ksint, first_value(kint) over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_8 '''
		select kint, ksint, first_value(kint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_8 '''
		select kint, ksint, first_value(kint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_9 '''
		select kint, ksint, first_value(kint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_9 '''
		select kint, ksint, first_value(kint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_10 '''
		select kint, ksint, first_value(kint) over(order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_10 '''
		select kint, ksint, first_value(kint) over(order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_11 '''
		select kint, ksint, first_value(kint) over(order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_11 '''
		select kint, ksint, first_value(kint) over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_12 '''
		select kint, ksint, first_value(kint) over(order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_12 '''
		select kint, ksint, first_value(kint) over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_13 '''
		select kint, ksint, first_value(kint) over(order by kint range unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_13 '''
		select kint, ksint, first_value(kint) over(order by kint range unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_14 '''
		select kint, ksint, first_value(kint) over(order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_14 '''
		select kint, ksint, first_value(kint) over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_15 '''
		select kint, ksint, first_value(kint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_15 '''
		select kint, ksint, first_value(kint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_16 '''
		select kint, ksint, first_value(kint) over(order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_notnull_16 '''
		select kint, ksint, first_value(kint) over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_pb '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint) as wf from fn_test order by kint'''
	qt_sql_first_value_pb_notnull '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_1 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_1 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_2 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_2 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_3 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows current row) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_3 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_4 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_4 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_5 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_5 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_6 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_6 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_7 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_7 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_8 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_8 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_9 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_9 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_10 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_10 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_11 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_11 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_12 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_12 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_13 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint range unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_13 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint range unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_14 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_14 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_15 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_15 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_first_value_f_pb_16 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_first_value_f_pb_notnull_16 '''
		select kint, ksint, first_value(kint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''

	qt_sql_lag '''
		select kint, ksint, lag(kint, 2, 1) over() as wf from fn_test order by kint'''
	qt_sql_lag_notnull '''
		select kint, ksint, lag(kint, 2, 1) over() as wf from fn_test_not_nullable order by kint'''
	qt_sql_lag_pb '''
		select kint, ksint, lag(kint, 2, 1) over(partition by kstr order by kint) as wf from fn_test order by kint'''
	qt_sql_lag_pb_notnull '''
		select kint, ksint, lag(kint, 2, 1) over(partition by kstr order by kint) as wf from fn_test_not_nullable order by kint'''

	qt_sql_last_value '''
		select kint, ksint, last_value(kint) over() as wf from fn_test order by kint'''
	qt_sql_last_value_notnull '''
		select kint, ksint, last_value(kint) over() as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_1 '''
		select kint, ksint, last_value(kint) over(order by kint rows unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_1 '''
		select kint, ksint, last_value(kint) over(order by kint rows unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_2 '''
		select kint, ksint, last_value(kint) over(order by kint rows 2 preceding) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_2 '''
		select kint, ksint, last_value(kint) over(order by kint rows 2 preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_3 '''
		select kint, ksint, last_value(kint) over(order by kint rows current row) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_3 '''
		select kint, ksint, last_value(kint) over(order by kint rows current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_4 '''
		select kint, ksint, last_value(kint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_4 '''
		select kint, ksint, last_value(kint) over(order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_5 '''
		select kint, ksint, last_value(kint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_5 '''
		select kint, ksint, last_value(kint) over(order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_6 '''
		select kint, ksint, last_value(kint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_6 '''
		select kint, ksint, last_value(kint) over(order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_7 '''
		select kint, ksint, last_value(kint) over(order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_7 '''
		select kint, ksint, last_value(kint) over(order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_8 '''
		select kint, ksint, last_value(kint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_8 '''
		select kint, ksint, last_value(kint) over(order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_9 '''
		select kint, ksint, last_value(kint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_9 '''
		select kint, ksint, last_value(kint) over(order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_10 '''
		select kint, ksint, last_value(kint) over(order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_10 '''
		select kint, ksint, last_value(kint) over(order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_11 '''
		select kint, ksint, last_value(kint) over(order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_11 '''
		select kint, ksint, last_value(kint) over(order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_12 '''
		select kint, ksint, last_value(kint) over(order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_12 '''
		select kint, ksint, last_value(kint) over(order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_13 '''
		select kint, ksint, last_value(kint) over(order by kint range unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_13 '''
		select kint, ksint, last_value(kint) over(order by kint range unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_14 '''
		select kint, ksint, last_value(kint) over(order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_14 '''
		select kint, ksint, last_value(kint) over(order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_15 '''
		select kint, ksint, last_value(kint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_15 '''
		select kint, ksint, last_value(kint) over(order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_16 '''
		select kint, ksint, last_value(kint) over(order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_notnull_16 '''
		select kint, ksint, last_value(kint) over(order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_pb '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint) as wf from fn_test order by kint'''
	qt_sql_last_value_pb_notnull '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_1 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_1 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_2 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_2 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows 2 preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_3 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows current row) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_3 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_4 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_4 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_5 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_5 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between unbounded preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_6 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_6 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_7 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_7 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between 2 preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_8 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_8 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between 2 preceding and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_9 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_9 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between 2 preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_10 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_10 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between current row and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_11 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_11 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between current row and 2 following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_12 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_12 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint rows between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_13 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint range unbounded preceding) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_13 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint range unbounded preceding) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_14 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_14 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint range between unbounded preceding and current row) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_15 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_15 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint range between unbounded preceding and unbounded following) as wf from fn_test_not_nullable order by kint'''
	qt_sql_last_value_f_pb_16 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test order by kint'''
	qt_sql_last_value_f_pb_notnull_16 '''
		select kint, ksint, last_value(kint) over(partition by kstr order by kint range between current row and unbounded following) as wf from fn_test_not_nullable order by kint'''

	qt_sql_lead '''
		select kint, ksint, lead(kint, 2, 1) over() as wf from fn_test order by kint'''
	qt_sql_lead_notnull '''
		select kint, ksint, lead(kint, 2, 1) over() as wf from fn_test_not_nullable order by kint'''
	qt_sql_lead_pb '''
		select kint, ksint, lead(kint, 2, 1) over(partition by kstr order by kint) as wf from fn_test order by kint'''
	qt_sql_lead_pb_notnull '''
		select kint, ksint, lead(kint, 2, 1) over(partition by kstr order by kint) as wf from fn_test_not_nullable order by kint'''

	qt_sql_ntile '''
		select kint, ksint, ntile(3) over() as wf from fn_test order by kint'''
	qt_sql_ntile_notnull '''
		select kint, ksint, ntile(3) over() as wf from fn_test_not_nullable order by kint'''
	qt_sql_ntile_pb '''
		select kint, ksint, ntile(3) over(partition by kstr order by kint) as wf from fn_test order by kint'''
	qt_sql_ntile_pb_notnull '''
		select kint, ksint, ntile(3) over(partition by kstr order by kint) as wf from fn_test_not_nullable order by kint'''

	qt_sql_rank '''
		select kint, ksint, rank() over() as wf from fn_test order by kint'''
	qt_sql_rank_notnull '''
		select kint, ksint, rank() over() as wf from fn_test_not_nullable order by kint'''
	qt_sql_rank_pb '''
		select kint, ksint, rank() over(partition by kstr order by kint) as wf from fn_test order by kint'''
	qt_sql_rank_pb_notnull '''
		select kint, ksint, rank() over(partition by kstr order by kint) as wf from fn_test_not_nullable order by kint'''

	qt_sql_row_number '''
		select kint, ksint, row_number() over() as wf from fn_test order by kint'''
	qt_sql_row_number_notnull '''
		select kint, ksint, row_number() over() as wf from fn_test_not_nullable order by kint'''
	qt_sql_row_number_pb '''
		select kint, ksint, row_number() over(partition by kstr order by kint) as wf from fn_test order by kint'''
	qt_sql_row_number_pb_notnull '''
		select kint, ksint, row_number() over(partition by kstr order by kint) as wf from fn_test_not_nullable order by kint'''

}