<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->

# choose a base image
FROM bitnami/minideb:latest

# replace according to your needs
ARG package_url=Local binary package path, concatenated with package_name to get the complete directory
# e.g. ARG package_url=./resource

ARG package_name=binary package filename
# e.g. ARG package_name=apache-doris-1.1.3-bin-be-x86_64.tar.gz

ARG package_path=The file directory name after decompression
# e.g. ARG package_path=apache-doris-1.1.3-bin-be-x86_64

# set environment variables
ENV PATH="/usr/local/apache-doris/be/bin:/usr/local/apache-doris/apache_hdfs_broker/bin:$PATH"

# download the software to the mirror and replace it as needed
COPY $package_url/$package_name /usr/local/

# deploy software
RUN tar -zxvf /usr/local/$package_name -C /usr/local/ && \
    mv /usr/local/$package_path /usr/local/apache-doris && \
    rm -rf /usr/local/$package_name /usr/local/apache-doris/fe /usr/local/apache-doris/udf

CMD ["bash"]
