# choose a base image
FROM bitnami/minideb:latest

# replace according to your needs
ARG package_url=Local binary package path, concatenated with package_name to get the complete directory
# e.g. ARG package_url=./resource

ARG package_name=binary package filename
# e.g. ARG package_name=apache-doris-1.1.3-bin-be-x86_64.tar.gz

ARG package_path=The file directory name after decompression
# e.g. ARG package_path=apache-doris-1.1.3-bin-be-x86_64

# set environment variables
ENV PATH="/usr/local/apache-doris/be/bin:/usr/local/apache-doris/apache_hdfs_broker/bin:$PATH"

# download the software to the mirror and replace it as needed
COPY $package_url/$package_name /usr/local/

# deploy software
RUN tar -zxvf /usr/local/$package_name -C /usr/local/ && \
    mv /usr/local/$package_path /usr/local/apache-doris && \
    rm -rf /usr/local/$package_name /usr/local/apache-doris/fe /usr/local/apache-doris/udf

CMD ["bash"]
