CREATE TABLE IF NOT EXISTS lineitem (
  L_SHIPDATE    DATE NOT NULL,
  L_ORDERKEY    bigint NOT NULL,
  L_LINENUMBER  int not null,
  L_PARTKEY     int NOT NULL,
  L_SUPPKEY     int not null,
  L_QUANTITY    DECIMAL(15,2) NOT NULL,
  L_EXTENDEDPRICE  DECIMAL(15,2) NOT NULL,
  L_DISCOUNT    DECIMAL(15,2) NOT NULL,
  L_TAX         DECIMAL(15,2) NOT NULL,
  L_RETURNFLAG  VARCHAR(1) NOT NULL,
  L_LINESTATUS  VARCHAR(1) NOT NULL,
  L_COMMITDATE  DATE NOT NULL,
  L_RECEIPTDATE DATE NOT NULL,
  L_SHIPINSTRUCT VARCHAR(25) NOT NULL,
  L_SHIPMODE     VARCHAR(10) NOT NULL,
  L_COMMENT      VARCHAR(44) NOT NULL
)
DUPLICATE KEY(L_SHIPDATE, L_ORDERKEY)
DISTRIBUTED BY HASH(L_ORDERKEY) BUCKETS 3
PROPERTIES (
  "replication_num" = "1"
)

