CREATE TABLE IF NOT EXISTS nation  (
  N_NATIONKEY  int NOT NULL,
  N_NAME       VARCHAR(25) NOT NULL,
  N_REGIONKEY  int NOT NULL,
  N_COMMENT    VARCHAR(152)
)
DUPLICATE KEY(N_NATIONKEY)
DISTRIBUTED BY HASH(N_NATIONKEY) BUCKETS 3
PROPERTIES (
  "replication_num" = "1"
)

