CREATE TABLE IF NOT EXISTS partsupp (
  PS_PARTKEY     int NOT NULL,
  PS_SUPPKEY     int NOT NULL,
  PS_AVAILQTY    int NOT NULL,
  PS_SUPPLYCOST  DECIMAL(15,2)  NOT NULL,
  PS_COMMENT     VARCHAR(199) NOT NULL
)
DUPLICATE KEY(PS_PARTKEY)
DISTRIBUTED BY HASH(PS_PARTKEY) BUCKETS 3
PROPERTIES (
  "replication_num" = "1"
)

