CREATE TABLE IF NOT EXISTS region (
  R_REGIONKEY  int NOT NULL,
  R_NAME       VARCHAR(25) NOT NULL,
  R_COMMENT    VARCHAR(152)
)
DUPLICATE KEY(R_REGIONKEY)
DISTRIBUTED BY HASH(R_REGIONKEY) BUCKETS 3
PROPERTIES (
  "replication_num" = "1"
)

