CREATE TABLE IF NOT EXISTS supplier (
  S_SUPPKEY     int NOT NULL,
  S_NAME        VARCHAR(25) NOT NULL,
  S_ADDRESS     VARCHAR(40) NOT NULL,
  S_NATIONKEY   int NOT NULL,
  S_PHONE       VARCHAR(15) NOT NULL,
  S_ACCTBAL     DECIMAL(15,2) NOT NULL,
  S_COMMENT     VARCHAR(101) NOT NULL
)
DUPLICATE KEY(S_SUPPKEY)
DISTRIBUTED BY HASH(S_SUPPKEY) BUCKETS 3
PROPERTIES (
  "replication_num" = "1"
)
