set sql_dialect='presto';
set enable_fallback_to_original_planner=false;
set debug_skip_fold_constant=false;
-- SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[1, 2]); # error: errCode = 2, detailMessage = Syntax error in line 1:	... contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[1, 2]);	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[3, 4]); # error: errCode = 2, detailMessage = Syntax error in line 1:	... contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[3, 4]);	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[5, 6]); # error: errCode = 2, detailMessage = Syntax error in line 1:	... contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[5, 6]);	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[1, 2, 4]); # error: errCode = 2, detailMessage = Syntax error in line 1:	... contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[1, 2...	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1, 2, 3, NULL, 4, 5, 6], ARRAY[3, NULL, 4]); # error: errCode = 2, detailMessage = Syntax error in line 1:	... contains_sequence(ARRAY[1, 2, 3, NULL, 4, 5, 6], ARRA...	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[1, 2, 3, 4, 5, 6]); # error: errCode = 2, detailMessage = Syntax error in line 1:	... contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[1, 2...	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[]); # error: errCode = 2, detailMessage = Syntax error in line 1:	SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[]);	                                ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY['1', '2', '3'], ARRAY['1', '2']); # error: errCode = 2, detailMessage = Syntax error in line 1:	...ontains_sequence(ARRAY['1', '2', '3'], ARRAY['1', '2']);	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1.1, 2.2, 3.3], ARRAY[1.1, 2.2]); # error: errCode = 2, detailMessage = Syntax error in line 1:	...ontains_sequence(ARRAY[1.1, 2.2, 3.3], ARRAY[1.1, 2.2]);	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[ARRAY[1,2], ARRAY[3], ARRAY[4,5]], ARRAY[ARRAY[1,2], ARRAY[3]]); # error: errCode = 2, detailMessage = Syntax error in line 1:	...ins_sequence(ARRAY[ARRAY[1,2], ARRAY[3], ARRAY[4,5]], ...	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[ARRAY[1,2], ARRAY[3], ARRAY[4,5]], ARRAY[ARRAY[1,2], ARRAY[4]]); # error: errCode = 2, detailMessage = Syntax error in line 1:	...ins_sequence(ARRAY[ARRAY[1,2], ARRAY[3], ARRAY[4,5]], ...	                             ^	Encountered: COMMA	Expected: ||	
set debug_skip_fold_constant=true;
-- SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[1, 2]); # error: errCode = 2, detailMessage = Syntax error in line 1:	... contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[1, 2]);	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[3, 4]); # error: errCode = 2, detailMessage = Syntax error in line 1:	... contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[3, 4]);	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[5, 6]); # error: errCode = 2, detailMessage = Syntax error in line 1:	... contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[5, 6]);	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[1, 2, 4]); # error: errCode = 2, detailMessage = Syntax error in line 1:	... contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[1, 2...	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1, 2, 3, NULL, 4, 5, 6], ARRAY[3, NULL, 4]); # error: errCode = 2, detailMessage = Syntax error in line 1:	... contains_sequence(ARRAY[1, 2, 3, NULL, 4, 5, 6], ARRA...	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[1, 2, 3, 4, 5, 6]); # error: errCode = 2, detailMessage = Syntax error in line 1:	... contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[1, 2...	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[]); # error: errCode = 2, detailMessage = Syntax error in line 1:	SELECT contains_sequence(ARRAY[1, 2, 3, 4, 5, 6], ARRAY[]);	                                ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY['1', '2', '3'], ARRAY['1', '2']); # error: errCode = 2, detailMessage = Syntax error in line 1:	...ontains_sequence(ARRAY['1', '2', '3'], ARRAY['1', '2']);	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[1.1, 2.2, 3.3], ARRAY[1.1, 2.2]); # error: errCode = 2, detailMessage = Syntax error in line 1:	...ontains_sequence(ARRAY[1.1, 2.2, 3.3], ARRAY[1.1, 2.2]);	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[ARRAY[1,2], ARRAY[3], ARRAY[4,5]], ARRAY[ARRAY[1,2], ARRAY[3]]); # error: errCode = 2, detailMessage = Syntax error in line 1:	...ins_sequence(ARRAY[ARRAY[1,2], ARRAY[3], ARRAY[4,5]], ...	                             ^	Encountered: COMMA	Expected: ||	
-- SELECT contains_sequence(ARRAY[ARRAY[1,2], ARRAY[3], ARRAY[4,5]], ARRAY[ARRAY[1,2], ARRAY[4]]) # error: errCode = 2, detailMessage = Syntax error in line 1:	...ins_sequence(ARRAY[ARRAY[1,2], ARRAY[3], ARRAY[4,5]], ...	                             ^	Encountered: COMMA	Expected: ||	
