# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
version: "3"
services:
  namenode:
    image: singularities/hadoop:2.8
    volumes:
      - /data:/data
    command: start-hadoop namenode
    hostname: namenode
    environment:
      HDFS_USER: hdfsuser
    ports:
      - "8020:8020"
      - "14000:14000"
      - "50070:50070"
      - "50075:50075"
      - "10020:10020"
      - "13562:13562"
      - "19888:19888"
  datanode:
    image: singularities/hadoop:2.8
    hostname: datanode
    volumes:
      - /data/hdfs/:/data
    command: start-hadoop datanode namenode
    environment:
      HDFS_USER: hdfsuser
    ports:
      - "50010:50010"
    links:
      - namenode

  fe:
    image: apache/doris:2.0.0_alpha-fe-x86_64
    hostname: doris-fe
    volumes:
      - /data/fe/doris-meta/:/opt/apache-doris/fe/doris-meta/
      - /data/fe/log/:/opt/apache-doris/fe/log/
    environment:
      - FE_SERVERS=fe1:172.20.80.1:9010
      - FE_ID=1
    restart: on-failure
    networks:
      doris_net:
        ipv4_address: 172.20.80.1

  be:
    image: apache/doris:2.0.0_alpha-be-x86_64
    hostname: doris-be
    volumes:
      - /data/be/storage/:/opt/apache-doris/be/storage/
      - /data/be/log/:/opt/apache-doris/be/log/
    environment:
      - FE_SERVERS=fe1:172.20.80.1:9010
      - BE_ADDR=172.20.80.2:9050
    depends_on:
      - fe
    restart: on-failure
    networks:
      doris_net:
        ipv4_address: 172.20.80.2

  broker:
    image: apache/doris:1.2.2-broker-x86_64
    hostname: doris-broker
    volumes:
      - /data/broker/conf/:/opt/apache-doris/broker/conf/
      - /data/broker/log/:/opt/apache-doris/broker/log/
    environment:
      - FE_SERVERS=fe1:172.20.80.1:9010
      - BROKER_ADDR=bk1:172.20.80.3:9050
    depends_on:
      - fe
    restart: on-failure
    networks:
      doris_net:
        ipv4_address: 172.20.80.3
networks:
  doris_net:
    ipam:
      config:
        - subnet: 172.20.80.0/24
