--from clickbench table hits
CREATE TABLE IF NOT EXISTS  orc_s3_case9 (
    COUNTERID INT NOT NULL, 
    EVENTDATE INT NOT NULL, 
    USERID BIGINT NOT NULL, 
    EVENTTIME INT NOT NULL, 
    WATCHID BIGINT NOT NULL, 
    JAVAENABLE SMALLINT NOT NULL,
    TITLE STRING NOT NULL,
    GOODEVENT SMALLINT NOT NULL,
    CLIENTIP INT NOT NULL,
    REGIONID INT NOT NULL,
    COUNTERCLASS SMALLINT NOT NULL,
    OS SMALLINT NOT NULL,
    USERAGENT SMALLINT NOT NULL,
    URL STRING NOT NULL,
    REFERER STRING NOT NULL,
    ISREFRESH SMALLINT NOT NULL,
    REFERERCATEGORYID SMALLINT NOT NULL,
    REFERERREGIONID INT NOT NULL,
    URLCATEGORYID SMALLINT NOT NULL,
    URLREGIONID INT NOT NULL,
    RESOLUTIONWIDTH SMALLINT NOT NULL,
    RESOLUTIONHEIGHT SMALLINT NOT NULL,
    RESOLUTIONDEPTH SMALLINT NOT NULL,
    FLASHMAJOR SMALLINT NOT NULL,
    FLASHMINOR SMALLINT NOT NULL,
    FLASHMINOR2 STRING NOT NULL,
    NETMAJOR SMALLINT NOT NULL,
    NETMINOR SMALLINT NOT NULL,
    USERAGENTMAJOR SMALLINT NOT NULL,
    USERAGENTMINOR VARCHAR(255) NOT NULL
)
DUPLICATE KEY (CounterID, EventDate, UserID, EventTime, WatchID) 
DISTRIBUTED BY HASH(UserID) BUCKETS 16
PROPERTIES ("replication_num"="1");
