CREATE CATALOG IF NOT EXISTS hms_hdfs PROPERTIES ( "type" = "hms", "hive.metastore.uris" = "META_URI" );
CREATE CATALOG IF NOT EXISTS hms_oss PROPERTIES ( "type" = "hms", "hive.metastore.uris" = "META_URI", "oss.secret_key" = "SK_INPUT", "oss.endpoint" = "ENDPOINT", "oss.access_key" = "AK_INPUT" );
CREATE CATALOG IF NOT EXISTS hms_jindo PROPERTIES ( "type" = "hms", "hive.metastore.uris" = "META_URI", "oss.secret_key" = "SK_INPUT", "oss.endpoint" = "JINDO_ENDPOINT", "oss.access_key" = "AK_INPUT", "oss.hdfs.enabled" = "true" );

CREATE CATALOG IF NOT EXISTS iceberg_hms PROPERTIES ( "type" = "iceberg", "iceberg.catalog.type" = "hms", "hive.metastore.uris" = "META_URI" );
CREATE CATALOG IF NOT EXISTS iceberg_hms_oss PROPERTIES ( "type" = "iceberg", "iceberg.catalog.type" = "hms", "hive.metastore.uris" = "META_URI", "oss.secret_key" = "SK_INPUT", "oss.endpoint" = "ENDPOINT", "oss.access_key" = "AK_INPUT" );
CREATE CATALOG IF NOT EXISTS iceberg_hms_jindo PROPERTIES ( "type" = "iceberg", "iceberg.catalog.type" = "hms", "hive.metastore.uris" = "META_URI", "oss.secret_key" = "SK_INPUT", "oss.endpoint" = "JINDO_ENDPOINT", "oss.access_key" = "AK_INPUT", "oss.hdfs.enabled" = "true" );

CREATE CATALOG IF NOT EXISTS dlf PROPERTIES( "type" = "hms", "hive.metastore.type" = "dlf", "dlf.proxy.mode" = "DLF_ONLY", "dlf.endpoint" = "DLF_ENDPOINT", "dlf.uid" = "217316283625971977", "dlf.access_key" = "AK_INPUT", "dlf.secret_key" = "SK_INPUT" );
CREATE CATALOG IF NOT EXISTS dlf_jindo PROPERTIES( "type" = "hms", "hive.metastore.type" = "dlf", "dlf.proxy.mode" = "DLF_ONLY", "dlf.endpoint" = "DLF_ENDPOINT", "dlf.uid" = "217316283625971977", "dlf.access_key" = "AK_INPUT", "dlf.secret_key" = "SK_INPUT", "oss.hdfs.enabled" = "true" );
CREATE CATALOG IF NOT EXISTS iceberg_dlf PROPERTIES ( "type"="iceberg", "iceberg.catalog.type" = "hms", "hive.metastore.type" = "dlf", "dlf.endpoint" = "DLF_ENDPOINT", "dlf.region" = "cn-beijing", "dlf.proxy.mode" = "DLF_ONLY", "dlf.uid" = "217316283625971977", "dlf.access_key" = "AK_INPUT", "dlf.secret_key" = "SK_INPUT" );
CREATE CATALOG IF NOT EXISTS iceberg_dlf_jindo PROPERTIES ( "type"="iceberg", "iceberg.catalog.type" = "hms", "hive.metastore.type" = "dlf", "dlf.endpoint" = "DLF_ENDPOINT", "dlf.region" = "cn-beijing", "dlf.proxy.mode" = "DLF_ONLY", "dlf.uid" = "217316283625971977", "dlf.access_key" = "AK_INPUT", "dlf.secret_key" = "SK_INPUT", "oss.hdfs.enabled" = "true" );