name: Auto Reply to PR

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on PR
      uses: ./.github/actions/create-or-update-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
            Thank you for your contribution to Apache Doris.

            Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR)
