name: Clang Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        type: [build, ut]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run ${{ matrix.type }}
        run: |
          export DEFAULT_DIR='/opt/doris'
          export PATH="${DEFAULT_DIR}/ldb-toolchain/bin/:${DEFAULT_DIR}/thirdparty/installed/bin/:${PATH}"
          export DORIS_THIRDPARTY="${DEFAULT_DIR}/thirdparty"

          mkdir "${DEFAULT_DIR}"

          wget https://github.com/amosbird/ldb_toolchain_gen/releases/download/v0.12/ldb_toolchain_gen.sh \
            -q -O /tmp/ldb_toolchain_gen.sh
          bash /tmp/ldb_toolchain_gen.sh "${DEFAULT_DIR}/ldb-toolchain"

          mkdir -p "${DORIS_THIRDPARTY}/installed"
          docker run --rm --mount=type=bind,source="${DORIS_THIRDPARTY}/installed",target=/installed \
            apache/doris:build-env-ldb-toolchain-latest bash -c 'mv /var/local/thirdparty/installed/* /installed'

          sudo apt update
          sudo apt upgrade
          sudo apt install --yes tzdata ccache byacc

          # set timezone
          sudo ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo dpkg-reconfigure --frontend noninteractive tzdata

          date

          if [[ "${{ matrix.type }}" == 'build' ]]; then
            DORIS_TOOLCHAIN=clang ./build.sh -j "$(nproc)" --be --clean
          else
            DORIS_TOOLCHAIN=clang ./run-be-ut.sh -j "$(nproc)" --run --clean
          fi
