# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
name: License Check
on:
  pull_request_target:
  push:
    branches:
      - master
  workflow_dispatch:
  issue_comment:
    types: [ created ]

jobs:
  license-check:
    name: "License Check"
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request_target') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/master') ||
      (github.event_name == 'issue_comment' &&
       github.event.comment.body == 'run buildall' &&
       github.actor == 'doris-robot' &&
       github.event.issue.user.login == 'github-actions[bot]')
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v3

      - name: Checkout ${{ github.ref }} ( ${{ github.event.pull_request.head.sha }} )
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check License
        uses: apache/skywalking-eyes@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
